### ISSUE TITLE
Error on send message

### ISSUE THREAD

**Issue by DelphiBoy2010** [sochix/TLSharp#1]
when I call SendMessage method, get error : Unable to read beyond the end of the stream.
!?

**Comment by sochix** [comment]
Post your code snippet here, please

**Comment by DelphiBoy2010** [comment]
I use VS 2013, 
Code is:
 NotificatioClientTests nt = new NotificatioClientTests();
nt.Init();                
nt.AuthUser();
nt.SendMessage();

In SendMessage method when try call 
await client.Connect();
error raise.

**Comment by sochix** [comment]
You should firstly create valid session. Run the AuthUser test, and set a breakpoint on `			var code = "123"; // you can change code in debugger` line. You should get a code from telegram and replace with it value of `code` variable. Than continue execution. You'll see created `session.dat` file.

````csharp
[TestMethod]
public async Task AuthUser()
{
  var store = new FileSessionStore();
  var client = new TelegramClient(store, "session");
  await client.Connect();

  var hash = await client.SendCodeRequest(NumberToAuthenticate);
  var code = "123"; // you can change code in debugger

  var user = await client.MakeAuth(NumberToAuthenticate, hash, code);

 Assert.IsNotNull(user);
}
````

After this done, try to run `SendMessage` test

**Comment by DelphiBoy2010** [comment]
Thanks.
The problem solved, but I got following error on authentication:
PHONE_MIGRATE_4

**Comment by sochix** [comment]
Read https://github.com/sochix/TLSharp#faq

**Comment by delphiassistant** [comment]
I never get beyond this line:
var hash = await client.SendCodeRequest(NumberToAuthenticate);
It throws same exception "System.IO.EndOfStreamException: Unable to read beyond the end of the stream." and does not return hash, so no session.dat file is created.

**Comment by sochix** [comment]
Did you fill app.config correctly? Did you use correct apiId and apiHash?

**Comment by sochix** [comment]
Ok. Problem solved
