### ISSUE TITLE
Connection KeepAlive

### ISSUE THREAD

**Issue by delphiassistant** [sochix/TLSharp#10]
Hi Again.
I'm developing a windows application which serves a WCF Service, which other apps could invoke it for telegram messaging (instead of sms notifications to my users).

After a while since application is idle, it seems that tcp connection get closed and I get errors when calling sendmessage method.
Do have any advice for this problem?

**Comment by sochix** [comment]
See TcpTransport class, don't know a quck solution for this problem. If you found one, please make a pull-request

**Comment by eaba** [comment]
how about this http://www.codeproject.com/Articles/117557/Set-Keep-Alive-Values

**Comment by hosseinGanjyar** [comment]
I have got same issue. I using WCF and I want to alive connections. In below I show my code:
```
var session = new FileSessionStore();
TelegramClient client = new TelegramClient(apiId, apiHash, session, "session_N");
await client.ConnectAsync();
```
How do I using  **client** for reusable it in many times?
@eaba , @delphiassistant  pleasehelp me if you know any thing.
@eaba I have read above article of you, but I haven't understood. Please show a sample for my code.
**Thanks**
