### ISSUE TITLE
MakeAuth request is PHONE_NUMBER_UNOCCUPIED error

### ISSUE THREAD

**Issue by majid23** [sochix/TLSharp#102]
Hello,
In Authorize i request code and i give it in my phone from Telegram.
hash = await client.SendCodeRequest(NumberToAuthenticate);
but when i send code for Authorize with MakeAuth function i have PHONE_NUMBER_UNOCCUPIED error and occur Exception.
Please Help me Why this error occur.

**Comment by sochix** [comment]
Read it https://github.com/sochix/TLSharp#nothing-helps before create an issue
