### ISSUE TITLE
fails in sending message to bot

### ISSUE THREAD

**Issue by siml173** [sochix/TLSharp#103]
hi.
how can i send message to bot. when i try i get invalid peer id error.
please help

**Comment by sochix** [comment]
It haven't implemented yet.

**Comment by siml173** [comment]
is it different with regular sendmessage ??
i added bot to my contact by it's username (testbot). when i try send message to it's id i get that error. any suggestion?

**Comment by siml173** [comment]
if it need implement new method tell me.i will do that. tnx

**Comment by AArayeshi** [comment]
For sending message to Bots use the Bot API.

**Comment by siml173** [comment]
i want use api.

**Comment by AArayeshi** [comment]
Agha Mohammad please review these links:

https://core.telegram.org/bots

https://core.telegram.org/bots/api

**Comment by armanforghani** [comment]
I have the same problem.

**Comment by romi4rd1** [comment]
Try like this :

**Comment by romi4rd1** [comment]
Try like this:
