### ISSUE TITLE
Not working with VS2013

### ISSUE THREAD

**Issue by Mohammad7070** [sochix/TLSharp#108]
while compiling with VS2013 and .NET 4.5.2
lots of error .. (32 errors ... )
Error	1	Unexpected character '$'	 \TLSharp-master\TLSharp-master\TLSharp.Core\Session.cs	18	39	TLSharp.Core

**Comment by rd1975** [comment]
Hi, This project Only work on visual studio 2015

**Comment by colotiline** [comment]
Works for me in Visual Studio 2013 Professional Edition. Of course after some code manipulation.

**Comment by colotiline** [comment]
`TLSharp` uses C# 6.0 features that are not available in VS2013. By the way, you can always download VS2015 Community Edition.
