### ISSUE TITLE
PEER_ID_INVALID during hsitory request

### ISSUE THREAD

**Issue by mikachi** [sochix/TLSharp#109]
Hello, I am trying to get history for the user, using your test "GetHistory"
But I constantly get error PEER_ID_INVALID.
Is it a bug or a feature?

**Comment by mikachi** [comment]
So I've figured out, I was missing IsUserAuthorized check. But why is it false and still allows me to send messages, I am wondering...
Also I am trying to reproduce now full stack using your tests and I started to get error "STORE_INVALID_OBJECT_TYPE" right after the error "PHONE_MIGRATE_4" Do you know what is that? Never seen such error before...

**Comment by colotiline** [comment]
@mikachi, check your API server address. It helped me.

**Comment by colotiline** [comment]
@mikachi, I'm talking about the `STORE_INVALID_OBJECT_TYPE` error.

**Comment by mikachi** [comment]
@colotiline thanks, it's not issue already.
Do you have issues while sending auth code now?
I came into trouble that Telgeram sends code only as SMS and when trying to use it it says PHONE_UNOCCUPIED...

**Comment by colotiline** [comment]
@mikachi no, I didn't. I use preregistered phones and everything is ok. I noticed that Telegram sends code via SMS after `n` requests for auth, so it's ok. I can't help you with `PHONE_UNOCCUPIED`.

**Comment by mikachi** [comment]
@colotiline, what do you mean when saying "I use preregistered phones and everything is ok" Have you ever faced limits problem? When you get blocked from Telegram side

**Comment by colotiline** [comment]
@mikachi I mean that I only used `TLSharp` with a phone number that already was registered in telegram. 

> Have you ever faced limits problem? When you get blocked from Telegram side
Yes. Once I was blocked for 72 hours during development for creating many groups with same title and users. But only once.
