### ISSUE TITLE
Problem with receive message from telegram while running authuser test

### ISSUE THREAD

**Issue by starbug1** [sochix/TLSharp#11]
Hi. 2 of tests(Test Connection and AuthenticationWorks) passed. but when i run authuser test First: I do not receive message from telegram and Second: Where the Session.dat file located? Thanks for your help.
This image is for more info:
http://s6.picofile.com/file/8215040434/from10.PNG

Thanks for you helping.

**Comment by delphiassistant** [comment]
Salam StarBug.
Khoobi?
session.dat file is located in bin folder of TLSharp.Tests project.

The server address modification in TcpTransport.cs is the key. Current working address of telegram server with this api is 149.154.167.90 and 149.154.167.91 .
Other Servers return errors and exceptions.

**Comment by starbug1** [comment]
salam delphiassistant.
mamnonam.
I found it after several hours of distraction. Thanks.

**Comment by sochix** [comment]
@delphiassistant good catch!

**Comment by mehdir92** [comment]
I can not pass and  do not receive a message.What should I do?
@delphiassistant  lotfan komak konid!

**Comment by mehdir92** [comment]
What was said, but I did not pass the test connection

**Comment by mehdir92** [comment]
@starbug1  hi,how to pass test connection?! i go step by step,but failed

**Comment by starbug1** [comment]
@mehdir92 : hi. what error do you receive? but for immediate answer you can see the image that i uploaded in issue. if you have session.dat file in project bin folder, first of all delete it and then you must  run tests one by one.

**Comment by mehdir92** [comment]
@starbug1  tnx for answer.
soale asai inke daghighan bejaye  value haye : numberToAuthenticate,registeredNumber,unregisteredNumber chi bayad bezarim?!
bara 2taye aval maghsad va akhari shomare khodamo dadam! va test ok shod.

at first my problem  was passed test connection,but it and Authenticationwork is ok and pass.
now auttuser test failed. one moment ok and color changed green but again red.

http://s6.picofile.com/file/8221058934/01.PNG

Thank you

**Comment by starbug1** [comment]
@mehdir92 : unregistered number is a number that is not registered in telegram and owner of this number does not use telegram at all. number to authenticate can be your own number. and registered number can be number of you father or mother or any other person's number that has telegram and owner of it has telegram account. about test you must first run TestConnection after that AuthenticationWorks and after that AuthUser. when you run AuthUser you must debug code and replace the code you get from telegram in runtime inside var variable. then continue running.

**Comment by mehdir92** [comment]
@starbug1  You're right , but I do not received  any code.
What should I do??!

**Comment by starbug1** [comment]
@mehdir92 : if you do the tasks in the right way, you must receive message. this code will send to your telegram account. check with telegram web or desktop.

**Comment by mehdir92** [comment]
@starbug1  
at first thank u for replying,really tnx, i passed two step,during 3rd step i receive sms at  my phone not telegram,replace this code but yet fail.i'm confused :|

**Comment by mehdir92** [comment]
this time that i test,the code sent to mt telegram account and replace it BUT again fail.
this errore show:  phone code invalid!!

**Comment by mehdir92** [comment]
@starbug1  
tnx alot

**Comment by mehdir92** [comment]
oohhh YES , I could :) 
send message test is pass ,too 
Now, what to do?!
@sochix 
@starbug1
