### ISSUE TITLE
PHONE_NUMBER_UNOCCUPIED

### ISSUE THREAD

**Issue by mikachi** [sochix/TLSharp#110]
Hello,

I started getting strange error: PHONE_NUMBER_UNOCCUPIED. 
During authentication call code is coming via SMS (!)  though I have Telegram and ApiId and Hash set correctly. And when I put SMS code I get error PHONE_NUMBER_UNOCCUPIED...

Do you know about any changes made by Telegram?

**Comment by kaykujo** [comment]
try delete session.dat, clean solution and build again. It works for me.

**Comment by mikachi** [comment]
Could you please confirm that you are able to add new TL phone number to send messages?
I constantly get SMS only verification code and it doesn't work properly after taht...
Thanks in advance.

**Comment by kaykujo** [comment]
Yes i can. Try delete session.dat first, refresh the project's folder, clean solution and build again. Works for me every time.

**Comment by detho** [comment]
try this https://core.telegram.org/method/auth.signUp
