### ISSUE TITLE
PEER_ID_INVALID when sending a message.

### ISSUE THREAD

**Issue by mtbitcoin** [sochix/TLSharp#111]
Occasionally it would fail to send a message with "ImportByUserNameAndSendMessage" and return the PEER_ID_INVALID error code. However, the username is valid and using the normal telegram app i am able to send a message to him

**Comment by MindsterCool** [comment]
I have same problem.
ImportByUsername is not working
sendMessage can only work if the recipient alredy in contact list ?
If so, TLsharp can't send message to Telegram Bot.

**Comment by AndreiKrutikov** [comment]
It just because bot is not InputPeerContact, but InputPeerForeign. So you have to write smth like
 `        public async Task SendMessageToBot(int id, long access_hash, string message)
        {
            var request = new SendMessageRequest(new InputPeerForeignConstructor(id, access_hash), message);

            await _sender.Send(request);
            await _sender.Receive(request);
        }
`
