### ISSUE TITLE
HandleBadMsgNotification cases 16, 17, 32 and 33

### ISSUE THREAD

**Issue by colotiline** [sochix/TLSharp#112]
Hi.

I've solved some issues in the library's `HandleBadMsgNotification` method. 

For cases 16 and 17 you can use:
```
var bigInteger = new BigInteger(messageId.ToString("#"));
					
var serverUnixTime = int.Parse(bigInteger.ShiftRight(32).ToString(10));
var serverTime = serverUnixTime.ToDateTime();

var timeOffset = serverTime - DateTime.UtcNow;

_session.TimeOffset = timeOffset.Seconds;
Send(request);

return true;
```

For 32:
```
_session.Sequence++;
Send(request);

return true;
```

For 33:
```
_session.Sequence--;
Send(request);

return true;
```

Solution for cases 16 and 17 is completely valid compare to [webogram](https://github.com/zhukov/webogram). 

As for 32, 33 - them are not so clever, but solved my problem.

I can't create a pull request, because I've made your code not async, so I just left my solution here.

**Comment by sochix** [comment]
Thanks!
