### ISSUE TITLE
Send Message to Group

### ISSUE THREAD

**Issue by lfsolutions** [sochix/TLSharp#113]
Amazing One by the way

Do you have a method to send it to Group ?

**Comment by chester89** [comment]
Looks like it's similar to just sending message to a contact. Will take a look

**Comment by colotiline** [comment]
Easy. You need to add to `TelegramClient` the method below:
```
public void SendMessageToChat(int id, string message)
{
	var request = new SendMessageRequest(new InputPeerChatConstructor(id), message);

	_sender.Send(request);
	_sender.Recieve(request);
}
```

**Comment by chester89** [comment]
And I can receive chatId by it's name, I assume?

2016-03-18 13:58 GMT+03:00 Constantine Colotiline <notifications@github.com>
:

> Easy. You need to add to TelegramClient the method below:
>
> public void SendMessageToChat(int id, string message)
> {
>     var request = new SendMessageRequest(new InputPeerChatConstructor(id), message);
>
>     _sender.Send(request);
>     _sender.Recieve(request);
> }
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/sochix/TLSharp/issues/113#issuecomment-198307196>
>



-- 
Yours faithfully,
Gleb

**Comment by colotiline** [comment]
@chester89, don't know. I get a chat's id after I create it. But I think that you can use the `GetDialogs` method according to documentation [GetDialogs](https://core.telegram.org/method/messages.getDialogs).

**Comment by sochix** [comment]
Someone please add it to Readme.md
