### ISSUE TITLE
What value to use for sessionUserId parameter?

### ISSUE THREAD

**Issue by chester89** [sochix/TLSharp#114]
What value should I use for sessionUserId parameter?
Simple example - I want to receive some updates via telegram from external system. Now I have my account and username, api_id and api_hash. I would like to create new chat, add my account there and send messages to this new chat from a console/web app. 
Obviously, "store" does not work and neither did my username - API says AUTH_KEY_UNREGISTERED

**Comment by arman-khangi** [comment]
I faced same problem and I think you can solve it by calling MakeAuth Method.

**Comment by chester89** [comment]
I see. Thanks, I will try

2016-04-07 12:58 GMT+03:00 arman <notifications@github.com>:

> I faced same problem and I think you can solve it by calling MakeAuth
> Method.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/sochix/TLSharp/issues/114#issuecomment-206792697>
>



-- 
Yours faithfully,
Gleb
