### ISSUE TITLE
Problem with Importing contacts

### ISSUE THREAD

**Issue by JaswinderLayal** [sochix/TLSharp#117]
I had problem while fetching contacts.I got contacts user_ids, but when i try to get users,i received 0xCAB35E18 code instead of 0xf2fb8319. For hash i am sending hash of empty string. Is something i am missing? or something wrong with api documentation?

**Comment by bps1372** [comment]
I have the exact same problem. 0xf2fb8319 doesen't seem to even exist in tl-scheme : https://core.telegram.org/scheme 
i changed usercontactconstructor code to 0xCAB35E18 but didn't work!

**Comment by JaswinderLayal** [comment]
I found the solution to the problem 
In UserContactConstructor's read() method  add the   reader.ReadUInt32(); after       this.access_hash = reader.ReadInt64();

             ```
  this.access_hash = reader.ReadInt64();
                 reader.ReadUInt32(); 
               this.phone = Serializers.String.read(reader);
```
