### ISSUE TITLE
TlSharp AUTH_KEY_UNREGISTERED

### ISSUE THREAD

**Issue by MaryamMlk** [sochix/TLSharp#119]
I have the same problem: "AUTH_KEY_UNREGISTERED".
this is my code in mvc ,2 actions :
1)first action(Get) is for connecting to server:
var store = new FileSessionStore();
client = new TelegramClient(store, sessionUserId: "session");
await client.Connect();
var hash = await client.SendCodeRequest("myPhoneNumber");

..................................................................

2)then action(Post) is for authenticationg:
var user = await client.MakeAuth("myPhoneNumber", Session["hash"].ToString(), code);

.....................................................................

after connection and authentication , I called other actions for:
var ImportContactByPhoneNumber = await client.ImportContactByPhoneNumber(phone);

......................................................................
I checked the existence of session.dat in "C:\Program Files (x86)\IIS Express\session.dat"
and 
the client.IsUserAuthorized() is True
....................................................................

**Comment by headria** [comment]
clear all "await" in api

**Comment by MaryamMlk** [comment]
thanks I changed the code into:
-------------------------------------
var ImportContactByPhoneNumber = client.ImportContactByPhoneNumber(phone);
------------------------------------
but the error has changed into:
---------------------------------------
Couldn't read the packet length
--------------------------------------
I think , this is a problem with receiving the packets
but when I connecting to server I do not have this  problem!!!

**Comment by MaryamMlk** [comment]
solved  thanks

**Comment by headria** [comment]
how ?
