### ISSUE TITLE
Why i get rpc_error FLOOD_WAIT

### ISSUE THREAD

**Issue by starbug1** [sochix/TLSharp#12]
Hi. i am doing a registeration check for my list of phone numbers. but after doing 9 or 10 of checks an rpc error for FLOOD_WAIT occur and in debug write that you must wait(for example 270 sec.) why this error occur? and how to pass from this error. please explain about it. Thanks.

**Comment by sochix** [comment]
See this https://core.telegram.org/api/errors#420-flood

**Comment by starbug1** [comment]
Ok. I got it. then how many attempts of one method i can invoke?

**Comment by sochix** [comment]
I don't know

суббота, 3 октября 2015 г. пользователь starbug1 написал:

> Ok. I got it. then how many attempts of one method i can invoke?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sochix/TLSharp/issues/12#issuecomment-145210141>.
>


-- 
Best regards, Ilya (http://sochix.ru)
С уважением, Илья (http://sochix.ru)

**Comment by delphiassistant** [comment]
>Ok. I got it. then how many attempts of one method i can invoke?
Put a delay of 2 seconds between invokes.

**Comment by starbug1** [comment]
@delphiassistant : Thanks. i placed delay of 2500 between every method's invoke, but after almost 10 request FLOOD_WAIT error occur and say you should wait for example 270 sec. and because i need to send bulk requests to telegram what i must do to pass this error. Thanks.

**Comment by delphiassistant** [comment]
Yeah and ahhh....
I seen it as well. it's not 10, that delay is per 9 request and is really
frustrating.
This occurs after 9 invokes to send message too.
در تاریخ ۴ اکتبر ۲۰۱۵ ۱۹:۳۰، "starbug1" <notifications@github.com> نوشت:

**Comment by starbug1** [comment]
@delphiassistant: then you say telegram server works with count of requests not with (count/time)? i mean count of requests in time unit is not important?

**Comment by delphiassistant** [comment]
I can't say exectly which parameter is important.
در تاریخ ۴ اکتبر ۲۰۱۵ ۲۱:۵۸، "starbug1" <notifications@github.com> نوشت:

**Comment by eslamih10** [comment]
@starbug1,did you find solution for flood_wait?

**Comment by delphiassistant** [comment]
Not yet. It's limit is too dumb. 9 Requests and time is not important.

**Comment by eslamih10** [comment]
mr keramati,You have worked with telegram API?

**Comment by delphiassistant** [comment]
Sure.

**Comment by starbug1** [comment]
@eslamih10: as delphiassistant said there is a maximum number of attempts of one method. but if you can delete your session and recreate it under 200 second(for every usual waits), then you can do what you want.

**Comment by eslamih10** [comment]
@delphiassistant,Did you use Visual studio 2013 or 2015?

**Comment by eslamih10** [comment]
@starbug1,Unfortunately,When I delete the session, there is still the problem!

**Comment by starbug1** [comment]
you must delete session. and create it again and add the code you get from telegram to it.this process must be done under logic time.

**Comment by delphiassistant** [comment]
>as delphiassistant said there is a maximum number of attempts of one method. but if you can delete your session and recreate it under 200 second(for every usual waits), then you can do what you want.

This will be a tedious task since you will need to get another authentication code from telegram and add it into the code.

>Did you use Visual studio 2013 or 2015?
VS2015.

>Unfortunately,When I delete the session, there is still the problem!
It seems to be based on invoker ip address.

**Comment by starbug1** [comment]
@delphiassistant: you can do this programatically. not with your hands. just be a  bit creative.

**Comment by delphiassistant** [comment]
You mean by having telegram client app open, and using windows hooks?

**Comment by alipishvaee** [comment]
it means There is Not A Soultion For Preventing This Error?

**Comment by hosseinGanjyar** [comment]
@starbug1 Delete session.dat file?
how?

**Comment by mostafa8026** [comment]
khosham miad hame irani hastin o english miharfin :)

**Comment by hosseinGanjyar** [comment]
I solved this issue. please send your question in my group:
https://t.me/joinchat/HhLHow3Ed97A0gRZo7Ggog

**Comment by hosseinGanjyar** [comment]
@mostafa8026 Foolish!
