### ISSUE TITLE
Error when tow-step password protection is active

### ISSUE THREAD

**Issue by Ramin-Bateni** [sochix/TLSharp#126]
I use tow-step password protection for my phone number in telegram. Now when i use `AuthUser()`, i get this error in VS:
> PHONE_PASSWORD_PROTECTED

Also i get this message by sms from telegram:

> You are using an outdated app that doesn't support 2-Step verification. Please update your app to log in to telegram.

What is the solution?

**Comment by RaaaGEE** [comment]
So. Two-step auth used undocumented packet/method: `auth.checkPassword`
Opcode (constructor) `0xa63011e` and bytes (SHA2 password hash with salt).
And we got response: `auth.authorization` or `PASSWORD_HASH_INVALID`.
For more details you can look to source official telegram client to android.
