### ISSUE TITLE
New function: SendBroadcast error: 'UNKNOWN'

### ISSUE THREAD

**Issue by eduardoed5** [sochix/TLSharp#127]
Write this request for the function messages.sendBroadcast.

    public class SendBroadcastRequest : MTProtoRequest
	{
        private List<InputUser> _contacts;
        private string _message;
         InputMedia _inputMedia;

       public Messages_statedMessageConstructor messageOutput;
        public SendBroadcastRequest(List<InputUser> contacts, string message, InputMedia inputMedia)
		{
            _contacts = contacts;
            _message = message;
            _inputMedia = inputMedia;
        }

		public override void OnSend(BinaryWriter writer)
		{
            writer.Write(0x41bb0972);
            writer.Write(0x1cb5c415);  
            writer.Write(_contacts.Count);
            foreach (InputUser id in _contacts)
                id.Write(writer);
            Serializers.String.write(writer, _message);
            _inputMedia.Write(writer);
        }

		public override void OnResponse(BinaryReader reader)
		{
            messageOutput = TL.Parse<Messages_statedMessageConstructor>(reader);
        }

		public override void OnException(Exception exception)
		{
			throw new NotImplementedException();
		}

		public override bool Confirmed => true;
		public override bool Responded { get; }
	}

I have reviewed many times with the API specification and the values ​​are correct , but send me the following error: 'UNKNOWN'

**Comment by eaba** [comment]
Hi @eduardoed5 I am interested in this feature, so let put heads together
The API scheme for SendBroadcast is
`messages.sendBroadcast#41bb0972 contacts:Vector<InputUser> message:string media:InputMedia = messages.StatedMessages;`
I dont get what why `writer.Write(0x1cb5c415);` is there

**Comment by eaba** [comment]
```
public override void OnSend(BinaryWriter writer)
    {
        writer.Write(0x41bb0972);
        //writer.Write(0x1cb5c415);  
        //writer.Write(_contacts.Count);
        foreach (InputUser id in _contacts)
            id.Write(writer);
        _inputMedia.Write(writer);
        Serializers.String.write(writer, _message);
    }

```

**Comment by eaba** [comment]
On further research it may be the sendbroadcast is no more available being replace with channel and 0x41bb0972 is not found in tlsharp constructor

**Comment by eduardoed5** [comment]
Hi.

 I use the API specification for vector object:


vector

A universal vector constructor.

Layer 23 
vector#1cb5c415 {t:Type} # [ t ] = Vector t;
Parameters

For serialization write the constructor id 0x1cb5c415:**int**, then the number of vector elements - #:**int**, then, one after another, the # of the elements of the type t, that was implicitly passed to the constructor

if,  I delete some of the lines that you mention it, I get this error: INPUT_FETCH_ERROR, since I am not specifying the correct values

**Comment by eaba** [comment]
Hi SendBroadcast is no longer supported

**Comment by eduardoed5** [comment]
Ok.thanks.

**Comment by eaba** [comment]
Kindly close this issue
