### ISSUE TITLE
unregisteredNumber and another Numbers

### ISSUE THREAD

**Issue by DavLutsan** [sochix/TLSharp#13]
Hi
can i ask u about these three phone numbers?
what about numberToAuthenticate, registeredNumber and unregisteredNumber?
i set them like this:
    <add key="numberToAuthenticate" value="+95454545  (MyPhoneNumber)" />
    <add key="registeredNumber" value="+95454545 (MyPhoneNumber)" />
    <add key="unregisteredNumber" value="+ (i have no idea about this??)" />

MyPhoneNumber means that number i registered it in Telegram Site for giving API Code.
is that alright?
what about unregisteredNumber?

thanks

**Comment by delphiassistant** [comment]
>MyPhoneNumber means that number i registered it in Telegram Site for giving API Code.
is that alright?

Correct.

>what about unregisteredNumber?

I don't know about this one.

**Comment by sochix** [comment]
It's a number that not registered in telegram

воскресенье, 4 октября 2015 г. пользователь DavLutsan написал:

> Hi
> can i ask u about these three phone numbers?
> what about numberToAuthenticate, registeredNumber and unregisteredNumber?
> i set them like this:
>
>
> MyPhoneNumber means that number i registered it in Telegram Site for
> giving API Code.
> is that alright?
> what about unregisteredNumber?
>
> thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sochix/TLSharp/issues/13>.
>


-- 
Best regards, Ilya (http://sochix.ru)
С уважением, Илья (http://sochix.ru)

**Comment by nezam1** [comment]
HI
Whats unregisteredNumber in app.config file?

**Comment by sochix** [comment]
It's a number which is not registered in Telegram

2015-10-09 14:48 GMT+08:00 nezam1 <notifications@github.com>:

> HI
> Whats unregisteredNumber in app.config file?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sochix/TLSharp/issues/13#issuecomment-146771613>.
>



-- 
Best regards, Ilya (http://sochix.ru)
С уважением, Илья (http://sochix.ru)
