### ISSUE TITLE
Connection waiting

### ISSUE THREAD

**Issue by Vishu24** [sochix/TLSharp#132]
Hi,
I have used below code to connect with telegram, but its stuck at 3rd line. [I had update _apiHash and _apiId in  telegramClient.cs file.]
var store = new FileSessionStore();
var client = new TelegramClient(store, "session");
await client.Connect();

Plz help me. still anything have to change?

**Comment by eaba** [comment]
Remove `await client.Connect();`
try `client.Connect().ConfigureAwait(false);`
and see if it works!

**Comment by Vishu24** [comment]
This solution does not works for me.

**Comment by eaba** [comment]
That is one problem you need to know about async/await it will dead lock if not used properly
Maybe calling it from a UI thread!
You could also put it in its own thread: `Task.Factory.StartNew(async()=> {var result = await client.IsPhoneRegistered("Mobilenumber")})`
This is one of the solution I have ever tried personally

**Comment by Vishu24** [comment]
Thanks for your help, But solution is not working.

**Comment by eaba** [comment]
Hi just experienced same issue?
Where are you call the code?
I solved my issue by moving it to another?
Are you running the code on a console?
