### ISSUE TITLE
telegram api for UWP

### ISSUE THREAD

**Issue by holodnukfedor** [sochix/TLSharp#137]
Не мог бы ты создать реализацию своей библиотеки, как портируемую библиотеку которая поддерживает UWP платформу windows 10, некоторые классы придется заменить, поскольку .Net core win 10, не поддерживает все. Ну тебе, возможно, это легче сделать поскольку ты знаешь, как библиотека работает. Заранее тебе благодарен.

**Comment by sochix** [comment]
Sorry, have no time for it
