### ISSUE TITLE
Group Chat Functions

### ISSUE THREAD

**Issue by delphiassistant** [sochix/TLSharp#14]
Hi
Could you kindly add functions for working with chats?

Or if have'nt enough time, if you guide me I could help to develop and improve your library.
I'm a senior developer with 22 year of software development experience.
If you like my offer, we could talk here or in telegram. I will give you my phone number for telegram chat.

**Comment by sochix** [comment]
Yes, you could contribute. Start from understanding MTProto binary data serialization (https://core.telegram.org/mtproto/serialize). To send data to chat, you simply need to get `chatId` and use existing send method to send data to this `chatId`. Methods to get chatid you should find here https://core.telegram.org/methods#working-with-chats . Than you need to create a new class derived from MtProtoRequest. If you have any problems, ask.

**Comment by POSBean** [comment]
Hi sir,

i got this error how to clear this

Visual Studio 2012
Framework 4.5

public override bool Confirmed => true;

Error	7	; expected	AuthSendCodeRequest.cs	51	34	TLSharp.Core

Please Help me...

**Comment by sochix** [comment]
Update VS to 2015
