### ISSUE TITLE
How fix AUTH_KEY_UNREGISTERED error

### ISSUE THREAD

**Issue by jamesmoriati** [sochix/TLSharp#141]

**Comment by eaba** [comment]
Hi @jamesmoriati please describe how you are calling the api

**Comment by jamesmoriati** [comment]
When adding a contact, I deal AUTH_KEY_UNREGISTERED error.

I use
contacts.importContacts#da30b32d contacts:Vector<InputContact> replace:Bool = contacts.ImportedContacts;

**Comment by eaba** [comment]
Are you following the sample given?
If yes, dont call connect() on all methods,
call connect once and use in other methods.

**Comment by uzwebline** [comment]
You should firstly make an auth request. Then you can send message to contact. 
If you done auth request once then you may send messages without auth.
