### ISSUE TITLE
Как можно получить список диалогов контакта. 

### ISSUE THREAD

**Issue by serafim61** [sochix/TLSharp#143]
Вижу получить переписку по ид контакта. А как сам список контактов(диалогов) Достать.

**Comment by RaaaGEE** [comment]
Для контактов реализовать GetContacts, не забыв обновить структуру. Для текущих диалогов GetDialogs.
Получение контактов можно посмотреть в моем pull request'е: https://github.com/sochix/TLSharp/pull/135/commits/489636f0143284146bd74ce2913a6481005f7921

Получение диалогов уже есть, достаточно обновить структуру Message и ее зависимости: https://github.com/sochix/TLSharp/pull/135/commits/bb0616ef101c03683670bac9ca045d6bfc99ec98
А в клиенте добавить/изменить:
```
        public async Task<messages_Dialogs> GetDialogs(int offset, int limit, int maxId = 0) {
            var req = new GetDialogsRequest(offset, maxId, limit);
            await _sender.Send(req);
            await _sender.Recieve(req);
            return new Messages_dialogsConstructor(req.dialogs, req.messages, req.chats, req.users);
        }
```

**Comment by sochix** [comment]
Check readme
