### ISSUE TITLE
GetHistoryRequest no read file.

### ISSUE THREAD

**Issue by serafim61** [sochix/TLSharp#145]
only message text and photo. Other file .mp3 .* no read(GetHistoryRequest) 
Response=NULL(error)

```
public async Task<List<Message>> GetMessagesHistoryForContact(int user_id, int offset, int limit, int max_id = -1)
        {
            var request = new GetHistoryRequest(new InputPeerContactConstructor(user_id), offset, max_id, limit);
            await _sender.Send(request);
            await _sender.Recieve(request);

            return request.messages;
        }
```

**Comment by RaaaGEE** [comment]
Need to update Message & Document structure. Now stickers, music, files and other message attaches doesnt work.
Look: https://github.com/sochix/TLSharp/issues/139

**Comment by serafim61** [comment]
А можете обновить гит? А то фиг пойми куда это :D

**Comment by RaaaGEE** [comment]
@serafim61 А в чем проблема стянуть мой форк, пока pull request не будет принят?

**Comment by serafim61** [comment]
Наверно потому что я чайник. И не понимаю как обрабатывать вашим "форком"

**Comment by detho** [comment]
how Add Updates handling??

**Comment by pishgaman-org** [comment]
@RaaaGEE could you solve my problem #163?
