### ISSUE TITLE
GetDialogsRequest returns empty lists

### ISSUE THREAD

**Issue by Starli0n** [sochix/TLSharp#149]
Hi,

I try to use the `GetDialogsRequest` function but it returns:

* 0 dialogs
* 0 messages
* 0 chats

I try to get batck the chat_id of a group in order to get the history.

I added `GetDialogsRequest` function in `TelegramClient`

```
        public async Task<List<Dialog>> GetDialogsRequest(int offset, int limit, int max_id = -1)
        {
            var request = new GetDialogsRequest(offset, max_id, limit);
            await _sender.Send(request);
            await _sender.Recieve(request);

            return request.dialogs;
        }
```

And I call it like that:

```
                var store = new FileSessionStore();
                var client = new TelegramClient(store, "session", apiId, apiHash);
                await client.Connect();
                var dial = await client.GetDialogsRequest(0, 5);
```

Could you please help me?

**Comment by chusothe41** [comment]
I'm busy right now I'll check it later

**Comment by mizbani** [comment]
hi , i have same problem ... please help me !

**Comment by woakesd** [comment]
Did some further testing, I made the following call:

`client.GetDialogs(0, -1, 0)`

Stepping through in Debug mode I get a ZlibException thrown with the message "Bad CRC32 in GZIP trailer. (actual(E8668E15)!=expected(7F1FA9BA))" in MtProtoSender at line 305.

The exception is caught here and nothing done with it.

Calling GetDialogs without the third parameter (where it defaults to -1) results in a much shorter response which isn't compressed and doesn't hit this issue (the result is correctly decoded without issue).

I think there is an issue as I get quite a few exceptions caught at the same place from calling Connect also.
