### ISSUE TITLE
IsPhoneRegistered

### ISSUE THREAD

**Issue by Frank213** [sochix/TLSharp#152]
У вас написано что для проверки не нужна авторизация, да и в примерах у вас она отсутствует. У меня почему - то проверка не проходит до отправки смс кода.
```
public static async Task CheckPhones()
        {
            var store = new FileSessionStore();
            var client = new TelegramClient(store, "session", 11111, "xxx");
            await client.Connect();
            var phone = "79111111111";
            //await client.SendCodeRequest(phone);
            var res = await client.IsPhoneRegistered(phone);
            MessageBox.Show(res.ToString());
        }
```
Этот код не работает пока не раскоментить строку с отправкой кода. В чем моя ошибка? Вызываю так `Task.Run((Func<Task>)Form1.CheckPhones).Wait();`

**Comment by Arei15** [comment]
@sochix Как думаете, это ошибка протокола или в библиотеки? Т.к у меня тоже не работает проверка телефонов.

**Comment by sochix** [comment]
library updated
