### ISSUE TITLE
TelegramClient.SendCodeRequest(string) not working after some successful attempts.

### ISSUE THREAD

**Issue by atoipowered** [sochix/TLSharp#153]
`TelegramClient.SendCodeRequest(string)` doesn't work after about 10 or 20 successful attempts; no change made to the code at all. Is there any restriction made by Telegram or is this a bug?

**Comment by eaba** [comment]
If the number is on telegram, you wont get the code on your phone but rather on the official telegram!
You can force the code to to be sent as sms.
look at this method `SendCodeToSms` in #136
