### ISSUE TITLE
How improve TLSharp to work with channels?

### ISSUE THREAD

**Issue by GoldenLighter** [sochix/TLSharp#158]
Hi dear members,

**1-**
My question is why TLSharp does n't support channels?  

**2-**
How can i improve TLSharp to work with channels?

Please take a look at this link :  
[Why improve webogram to work with channels?](https://github.com/sochix/TLSharp/issues/70#issuecomment-176725343)
As this link says TLSharp was wrote to work with Layer 23 and this layer is very old and does n't have channel parts.
Now i want to improve TLSharp to work with channels base on this scheme(Layer 51):  
[Scheme - Layer 51](https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/mtproto/scheme.tl)

**3-**
What is the easiest way to add channel parts to TLSharp?   

**4-**
Which files should i change?  
For example can u show us how can we add createChannel part? (I choosed it because tags area are not familiar for me)

Thanks in advance

**Comment by chusothe41** [comment]
I can't see the links m8

**Comment by GoldenLighter** [comment]
I update them...

**Comment by sadeghiPH** [comment]
Hi dear @GoldenLighter 
can you help me 
how did you do it

**Comment by keyvanarasteh** [comment]
@sadeghiPH you have to write TL.cs for layer 51 or 52 or later than 23

and change Requests in Requests folder and layer to 51 or 53 or ... in InitConnectionRequest ;-) 

Good luck.

**Comment by GoldenLighter** [comment]
@sadeghiPH 
I saw your profile and you are new here.
Complete your registration and put an email address there.
We will contact you.

**Comment by GoldenLighter** [comment]
Finally i changed the entire software and works very well with new layers...
If you are interested put your email address here.

**Comment by eaba** [comment]
questswa@gmail.com

**Comment by keyvanarasteh** [comment]
@GoldenLighter send to me too, i'll compare yours with mine ;-) tnx keyvan.arasteh@gmail.com

**Comment by sadeghiPH** [comment]
hi
my email's
sadeghi92515@gmail.com
and thanks for your guidance

**Comment by keyvanarasteh** [comment]
@sadeghiPH , @eaba 
as @GoldenLighter said, but he hasn't it :|
i talked with he even dont know about API Layers :|
he told me he is in layer 131 :| (Latest layer : 52 (telegram official apps current layer))

**Comment by eaba** [comment]
@keyvanarasteh cant you be generous?

**Comment by keyvanarasteh** [comment]
@eaba i'm sry, it's about 9 month i'm working on telegram, it's my 9 month experience :-1: 

i cant :1234:

**Comment by eaba** [comment]
talk to me on telegram

**Comment by GoldenLighter** [comment]
Hi every body,
Here is the web site of @keyvanarasteh 
http://46.4.159.238/UserLogin.aspx
As you see this web site is fake and every link in this fake web site doesn't work.
This is why i told him i am working on layer 132, because you should be honest during talk.
My telegram api (latest layer) is ok and works very well.
I asked @keyvanarasteh to send me a message from that fake web site.
But he blocked me in telegram.
He even do n't know what is he doing and what layer is!  
For example in his codes you will see a hash variable and this is fake too.
So ignore this cheater guy.
I am so sorry to see such these people around here.

**Comment by GoldenLighter** [comment]
He does n't know what layer should work and his logic about flags is incorrect.
If you are looking for a workable & new codes : 
1-Should be honest
2-Don't forget about donation
3-Just Contact

**Comment by GoldenLighter** [comment]
You made this thread and asked some questions.
So how could you improve codes?   
We are here to find active people in our area and find best classes for the job and share it with pro (not dopey) people.
So feel free for the contact and we will guide you to the right direction.

**Comment by keyvanarasteh** [comment]
@GoldenLighter 
1. about http://46.4.159.238/UserLogin.aspx
untill you dont have username or password you cant use my portal & as i said before it's not working anymore. (site works but bulk messages is not working)

2. about hash variable 

its code for this Type in TL class : 

authorization#7bf2e6f6
hash:long flags:int device_model:string platform:string system_version:string api_id:int app_name:string app_version:string date_created:int date_active:int ip:string country:string region:string = Authorization;

as you see "hash" is first parameter of "authorization" type.
and you can see in tdesktop official scheme 
(this link : https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/mtproto/scheme.tl)
at line 529 (or search 7bf2e6f6 to find that)

i aproved my TLSharp with layer 52 , what you have to aprove your code ??
talking is'nt enough, you need code my friend. i hope you'll improve your coding and your TLSharp.

**Comment by GoldenLighter** [comment]
One function in  **scheme.tl** or some have hash parameter at start and you used it for all functions.
This is enough for us about your codes and in this way will failed always.
If you want some help follow the rules upper and don't forget always be polite.
till that time go and play with your numbers.

**Comment by keyvanarasteh** [comment]
it's just for 1 type !!! (authorization#7bf2e6f6)

all types in TL.cs class has 22557 line !!!!

screenshot : 

![sctg3](https://cloud.githubusercontent.com/assets/16303698/15838409/25bf6954-2c53-11e6-9ae1-21a822e83c6f.png)

**Comment by GoldenLighter** [comment]
Have some fun & laugh,
Here is the picture of "کیوان آراسته" : 
![photo_2016-06-11_11-34-07](https://cloud.githubusercontent.com/assets/18400766/15983883/166caa04-2fcb-11e6-957d-3203272bb08a.jpg)

Certainly sure invalid first & last name.
He sent me this email several times : 
MacRumors <arn@normalkid.com>
"
Hi,
MacRumors is hosting a small mixer for media, developers and MacRumors readers at WWDC. As a regular forum member, we're offering you a possible spot on the invite list.
If you are going to be in San Francisco on Wed, June 15th from 6pm-9pm, and are interested in attending, please reply to this email with your full name and email address.
Space is very limited, so please only reply if seriously interested. We can't guarantee a spot, and will be in touch in the next couple of days.
MacRumors editors Eric Slivka and Juli Clover will also be in attendance.
Hope to see you there,
arn
"
What is this mail?  
Who are you really?   
This is not a place for sociologists half-men people.
Anagram? 
Seriously?
What should i say?

**Comment by DrEhsan** [comment]
@GoldenLighter chera axe mardomo mizarin inja?
hatman baiad hame ja ro be gand bekeshin
vagean aberuye harchi iran va iranie rafte
ye github monde bod ke fosho na seza nadide budim ke didim

**Comment by GoldenLighter** [comment]
Shoma khale khanoomi?

**Comment by DrEhsan** [comment]
@GoldenLighter man kari be kare un yeki dostemon nadaram. ama az tarz harf zadane shoma ham kamelan moshakhase ke che shakhsiati darin.

**Comment by GoldenLighter** [comment]
Be ghole goftani Sepasgozaram....

**Comment by keyvanarasteh** [comment]
@GoldenLighter ellate in k in kararo mikoni kamelan moshakhase :| martikeye avazi :|

man esm o rasmam hamechim moshakhase toyi k ye nashenasi, kari nakon aziatet konam :|

**Comment by GoldenLighter** [comment]
Doose aziz,
Shoma copy right ro raayat nemikoni va mafhoome donate bara shoma mese inke maskhare bazi has.
Bara ye web site latin e barnamenevisi che niazi be esmo rasm has va man lozoomi nemibinam bish az had khodamo moarefi konam.
Man fohsh hayi ke behem dadi mibakhsham chon mahe mobarake ramezan has.
Say kon be onvane ye developer avval be license ehteram bezari.
Dar sani man nemoone karam marboot be daroon sazmani va intranet boode.
Dar nahayat age man bi ehterami kardam ozr khasam, ama shoma be jash sange tamoom gozashi va man dar shaane khod nemininam ke ingoone barkhord konam.
Bia mese mard babate dastanayi ke sare man piade kardi ozr bekhah va payam haye in thread to pak kon va man mibakhsham va hame chio az inja pak mikonam va shoma ro be kheyro maro be salamat.

Good Bye
