### ISSUE TITLE
problem with breakpoint

### ISSUE THREAD

**Issue by eslamih10** [sochix/TLSharp#16]
When I run the program, I have received a code from telegram, but the program does not reach the breakpoint and performances continues! Please help

**Comment by delphiassistant** [comment]
Hi.
Right Click on Test Project and choose debug tests.


با احترام،
کرامتی.

2015-10-07 0:11 GMT+03:30 Hossein Eslami <notifications@github.com>:

**Comment by sochix** [comment]
Google it! It's not the best place to ask questions like this.

**Comment by eslamih10** [comment]
Mr keramati,Thank you very much
