### ISSUE TITLE
client.connect() exception

### ISSUE THREAD

**Issue by sadra74** [sochix/TLSharp#164]
Hello
my code ran but when it reach to client.connect() it throw 'System.Reflection.TargetInvocationException' in mscorlib.dll

the program also throw these exceptions:
Exception thrown: 'System.IO.FileNotFoundException' in TLSharp.Core.dll
Exception thrown: 'System.IO.FileNotFoundException' in mscorlib.dll
Exception thrown: 'System.IO.FileNotFoundException' in mscorlib.dll
Exception thrown: 'System.IO.FileNotFoundException' in mscorlib.dll
Exception thrown: 'System.IO.FileNotFoundException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in TLSharp.Core.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
I am working on it for 2 weeks and it still doesnt work i think the problem is not in my system

**Comment by yura399743993** [comment]
Hi, how you create your connection?
My code work great 
var Store = new FileSessionStore();
var Client = new TelegramClient(Store, "session", apiId, apiHash);
Client.Connect();
But i use constructor with 4 params.

**Comment by sadra74** [comment]
private async void Send_Message_By_Telegram(string Message)
        {
            var store = new FakeSessionStore();
            var client = new TelegramClient(store, "session", *****, "************************");

            
            await client.Connect();
            

            var hash = await client.SendCodeRequest("***");
            var code = "1234";
            var user = await client.MakeAuth("*****", hash, code);
            var userByPhoneId = await client.ImportContactByPhoneNumber("*****"); //import by phone
            await client.SendMessage(1, "hello");
        }
my code is like this

**Comment by sochix** [comment]
lib updated
