### ISSUE TITLE
i've wrote Layer 52 TL and TLSharp

### ISSUE THREAD

**Issue by keyvanarasteh** [sochix/TLSharp#165]
if anybody wants TLSharp with Layer 52 Telegram API, 

contact me : 
telegram username : keyvan_ar

**Comment by eaba** [comment]
@keyvanarasteh why dont you send a pull request?

**Comment by keyvanarasteh** [comment]
@eaba  because i'm working for 4 month on it, it supports all of available requests, types , ...

it's for my personal use on my automated softwares , sry eaba :-1:  i cant share it for free
