### ISSUE TITLE
Channels, Chats, ... = FullSupport

### ISSUE THREAD

**Issue by keyvanarasteh** [sochix/TLSharp#168]
if anybody wants API with latest layer and all methods support, contact me.

> telegram : @keyvan_ar

> email : keyvan.arasteh@gmail.com

About API :

> Auth :

API Supports Normal Accounts , Accounts with Two-Step-Verification & more

> Requests :

API supports 169 request (including Channels, Groups, Chats, Users, Help, Updates, ...

> Types : 

API support all Types defined in latest layer of telegram

`you can do all requests available for official telegram clients with API.`

`using API is simple, and methods return all of vars returned by telegram server.`

`best regards. Keyvan`

**Comment by XyLoNaMiyX** [comment]
Well sure they can do pretty much the same with my https://github.com/LonamiWebs/TLSharp.CodeGenerator ...

**Comment by angola3000** [comment]
Hi @XyLoNaMiyX , is that your project "TLSharp.CodeGenerator" closed?

**Comment by XyLoNaMiyX** [comment]
Yes @angola3000, I closed the project because I only found people asking me to solve their problems. More likely, the code generated by it didn't probably match TLSharp without some (many) fixes.

**Comment by angola3000** [comment]
@XyLoNaMiyX  What a pity...
Do you have any recommendation if i would like to implement the latest schema ?
I saw your pull request but seems could not combine with master branch...

**Comment by XyLoNaMiyX** [comment]
If you want to implement the latest schema, you're better off by:
 1. Learning how TLSharp works, and how the requests classes are made.
 2. Looking at the [latest scheme](https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/mtproto/scheme.tl) and understanding how it is made (you may want to look at the [official documentation](https://core.telegram.org/mtproto/TL), but honestly learning by trial and error sounds better to me!).
 3. Designing a "parser" or "code generator" in the language you prefer. I used C#, but you could also use Python, Java, or any other, in such a way that it takes `.tl` files and generates C# code ready for TLSharp.

Then it would be matter of using the generated code in TLSharp. If you would like to have a look at the code generator, don't doubt on [asking me](http://telegram.me/Lonami). But it would probably work better if you made your own generator, though you could use the tokenizer (...and improve it). Also, thanks for your interest :)

**Comment by XyLoNaMiyX** [comment]
@angola3000 if you're interested I'm writing (trying to) [TLSharp in Python](https://github.com/LonamiWebs/Telethon). There it should be easier because Python is duck typing, so no need for so many abstract classes. I'm looking forward to it, so just letting you know!

**Comment by angola3000** [comment]
@XyLoNaMiyX Thanks! Though I had less experience in Python before... but will certainly have a look at Telethon

**Comment by XyLoNaMiyX** [comment]
@angola3000 My experience with Python is barely comparable to the one I have with C#. However, it's really, _really_ easy to learn Python! Just read the code, and you'll get a good grasp of it. I personally read [Dive into Python 3](http://getpython3.com/diveintopython3/index.html), amazing book!

Yet, I hope @sochix does have a look at it too, and perhaps combine both improvements, so people can both enjoy a simple C# and Python Telegram API.

**Comment by sochix** [comment]
library updated. Channel supported
