### ISSUE TITLE
please make a simple windows form applicatiion for send messege

### ISSUE THREAD

**Issue by assassinsajjad** [sochix/TLSharp#169]
Hi...
I could not work with TLsharp...
please make Form for send messege to one person...
Thank you

**Comment by keyvanarasteh** [comment]
@assassinsajjad : 
1. you have to authenticate your line and create Session (Auth-Key).
2. after that you're able to send messages.
3. it's simple (follow below : )

> * - Import TLSharp.Core as Refrence to your project

> * - then :

`var client = new TelegramClient(store, "session", API_ID, "API_HASH");
await client.Connect();`

> * - then : 

`var hash = await client.SendCodeRequest(phoneNumber);

    var code = "1234"; //code that you receive from Telegram 

    var user = await client.MakeAuth(phoneNumber, hash, code); `

>* - then Import Contact : 

first option (add with phone number) 

`var res = await client.ImportContactByPhoneNumber("791812312323");`

second option (import with username)

`var res = await client.ImportByUserName(userName);`

> * - send message

`await client.SendMessage(userId, message);`

**Comment by assassinsajjad** [comment]
please  make a form application with visual studio for send messege ....
i can not use this ....
thankyou

**Comment by DrEhsan** [comment]
@assassinsajjad then do not try to work around it

**Comment by assassinsajjad** [comment]
i want only a form application for send message ... no more

**Comment by keyvanarasteh** [comment]
@assassinsajjad :| :| first get info about telegram and then ask this wrong questions :| :|

**Comment by assassinsajjad** [comment]
حرف نزن بابا


2016-06-16 13:47 GMT+04:30 Keyvan Arasteh <notifications@github.com>:

**Comment by keyvanarasteh** [comment]
@assassinsajjad anche k aayan ast che hajat b bayan ast.

i hope you'll get your code :)))))) as soon as possible my friend :100: %
