### ISSUE TITLE
IsPhoneRegistered exception

### ISSUE THREAD

**Issue by kotki** [sochix/TLSharp#170]
Hi,i'm trying to use your code? but i'm getting an error at IsPhoneRegisteredFunction
could you please suggest what could be wrong?
![image](https://cloud.githubusercontent.com/assets/18561521/15987183/7bf7c04a-3028-11e6-8aca-51b638e78444.png)

Thanks for help!

**Comment by DrEhsan** [comment]
@kotki your account has registered in dc2 ip , so you have to change your server Address.
I think the dc2 must be : 149.154.167.50:443

**Comment by kotki** [comment]
well, i tried all 7 ip's from here https://github.com/sochix/TLSharp/issues/48 ,
but it did not work, maybe I did something wrong?I opened a projectфтв  in class Sessiona changed  defaultConnectionAddress field. May be something else?
Thanks for help!

**Comment by keyvanarasteh** [comment]
@kotki  dc is diffrent for each country.

we have about 5 or 6 dc and for example :
+98 works with dc number 4
+20 works with dc number 4
and ....

you can connect to server with server ip described in my.telegram.org

and then you can get nearest dc with a request in telegram api with same name (GetNearestDC) 

i hope this solves your problem.

good luck.

**Comment by oldnavy1989** [comment]
@DrEhsan Where is server Address, which I have to change?

**Comment by oldnavy1989** [comment]
I've found defaultConnectionAddress field in Session class.

**Comment by keyvanarasteh** [comment]
@oldnavy1989 : you have to change that by your default Server address, described in my.telegram.org

**Comment by sochix** [comment]
library updated
