### ISSUE TITLE
CreateChatRequest and AddChatUserRequest

### ISSUE THREAD

**Issue by mhrghorbani67** [sochix/TLSharp#172]
hi,i want implementation createchatrequest and addchatuserrequest class in tlsharp,
please help me

**Comment by mhrghorbani67** [comment]
hi,i could implement createchatuserrequest,but my problem is that i have code below:

NumberToSendMessage = "989122222222";
var res = await client.ImportContactByPhoneNumber(NumberToSendMessage);
InputUserContactConstructor input = new InputUserContactConstructor();
input.user_id = res.Value;
id.Add(input);
Messages_statedMessageConstructor chatid = await client.CreateChat(id, "test chat"); 

and CreateChat method is in TelegramClient:

public async Task<Messages_statedMessageConstructor> CreateChat(List<InputUserContactConstructor> id, string title)
        {            
            var request = new CreateChatRequest(id, title);
            await _sender.Send(request);
            await _sender.Recieve(request);
            
            return request.message;            
         }      

i want after call Create method add user to this chat or send message to this group,for this work i need "chatid",but i don't access to chat id
my question is that how i get "chatid" after create chat?
message param is null,where did chat id?
please help me

**Comment by steavy29** [comment]
Hey. You could have a look at my pull request here https://github.com/sochix/TLSharp/pull/198 I added implementation of chat creation.

**Comment by sochix** [comment]
library updated
