### ISSUE TITLE
access chatid

### ISSUE THREAD

**Issue by mhrghorbani67** [sochix/TLSharp#173]
hi
i want after createchat,add user to this chat(group),
i need to "chatid"
how did access to chatid?
please help me

**Comment by keyvanarasteh** [comment]
@mhrghorbani67 

chat id is in response you got from CreateChat or JoinChat Request.

;-) just trace your response method in above requests you'll find out where it is ;-)

**Comment by mhrghorbani67** [comment]
chat_id is in message in Message_Stated,but message is null
so i don't access to chat_id
please help me

**Comment by sochix** [comment]
check readme
