### ISSUE TITLE
How can i send message without import contacts?

### ISSUE THREAD

**Issue by m6amiri** [sochix/TLSharp#18]

**Comment by sochix** [comment]
You should know a PeerId, and a refactor a TLSharp a bit to be able to do it.

**Comment by m6amiri** [comment]
How can i get  peerID? and How it produced?

**Comment by sochix** [comment]
Search here https://core.telegram.org/api/

**Comment by nezam1** [comment]
What method in TlSharp send message to foreign peer in https://core.telegram.org/constructor/userForeign
