### ISSUE TITLE
Getting dialog name and ID for sending messages

### ISSUE THREAD

**Issue by TaylerNest** [sochix/TLSharp#182]
Hello!
I've noticed that there is terrible support for group chats. There is no (or i didn't find) any method to identify or interact with chats. For example, i can't find chat by name because there is no support for name getting, and GetDialogs() returns me list of elements with weird types that has only default methods and binary read/write streams which i don't know how to use.
At all, there is NOTHING except getting ID by username and phone, and sending messages by userID. I don't know how this lib can be helpful to anyone.

**Comment by keyvanarasteh** [comment]
@TaylerNest 

when you recieving updates or dialogs you get "chats","dialogs","users"

each one of above Vector (List) contains all data about 

- chat title
- users status
- ....

i suggest to upgrade to layer 53 ;-) 
good luck

**Comment by sochix** [comment]
check readme
