### ISSUE TITLE
How to get all Contacts list that already exist in my account? (User ID and other info)

### ISSUE THREAD

**Issue by EbiPenMan** [sochix/TLSharp#183]
Hi
I want to sent message by (phone number or user name) that this contact has already exist in my contact list.
I used this code:
` var res = await client.ImportContactByPhoneNumber("5454545454");
            await client.SendMessage((int)res, "Hello from TLSharp!");`
but rename this contact. 
I dont want to rename my contact name.

How get contact id from phone number or user name?
`client.GetContactByPhoneNumber
client.GetContactByUserName`

**Comment by Di-Roll** [comment]
Try this:
```
var contacts = await _client.GetContacts();

foreach (var contact1 in contacts)
{
 var contact = (ContactConstructor) contact1;
}
```

**Comment by sochix** [comment]
check readme
