### ISSUE TITLE
Ошибки в GetMessagesHistoryForContact & GetDialogs

### ISSUE THREAD

**Issue by AntonGG** [sochix/TLSharp#184]
Не работают эти функции,
GetDialogs - {"invalid constructor code E26F42F1"}
GetMessagesHistoryForContact  - {"PEER_ID_INVALID"}

**Comment by AntonGG** [comment]
Если я получаю id  с помощью телефона пользователя то могу отправить сообщения и прочесть его, а если я получаю с помощью имени то выдает ошибку {"PEER_ID_INVALID"}.
Моя задача получать сообщения от канала, кто занимался - подскажите.

**Comment by AntonGG** [comment]
Еще невозможно получить диалоги из-за того что не может получить статусы

**Comment by melvinsalas** [comment]
Some solution?

**Comment by sochix** [comment]
library updated
