### ISSUE TITLE
Layer changes after reconnect

### ISSUE THREAD

**Issue by pishgaman-org** [sochix/TLSharp#187]
hi

in **SendCodeRequest** function if "_Your phone number registered to_" error occurs, **ReconnectToDc** calls.
after it, Connection Layer changes and calling other methods makes error.

to solve it, I tried comment **if (!reconnect)** line in **Connect** function and calling other methods makes no error.
but after restarting my program and loading saved session, Connect function throw "_Unable to read beyond the end of stream_" error.

what is the solution?

**Comment by steavy29** [comment]
Does it change to higher or lower layer level?

**Comment by pishgaman-org** [comment]
lower.

**Comment by steavy29** [comment]
Hey. I've fixed this issue in my [fork](https://github.com/steavy29/Telegram.Net). You can check it out.

**Comment by pishgaman-org** [comment]
Thank you. I'll test it.

**Comment by sochix** [comment]
library updated
