### ISSUE TITLE
Couldn't read the packet length

### ISSUE THREAD

**Issue by schlumpf90** [sochix/TLSharp#188]
Hi to all,

I have the same problem what is already discussed and described: (https://github.com/sochix/TLSharp/issues/44)  : "couldn't read the packet length"

From the first use of my application, I can register my phone account. After this I can send one message successfully from my application. But from the second message I get this error.
I'm using the telegram server 149.154.167.50 I changed it to several other ip adresses, but the result was the same error.

Then I tried the solution from "ra0o0f" from x-mas 2015 (from issue #44 ), but then I get an arithmetic error at "var body = new byte[packetLength - 12];"

So I think, that the length of the received packet is less than 4 bytes.

Does anyone solved this problem or can help me please !?!?!?

Thanx and best wishes,
Matthias

**Comment by schlumpf90** [comment]
Hi to all,

no one an idea ???

I've made some wireshark protocols -> see attached.
Hope this helps ... !!!
![2016-08-30_145023](https://cloud.githubusercontent.com/assets/20926828/18089691/7a725e60-6ec1-11e6-9776-2e6aabc3fa64.png)

**Comment by steavy29** [comment]
Where exactly does it crash in code? Did you debug?

**Comment by schlumpf90** [comment]
It crashes in the "TCPTransport.cs", exactly here:

public async Task<TcpMessage> Receieve()
        {

            var stream = _tcpClient.GetStream();
            
            var packetLengthBytes = new byte[4];

            **_if (await stream.ReadAsync(packetLengthBytes, 0, 4) != 4)
                throw new InvalidOperationException("Couldn't read the packet length");_**
            int packetLength = BitConverter.ToInt32(packetLengthBytes, 0);

**Comment by steavy29** [comment]
Can you show your code how you send messages? Maybe some unit test that reproduces the situation?

**Comment by schlumpf90** [comment]
Hi !

This is how I send the massages from my application.
Hope this helps you. Otherwise I could send you the whole Visual Studio solution...


private async void btnSend_Click(object sender, EventArgs e)
        {
            var store = new FileSessionStore();

            try
            {
                // Get some data from the settings file
		var MyIni = new IniFile("Settings.ini");
                var hash = MyIni.Read("hash", "Settings");
                var code = MyIni.Read("code","Settings");
                var Telefon = MyIni.Read("Telefon", "Settings");
                var _ConnectionAddress = MyIni.Read("ConnectionAddress", "Settings");
                var _ConnectionPort = Convert.ToInt32 (MyIni.Read("ConnectionPort", "Settings"));

                // Now make the connection and send the data
		var client = new TelegramClient(store, "session", 33685, "e019ae584301e4b2e2de89aac7b61b44", _ConnectionAddress , _ConnectionPort );
                await client.Connect();

                var user = await client.MakeAuth(Telefon, hash, code);

                var userId = await client.ImportContactByPhoneNumber(txtTo.Text);

                await client.SendMessage(Convert.ToInt32(userId), txtMessage.Text);
                
            }

            catch (Exception ex)
            {
                MessageBox.Show(ex.Message , "Error", MessageBoxButtons.OK);
            }

            txtTo.Text = "";
            txtMessage.Text = "";
            txtFile.Text = "";
        }

**Comment by steavy29** [comment]
It seems that you recreate telegram client for each message that you`re trying to send and reauthenticate. I suggest you refactor your authentication and to some static context and in your button click just sending the message. I just tested the following code and it worked well:
`        [TestMethod]
        public async Task SendMessage()
        {
            var store = new FileSessionStore();
            var client = new TelegramClient(store, "session", apiId, apiHash);
            await client.Connect();

            if (!client.IsUserAuthorized())
            {
                var hash = await client.SendCodeRequest(NumberToAuthenticate);

                var code = ""; // you can change code in debugger
                Debugger.Break();

                await client.MakeAuth(NumberToAuthenticate, hash, code);
            }

            Assert.IsTrue(client.IsUserAuthorized());

            var userId = await client.ImportContactByPhoneNumber(NumberToSendMessage);

            await client.SendMessage(userId.Value, "Ahoy!");
            await client.SendMessage(userId.Value, "Ahoy!");
            await client.SendMessage(userId.Value, "Ahoy!");
            await client.SendMessage(userId.Value, "Ahoy!");
        }`

**Comment by schlumpf90** [comment]
I've changed my application to the following code:

`private async void btnSend_Click(object sender, EventArgs e)
{
var store = new FileSessionStore();

        try
        {
            // Get some data from the settings file
    var MyIni = new IniFile("Settings.ini");
            var hash = MyIni.Read("hash", "Settings");
            var code = MyIni.Read("code","Settings");
            var Telefon = MyIni.Read("Telefon", "Settings");
            var _ConnectionAddress = MyIni.Read("ConnectionAddress", "Settings");
            var _ConnectionPort = Convert.ToInt32 (MyIni.Read("ConnectionPort", "Settings"));

            // Now make the connection and send the data
    var client = new TelegramClient(store, "session", 33685, "e019ae584301e4b2e2de89aac7b61b44", _ConnectionAddress , _ConnectionPort );
            await client.Connect();

            var user = await client.MakeAuth(Telefon, hash, code);

            var userId = await client.ImportContactByPhoneNumber(txtTo.Text);

            await client.SendMessage(Convert.ToInt32(userId), txtMessage.Text);
            await client.SendMessage(Convert.ToInt32(userId), txtMessage.Text);
            await client.SendMessage(Convert.ToInt32(userId), txtMessage.Text);
            await client.SendMessage(Convert.ToInt32(userId), txtMessage.Text);
            await client.SendMessage(Convert.ToInt32(userId), txtMessage.Text);

        }

        catch (Exception ex)
        {
            MessageBox.Show(ex.Message , "Error", MessageBoxButtons.OK);
        }

        txtTo.Text = "";
        txtMessage.Text = "";
        txtFile.Text = "";
    }
`

This works fine, the message text was send 5 times.
Then I closed my application and run it again. 
Then I become the error "Couldn't read the packet length".
It's not a new phone authentification !!!

Have I to close the session before I close my application (e.g. await client.close();) ???

**Comment by steavy29** [comment]
When you run it for the second time, when it crashes? While connecting/authenticating/retriving contact or sending message?

**Comment by schlumpf90** [comment]
I always thought that the crash happend at sending a message, but I make some testings for the answer to your question and the crash happend at:

var user = await client.MakeAuth(Telefon, hash, code);

This is my test scenario:

- start my application
- register my application to my phone number -> the file "session.dat" was created and I also store the following things in my file "settings.ini" : hash-code, my phone number, authentification code
- close my application
- start my application and read the stored settings from the file "settings.ini"
- send a message successfully over my application
- close my application
- start my application again
- try to send a message and then it crashes at the command "var user = await client.MakeAuth(Telefon, hash, code);"

**Comment by steavy29** [comment]
Looks strange. From this scenario I think the problem is not in TLSharp but somewhere in your code and how you use it. Try different combinations and see how it will behave. F.e. remove message sending and see if the problem still reproduces. Try narrowing your actions to minimum and see when crash disappears. Also try the same scenario but without your own `settings.ini`.

**Comment by schlumpf90** [comment]
OK, I'll build an application without my "settings.ini". But then I've another question:

At the first start of my new application I have to authenticate my phone number and store this data (hash code, authentification code and so on) in the file "session.dat".

But what if I close the application and start it again ?
Do I have to use the "session.dat" from this first app run ? If yes : how to do it ?
Or do I have to authenticate my phone number again (every time I start my app) ?

**Comment by steavy29** [comment]
You can reuse `session.dat` - it loads automatically. See `Session.TryLoadOrCreateNew` method in TLSharp and it's usages.

**Comment by schlumpf90** [comment]
But I have to do:

"var user = await client.MakeAuth(phoneNumber, hash, code);"

before I can send a message.
How do I get the hash-code and authentification-code from the "session.dat" for this ?

Or do I have to:

if (client.IsUserAuthorized())
{
...
}

**Comment by steavy29** [comment]
Code and it's hash are stored in `session.dat` once you authenticate once. Then they are taken from there. Yes, you can use `if (client.IsUserAuthorized())`

**Comment by schlumpf90** [comment]
I know now where there failure is:

In my application I made the authentication in two steps, because of the missing auth code from telegram.
Now I changed it to one step and it works...

Thanks a lot for your help !!!

**Comment by steavy29** [comment]
Glad to hear it worked. You're welcome.
