### ISSUE TITLE
TLSharp's Python implementation

### ISSUE THREAD

**Issue by XyLoNaMiyX** [sochix/TLSharp#197]
I'd like to comment with you, @sochix, what do you think of [this Python 3 implementation](https://github.com/LonamiWebs/Telethon). It's basically TLSharp's latest version, but with some interesting features:
- Handles updates, and allows you to add event listeners.
- More error codes have been implemented.
- It's written using the latest Python version, **Python 3**, with high readability as its goal.
- **Uses the latest [scheme](https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/mtproto/scheme.tl).**
- Includes a code generator/parser (`.tl` → `.py`) for being able to use the latest scheme always.

Since it's also licensed under MIT, you're free to have a look and copy them back to TLSharp! I was only happy with this, so I wanted to let you know that I've patched some things (at least, on my Python implementation; I'm not fully aware if there are the same errors on original the TLSharp, but I remember I had some similar ones). And to end this message, thank you a lot!

**Comment by sochix** [comment]
No ads here, please

**Comment by XyLoNaMiyX** [comment]
It wasn't quite an ad, and since you blocked me on Telegram, I could not say it anywhere else. It's a port of _your_ work and I wanted to let you know. I have implemented more things which _you_ may be interested to, so I just wanted you to have a look and your opinion. But, if you feel this like an ad, then yes you're free to ignore it.
