### ISSUE TITLE
dll not found

### ISSUE THREAD

**Issue by hami71sami** [sochix/TLSharp#2]
hi 
very thanks for this app .i`m used it but when compile show error tlcore.dll not found 
please help me

**Comment by hami71sami** [comment]
please say me for use this app i should add this library to another app ?

**Comment by sochix** [comment]
It's strange, try to run InitConnection test

**Comment by starbug1** [comment]
hi. metadata file ..\..\TLSharp.Core.dll could not be found. i just opened the .sln file through vs 2013 and when try to build it this error occured.

**Comment by sochix** [comment]
Try to open it in VS 2015, i have no ideas why it's not working

**Comment by starbug1** [comment]
excuse me. because i am amateur in VS 15, can i ask say me how to open it in VS 15. I now created a windows form application. now what i must do to add this library to my windows form application. please say it step by step. Thank you.

**Comment by sochix** [comment]
Sorry, I can't do it for you. Ask another guys or just google it.
