### ISSUE TITLE
DoAuthentication step 2 on Xamarin Studio

### ISSUE THREAD

**Issue by daniel1984tp** [sochix/TLSharp#20]
Hi boys,
i'm trying to use TLSharp on Xamarin studio, but code crash calling client.Connect()... on step 2 of DoAuthentication Task. 
System return this error code on step 2 of DoAuthentication task:
System.IO.EndOfStreamException: Failed to read past end of stream.
Have an ideas? 
Thank you so much!!

**Comment by sochix** [comment]
Did you follow a tutorial?

**Comment by daniel1984tp** [comment]
Yes i did, do you have any idea? Why doesn't work? 
I update App api_id and App api_hash but the second step of DoAuthentication return 0 bytes.

**Comment by sochix** [comment]
Did you try running tests?
