### ISSUE TITLE
telegram server appearing to be blocking me [ programm freezes on client.connect() ] 

### ISSUE THREAD

**Issue by madadoux** [sochix/TLSharp#200]
now i sent request code 7 times in raw by mistake and the server appearing to blocking me [the programm freezed] so what i can do now to unblock my self ? thanks in advance

     
madadoux commented an hour ago
    public async Task<bool> Connect(bool reconnect = false)
    {
        if (_session.AuthKey == null || reconnect)
        {
            var result = await Authenticator.DoAuthentication(_transport);
            _session.AuthKey = result.AuthKey;
            _session.TimeOffset = result.TimeOffset;
        }

        _sender = new MtProtoSender(_transport, _session);

        if (!reconnect)
        {
            var request = new InitConnectionRequest(_apiId);

            await _sender.Send(request);
            await _sender.Receive(request); // here freezes  using debugger 

            dcOptions = request.ConfigConstructor.dc_options;
        }

        return true;
    }

**Comment by steavy29** [comment]
If telegram had blocked you, you would have received an exception from API with appropriate message.
Check your threads, maybe you just have a deadlock or something else.

**Comment by madadoux** [comment]
i restarted my pc

**Comment by NaderStar** [comment]
I got exactly the same issue too !!!
      
await _sender.Receive(request); // here freezes  using debugger
