### ISSUE TITLE
Exeption in Tl.cs

### ISSUE THREAD

**Issue by melvinsalas** [sochix/TLSharp#201]
Hello!
Works sent message but sometimes in line:
```
if (!constructors.ContainsKey(dataCode))
{
     throw new Exception(String.Format("invalid constructor code {0}", dataCode.ToString("X")));
}
```
Exception thrown: 
```
System.Exception: invalid constructor code F2D2B032
```
Why?

**Comment by steavy29** [comment]
Hi. Could you provide object type name it's trying to Parse when this exception occurs?

**Comment by XyLoNaMiyX** [comment]
More likely you've been trying to read a Telegram object when you shouldn't. That constructor code does **not** belong to any API layer.

**Comment by melvinsalas** [comment]
The problem is in 
`client.GetDialogs(offset, limit)`

Without sticker
![captura1](https://cloud.githubusercontent.com/assets/708747/18494168/cc4ae818-79d1-11e6-8f1d-04ff34879d08.PNG)

With sticker
![captura2](https://cloud.githubusercontent.com/assets/708747/18494169/cc4ca3c4-79d1-11e6-9bc3-9a6a82c31a58.PNG)

**Comment by steavy29** [comment]
Set breakpoint on `throw new Exception..` and when it is hit look at generic `T` type. Post it here. Also please check api layer you are using in `InitConnectionRequest`. There should be line like this `writer.Write(23);// invokeWithLayer23#1c900537` which means that you use api layer 23(which is the correct one).

**Comment by melvinsalas** [comment]
Maping the debuger:

1. `var result = await client.GetDialogs(0, 10);`
2. `await _sender.Receive(request);`
3. `processMessage(result.Item2, result.Item3, messageReader, request);`
4. `HandleRpcResult(messageId, sequence, messageReader, request);`
5. `request.OnResponse(compressedReader);`
6. `messages_element = TL.Parse<Message>(reader);`
7. `((TLObject)(object)obj).Read(reader); //MessageConstructor`
8. `this.media = TL.Parse<MessageMedia>(reader);`
9. `((TLObject)(object)obj).Read(reader); //MessageMediaDocumentConstructor`
10. `this.document = TL.Parse<Document>(reader); //DocumentConstructor`
11. `this.thumb = TL.Parse<PhotoSize>(reader);`
12. And here occurs the issue:
```
if (!constructors.ContainsKey(dataCode))
{
     throw new Exception(String.Format("invalid constructor code {0}", dataCode.ToString("X")));
}
```

dataCode value is `1818578188`DEC or `6C654D0C`HEX
