### ISSUE TITLE
Send PDF Through TLSharp

### ISSUE THREAD

**Issue by alipishvaee** [sochix/TLSharp#202]
Hi.IS It possible To Send PDF File Through TLSharp? What Kind Of File Types Are Supported?

**Comment by alipishvaee** [comment]
If It is Not Possible Please Help How And Which Method Should Be added From Telegram API To Your Request Folder?

**Comment by sochix** [comment]
I recommend you to check Telegram API docs.

**Comment by alipishvaee** [comment]
I checked it.Nothing Found.

**Comment by alipishvaee** [comment]
In Current version I Can Just Send Jpeg And PNG File Which are Photos In Telegram And PDF , Excel ,MP4 ,TXT And Other Types can not be send Although They Are Being Uploded.In Fact In SendMediaMessage They Throw An Exception.As I Looked Ito TL.CS And Other Classes I Found Out Some Kind Of Filtering IS Happen To Just Filter Photo File.May Be I Am Wrong But That's What I Found out Till Now.

**Comment by schlumpf90** [comment]
Hi Alipishvaee, if you (or someone else) solved the problem, please tell... I would like to send other file types, too !

Thanks !

**Comment by iPazooki** [comment]
any solution ? we have same problem and there is problem for sending PDF file. looking forward to hear any good news !
