### ISSUE TITLE
Client.Conect() Exception On Mvc Controller

### ISSUE THREAD

**Issue by m0rtal123** [sochix/TLSharp#207]
hi
my code is : 

       var store = new FileSessionStore();
            var client = new TelegramClient(store, "session", **, "***");

            await client.Connect();

            var hash = await client.SendCodeRequest("***");
            var code = "33792"; // received code from Telegram

            var user = await client.MakeAuth("***", "**", code);
             var userByPhoneId = await client.ImportContactByPhoneNumber("***");

            await client.SendMessage(872087**, @"Hello from **C# Programing ! Screen-reader users, click here to turn off Google Instant.");

**This Code Work in UnitTest Class But in Mvc Contorller I got This Exception :** 

**Line 343:                case 17:
Line 344:                    throw new InvalidOperationException(" msg_id too high (similar to the previous case, the client time has to be synchronized, and the message re-sent with the correct msg_id)");**

**Comment by melvinsalas** [comment]
Delete the file session.dat on "C:\Program Files (x86)\IIS Express" (or equivalent)
Run Visual Studio as Administrator

**Comment by m0rtal123** [comment]
Hoom  !! 

Resolved !! Tnkx For Your Help :)

**Comment by melvinsalas** [comment]
Your welcome.
Please close the issue.
