### ISSUE TITLE
Enhancement: make telegram server address and port as parameter

### ISSUE THREAD

**Issue by schlumpf90** [sochix/TLSharp#208]
Hi to all,

I enhanced your awesome work just for myself, but I think, everyone should use it...

I enhanced the TLSharp of the ability to set the telegram server adress and the port in your own application and not in "TLSharp.Core.dll". So you're more flexible.

Therefore you have to change in "TelegramClient.cs" the following things:

Line 28 = public TelegramClient(ISessionStore store, string sessionUserId, int apiId, string apiHash, string ConnectionAddress, int ConnectionPort)

Line 38 = _session = Session.TryLoadOrCreateNew(store, sessionUserId, ConnectionAddress, ConnectionPort);

In the "Session.cs" :  

Line 156 = public static Session TryLoadOrCreateNew(ISessionStore store, string sessionUserId, string ConnectionAddress, int ConnectionPort)

Line 162 = ServerAddress = ConnectionAddress,
Line 163 = Port = ConnectionPort

You have also change the "new TelegramClient" in all TestMethods.

Thanks and have a nice weekend !

**Comment by steavy29** [comment]
Actually this is a controversial question. I thought the same way at first but then I read about data centers in Telegram and understood that `ServerAddress` in `Session` is just a starting point. When you do an authentication, telegram redirects you to the correct data center. This is currently handled. Actually, there is no 100% way to know which `ServerAddress` to use until you make a request and Telegram will redirect you.
Here is some reading on this topic: https://core.telegram.org/api/datacenter

**Comment by schlumpf90** [comment]
In my opinion you're not 100% right - because you get the telegram server address you have to use at registering your api id  at "https://my.telegram.org/auth".

Take a look at the screenshot...

![telegram server address](https://cloud.githubusercontent.com/assets/20926828/18626455/6b003fe4-7e55-11e6-9d04-9b37f0a3bbba.png)

**Comment by steavy29** [comment]
Well, yes. That is a good point. It depends on who will use your app. If, for example, you create api and you are located in Country1 than you'll see DC for this country in config. But users that register and use your app is a different story. If user is from Country2 than his DC will be different.

The ultimate point is to minimize the need of reconnections. If you know that most of your users will be from the country you registered API from,  than yes, this might help. And yes, adding a possibility to configure this `ServerAddress` definitely won't hurt. Just make sure you understand how to use it.

Will add this feature in my fork :)

**Comment by steavy29** [comment]
If you're still interested in the feature, you can check my [fork](https://github.com/steavy29/Telegram.Net), where I added those parameters.

**Comment by schlumpf90** [comment]
Thanks a lot - great work !  :-)
