### ISSUE TITLE
Build errors in VS 2015

### ISSUE THREAD

**Issue by Veterinarr** [sochix/TLSharp#210]
Hi I got about 30 errors when compile TLSharp.Core some of the errors repeat one another.
Maybe I am missing something I am not a pro.
Will appreciate some advice wher to look.
Here's a list of errors:
**1 -** Error	CS0006	Metadata file 'C:\Users\admin\Desktop\TLSharp-master\TLSharp.Core\bin\Release\TLSharp.Core.dll' could not be found
**2 -** CS1519	Invalid token 'return' in class, struct, or interface member declaration	TLSharp.Core "This one os present in line 335" line code: return request.message;
**3 -** Error	CS0538	'_sender' in explicit interface declaration is not an interface	TLSharp.Core
This is a few of them, I don't want to make a mess hope this will be enough to point me in the right direction.
Thanks.

**Comment by sochix** [comment]
Hope it fixed now

**Comment by Veterinarr** [comment]
Yes it compiles greate right now, thank you for your help.
