### ISSUE TITLE
Getting a migrate_x error, many times.

### ISSUE THREAD

**Issue by Veterinarr** [sochix/TLSharp#212]
Hi I am trying to check my own phone number for Registration, but geting error, here is the text of Error:
[An exception of type 'System.InvalidOperationException' occurred in mscorlib.dll but was not handled in user code

Additional information: Your phone number registered to 2 dc. Please update settings. See https://github.com/sochix/TLSharp#i-get-an-error-migrate_x for details.]

Here is my code example:
`     static void Main()
     {
        Task t = Task.Factory.StartNew(() => Aut());
        t.Wait();
        Console.WriteLine("one action task");
        Console.ReadKey();

    }
    private static async void Aut()
    {
        var store = new FileSessionStore();
        var client = new TelegramClient(store, "session", MyID, "API hash");
        await client.Connect();
        var result = await client.IsPhoneRegistered("myNumber");
    }`

**Comment by steavy29** [comment]
Hi. I recently fixed this issue in my fork. You can [check it out](https://github.com/steavy29/Telegram.Net)

**Comment by Veterinarr** [comment]
Thank you it is working now
