### ISSUE TITLE
Stuck on Client.Connect

### ISSUE THREAD

**Issue by aarani** [sochix/TLSharp#213]
Hi .
I tested repo via Console Application and it work like charm but when i use it in web application code stuck on Client.Connect().Wait().

what can I do ?

**Comment by steavy29** [comment]
Was session file created?

**Comment by aarani** [comment]
Nope

**Comment by steavy29** [comment]
Then try using `FakeSessionStore` instead of `FileSessionStore` and see if it helps.

**Comment by aarani** [comment]
I tried it before . not work

**Comment by aarani** [comment]
I wrote custom Store (using database) and it won't work then i tried FakeSessionStore. won't work again

**Comment by steavy29** [comment]
Then maybe problem is in your `.Wait()`? It should be somehow related to the fact that you run it as a web app. Can you post more code?

**Comment by aarani** [comment]
Solved using Thread (Start & Join)
