### ISSUE TITLE
Exeption in Tl.cs

### ISSUE THREAD

**Issue by nezam1** [sochix/TLSharp#22]
hello
works sent message but sometimes in line 
if (!constructors.ContainsKey(dataCode))
				{
					throw new Exception(String.Format("invalid constructor code {0}", dataCode));
				}
Exception thrown: 'System.Exception' in TLSharp.Core.dll ("invalid constructor code 1444835612")
why?

**Comment by sochix** [comment]
It's a bug :(

**Comment by sochix** [comment]
Fixed
