### ISSUE TITLE
Is authentication necessary for every message you wanna send to someone!?

### ISSUE THREAD

**Issue by mersi77** [sochix/TLSharp#221]
Is authentication necessary for every message you wanna send to someone!?

**Comment by andrew-maksimov** [comment]
No.

**Comment by mersi77** [comment]
Could you elaborate on it more? Without authentication I receive this error : "AUTH_KEY_UNREGISTERED"

**Comment by aarani** [comment]
No there is no need to re-authenticate you can Check IsUserAuthorized Response

**Comment by mersi77** [comment]
bool  isAuth = client.IsUserAuthorized();
            if (isAuth)
                     var result = await client.ImportContactByPhoneNumber("98...");


Inspite of "isAuth" is true, but this code returns "AUTH_KEY_UNREGISTERED" on last line of above code!
