### ISSUE TITLE
Чтение после конца потока невозможно.

### ISSUE THREAD

**Issue by str1py** [sochix/TLSharp#226]
Всем привет. Возникла проблема

После отсылки кода 
var hash = await client.SendCodeRequest(TelegramPhone.Text); 
 
Код приходит и программа крэшиться.

Вызвано исключение: "System.InvalidOperationException" в TLSharp.Core.dll
Вызвано исключение: "System.InvalidOperationException" в mscorlib.dll
Вызвано исключение: "System.IO.EndOfStreamException" в mscorlib.dll
Вызвано исключение: "System.IO.EndOfStreamException" в mscorlib.dll
Вызвано исключение: "System.IO.EndOfStreamException" в mscorlib.dll
Вызвано исключение: "System.IO.EndOfStreamException" в mscorlib.dll
Исключение типа "System.IO.EndOfStreamException" возникло в mscorlib.dll, но не было обработано в коде пользователя
Дополнительные сведения: Чтение после конца потока невозможно.

Необработанное исключение типа "System.IO.EndOfStreamException" в mscorlib.dll
Дополнительные сведения: Чтение после конца потока невозможно.

Тем не менее создается session.dat  и при повторной попытке(не удаляя session.dat) все работает.

(If you`ll need i will translate it into English)

**Comment by andrew-maksimov** [comment]
I have the same problem. (у меня тоже самое)

**Comment by sochix** [comment]
Library updated. Check now.
