### ISSUE TITLE
reuse session in web

### ISSUE THREAD

**Issue by sinaprog** [sochix/TLSharp#227]
i saved session with below snippet 
`await client.MakeAuth("", hash, Codetb.Text);
            TLSharp.Core.Session s = null;
            s = store.Load("session");
            System.IO.File.WriteAllBytes(HttpContext.Current.Server.MapPath(".") + "\\session.dat", s.ToBytes());`
and then in next  run read saved session with
`FileSessionStore store = new FileSessionStore();
            TLSharp.Core.Session.FromBytes(System.IO.File.ReadAllBytes(HttpContext.Current.Server.MapPath(".") + "\\session.dat"), store, "session");
            TelegramClient client = new TelegramClient(store, "session", apiid, "apihash");`
but it returns 

> AUTH_KEY_UNREGISTERED

**Comment by schlumpf90** [comment]
Hi,

take a look at this example: 

http://www.sochix.ru/how-to-send-messages-to-telegram-from-c/

Good luck !

**Comment by Trombov** [comment]
Hi,
Did you solve the problem?
