### ISSUE TITLE
how can i get messages between me and another one?

### ISSUE THREAD

**Issue by starbug1** [sochix/TLSharp#23]
Hi. I want to be able to retrieve my conversation in a chat with another person. can i do this using TLSharp?
Thanks.

**Comment by XyLoNaMiyX** [comment]
You can implement your own requests by having a look to the existing ones and to the telegram methods list: https://core.telegram.org/methods

Anyway, I've made a pull request which implements this method, but it hasn't been accepted yet. Do you want to backup your conversation? I'm making a program about that.

**Comment by starbug1** [comment]
@XyLoNaMiyX: No i just want to access them. i need to read messages in my conversation to every one that i want.

**Comment by XyLoNaMiyX** [comment]
Use:
```csharp
var contactId = await client.ImportContact(phone_number).Result;
var msgs = await client.GetHistory(user_id, offset, max_id, amount);
```

**Comment by starbug1** [comment]
@XyLoNaMiyX : Thanks. but if i have just username of person, then what i must do?

**Comment by XyLoNaMiyX** [comment]
That isn't implemented in this branch, you can check out https://github.com/Kred88/TLSharp/tree/Untestes/TLSharp.Core

I have a pull request of it but I don't know how to merge it! :/

**Comment by sochix** [comment]
Pull request merged
