### ISSUE TITLE
still missing events

### ISSUE THREAD

**Issue by parsagachkardev** [sochix/TLSharp#230]
It's a cool idea since Telegram Bot API is really limited.
but this library can't use telegram functions completely yet.

there is still missing events for getting updates.
missing cannel functions 
& ...

BTW plz add it as a Nuget Library to Nuget.Org downloading & compiling the lib is a pain in ass!

**Comment by aarani** [comment]
sochix merge a pull request near 8 hours ago that add all of  functions . it's just not documented yet !

**Comment by parsagachkardev** [comment]
What about events ?

**Comment by aarani** [comment]
As you can see in todo roadmap it's not ready now maybe in a week
