### ISSUE TITLE
handle file_migrate_x error

### ISSUE THREAD

**Issue by pishgaman-org** [sochix/TLSharp#232]
hi

when I want to download some files , file_migrate_x error occurs that means the files stored in another DC.
how should I resend request to another DC in a way my session file not be corrupted?

**Comment by pishgaman-org** [comment]
I solved it myself. thank you for fast replies!

**Comment by rootqey** [comment]
hi ,
I use request while get profile picture
upload.getFile#e3a6cfb5 location:InputFileLocation offset:int limit:int = upload.File;
in the response return FILE_MIGRATE_X 
How did you solve it ?
thanks

**Comment by pishgaman-org** [comment]
hi
first you should export authorization, next reconnect to new dcid and import exported authorization.
at last resend getfile request.

**Comment by atabaki** [comment]
thanks for your reply
id used this technique from telegram doc:

> auth.exportAuthorization must be executed in the current DC (the DC with which a connection has already been established), passing in dc_id as the value for the new DC. The method should return the user identifier and a long string of random data. An import operation can be performed at the new DC by sending it what was received. Queries requiring authorization can then be successfully executed in the new DC.

**Comment by sochix** [comment]
@pishgaman-org should we run it in separate thread?

**Comment by pishgaman-org** [comment]
yes and no. you could use a copy of session in a new thread or reload original session after file download completed.
I used the second way.

**Comment by sochix** [comment]
@pishgaman-org how can I reload an original session, I'm bit stuck

**Comment by sochix** [comment]
fixed
