### ISSUE TITLE
Getting profile image of an account.

### ISSUE THREAD

**Issue by mersi77** [sochix/TLSharp#234]
Is there any way to get profile image of an account(phone No)?

**Comment by sochix** [comment]
Yep, get all contacts. Then call getFullUser https://core.telegram.org/method/users.getFullUser

**Comment by MehdiGhafourian** [comment]
I can't find getFullUser method!!!
How to get Profile photo of each contact and show them?
I use this code:

var buffer = user.Photo.Serialize();
                    MemoryStream ms = new MemoryStream(buffer, true);
                    
                    userPhoto = Bitmap.FromStream(ms,true,true);
                   
but it throw "Parameter is  not valid" exception   !!!


Is there anyone give me a hand???/

**Comment by arsdever** [comment]
Hey guys. I'm here to say that to get the images for multiple users (e.g. 20) I'm getting `FloodException`. The way I try to do this is to call `client.GetFile` for each user. This seems to introduce a new request for each call. Hence, if you have 20 users, you make 20 requests and thus get blocked by the API. Is there a way to get all the images at once?
