### ISSUE TITLE
Library update.

### ISSUE THREAD

**Issue by Seekeer** [sochix/TLSharp#239]
Some days ago lib interfaces have been updated dramaticaly while readme hasnt been changed.

I couldnt understand how to work with new lib version. 

Can anyone provide me sample code to get:

1. All account dialogs.
2. All messages in this dialogs.

**Comment by aarani** [comment]
I haven't enough time to document it but @sochix said to me that he will document it soon . 
You can use previous releases until that

**Comment by sochix** [comment]
@Seekeer yep, I'm working on it

**Comment by sochix** [comment]
Done
