### ISSUE TITLE
unable to cast object of type 'TLSharp.Core.MTProto.UserContactCostructor' to type TLSharp.Core.MTProto.UserSelfCostructor

### ISSUE THREAD

**Issue by hamidpp** [sochix/TLSharp#24]
hi: i get this error after invoke sendMessage method in test mode :
unable to cast object of type 'TLSharp.Core.MTProto.UserContactCostructor' to type TLSharp.Core.MTProto.UserSelfCostructor
please help me.

**Comment by sochix** [comment]
Don't try to send messages to your self!
17 окт. 2015 г. 3:46 пользователь "hamid reza" <notifications@github.com>
написал:

**Comment by hamidpp** [comment]
fixed. i change receiver message phone number and fixed. thanks.
how to send media now? Please guide my friend

**Comment by sochix** [comment]
No way to send media, sorry. You can contribute or donate
17 окт. 2015 г. 22:56 пользователь "hamid reza" <notifications@github.com>
написал:

**Comment by hamidpp** [comment]
how to invoke auth.resetAuthorizations method?

**Comment by hamidpp** [comment]
i define method to auth.resetAuthorizations with this body :+1: public override void OnSend(BinaryWriter writer)
		{
			writer.Write(0x9fab0d1a);
			Serializers.String.write(writer, "");
		}
but get this error, INPUT_REQUEST_TOO_LONG

**Comment by sochix** [comment]
Sorry can't help, read the documentation of Telegram API.

**Comment by hamidpp** [comment]
thanks, but worst tired dear friend with the donation
