### ISSUE TITLE
SendCodeRequestAsync Exceptions

### ISSUE THREAD

**Issue by str1py** [sochix/TLSharp#240]
var hash = await client.SendCodeRequestAsync(Phone.Text);

Исключение типа "System.IO.InvalidDataException" возникло в mscorlib.dll, но не было обработано в коде пользователя
Дополнительные сведения: Constructor Invalid Or Context.Init Not Called !

OR

Исключение типа "System.InvalidOperationException" возникло в mscorlib.dll, но не было обработано в коде пользователя

Дополнительные сведения: Couldn't read the packet length

**Comment by sochix** [comment]
Send your codesnippet please

11 окт. 2016 г. 18:39 пользователь "Pavel Anulyev" <notifications@github.com>
написал:

**Comment by str1py** [comment]
private static readonly FileSessionStore store = new FileSessionStore();
        private readonly TelegramClient client = new TelegramClient(0, "00000");
        public int Click = 0;
        public string hash;

protected async Task Auth()
{
 await client.ConnectAsync();
            if (String.IsNullOrEmpty(Mobile.Text) == true)
            {
                ErrorMessage.Content = "Phone is null.Please enter your phone";
            }
            else
            {
                var result = await client.IsPhoneRegisteredAsync(Mobile.Text);
                if (result == true)
                {
                    if (Click == 0)
                    {
                        hash = await client.SendCodeRequestAsync(Mobile.Text);          
                    }
                    else
                    {
                        var code = TelegramCode.Text; 
                        var user = await client.MakeAuthAsync(Mobile.Text, hash, code);                     
                        MainLogic.MainVars.TelegramUserID = user.id;            
                    }
                    Click++;
                }
                else
                {
                    ErrorMessage.Content = "Number is not registered";
                }
            }
}

**Comment by sochix** [comment]
Delete session.dat and retry

11 окт. 2016 г. 19:10 пользователь "Pavel Anulyev" <notifications@github.com>
написал:

**Comment by str1py** [comment]
If there is no session.dat ->  Constructor Invalid Or Context.Init Not Called !
Here `protected async Task Auth()`

**Comment by sochix** [comment]
Did you get your apiid from telegram or use zeros?

11 окт. 2016 г. 20:14 пользователь "Pavel Anulyev" <notifications@github.com>
написал:

**Comment by str1py** [comment]
I use my apiid. 
So, when there is no no session.dat the Constructor invalid.
Next try -> there is no problems. 
And other tries couldn't read the package length

**Comment by sochix** [comment]
Will try to reproduce

12 окт. 2016 г. 10:12 пользователь "Pavel Anulyev" <notifications@github.com>
написал:

**Comment by str1py** [comment]
Ok, thank you

**Comment by sochix** [comment]
It was a bug. Fixed now. Rechcek please
