### ISSUE TITLE
INPUT_REQUEST_TOO_LONG error when i using TLRequestImportContacts request

### ISSUE THREAD

**Issue by isaeid63** [sochix/TLSharp#243]
I want to use TLRequestImportContacts request method to import contacts with phone numbers and i write this code:
`var request = new TeleSharp.TL.Contacts.TLRequestImportContacts();`
            `request.contacts = new TLVector<TLInputPhoneContact>();`
            `request.contacts.lists.Add(new TLInputPhoneContact() { phone = phoneNumber, first_name= "My Test Name", last_name=string.Empty  });`
            `var invokewithLayer = new TLRequestInvokeWithLayer() { layer = 53, query = request };`
            `//var request = new TLRequestImportContacts() {  }`
            `var k = await SendRequestAsync<TLImportedContacts>(invokewithLayer);`
But i always get the INPUT_REQUEST_TOO_LONG error.

**Comment by sochix** [comment]
You have too much contacts. That's the obvious answer. Check Telegram API for further details.

**Comment by kerlaedra** [comment]
I have the same problem and empty contacts. The problem is not in the count of contacts.
My code:
`var phoneContact = new TLInputPhoneContact() { phone = phoneNumber, first_name = "", last_name = ""};
            var contacts = new List<TLInputPhoneContact>() { phoneContact };
            var req = new TLRequestImportContacts() { contacts = new TLVector<TLInputPhoneContact>() { lists = contacts } };
            await client.SendRequestAsync<Boolean>(req);

**Comment by masoudsojodi** [comment]
you can use this method
it worked
 client = new TelegramClient(apiId, apiHash);
        await client.ConnectAsync();

        var phoneContact = new TLInputPhoneContact() { phone = "989121781885", first_name = "غیاثی", last_name = "" };
        var contacts = new List<TLInputPhoneContact>() { phoneContact };
        var req = new TeleSharp.TL.Contacts.TLRequestImportContacts() { contacts = new TLVector<TLInputPhoneContact>() { lists = contacts } };
   var rrr=     await client.SendRequestAsync<TeleSharp.TL.Contacts.TLImportedContacts>(req);

**Comment by jefferyleo** [comment]
@masoudsojodi It doesn't work on the latest version of TLSharp now, any others way to import contact?
