### ISSUE TITLE
Upload file was removed from this version

### ISSUE THREAD

**Issue by wolvewilson** [sochix/TLSharp#244]
Please, do you have a example about how can i send photos to a chat or a contact?

obs.: i´ve modified you code to connect to telegram through a proxy authentication. 
Do you think this change is interesting? can I propose this change here in the repository?

**Comment by sochix** [comment]
Upload files need to be added. It's in roadmap.

Yep, it's interesting. Show me your proxy code.

**Comment by sochix** [comment]
@aarani working on it

**Comment by aarani** [comment]
@sochix  @wolvewilson I created a pull request containing File UploadHelper but i haven't any chance to test it

**Comment by sochix** [comment]
@aarani pull-request meged. Testing now.

**Comment by sochix** [comment]
It's added back
