### ISSUE TITLE
Why the Chat is null?

### ISSUE THREAD

**Issue by ackid32** [sochix/TLSharp#245]
Hi,

This is my code.

after executing the GetUserDialogsAsync, 
the dialogs have the count of 4 chats
and in one have the title of "XYZ"
But i supply the "XYZ" to groupname, the chat returns null.

any help?

=================================================
  public async Task SendMessageToChannelTest(int apiId, string apiHash,string TeleMessage,string GroupName )
        {
            var client = new TelegramClient(apiId, apiHash);

            await client.ConnectAsync();

            var dialogs = await client.GetUserDialogsAsync();
            var chat = dialogs.chats.lists
                .Where(c => c.GetType() == typeof(TLChannel))
                .Cast<TLChannel>()
                .FirstOrDefault(c => c.title == GroupName);

            await client.SendMessageAsync(new TLInputPeerChannel() { channel_id = chat.id, access_hash = chat.access_hash.Value }, TeleMessage);
        }

    }

**Comment by aarani** [comment]
It's Simply because XYZ isn't a CHANNEL !

**Comment by sochix** [comment]
@aarani nice job!

**Comment by mehdiyahyavi** [comment]
your code is true, but a little change to performance 

var dialogs = (TLDialogsSlice)await client.GetUserDialogsAsync();
            var chat = dialogs.chats.lists
                .OfType<TLChannel>()
                .FirstOrDefault(c => c.title == TextBox1.Text);
            await client.SendMessageAsync(new TLInputPeerChannel() { channel_id = chat.id, access_hash = chat.access_hash.Value },TextBox2.Text);

TL.channel use for SuperGroup. 
chat is null issue, when showing to u, because your account no joined to destination group. first you need to join your account to group.
