### ISSUE TITLE
var request = new TLRequestSignIn() { phone_number = phoneNumber, phone_code_hash = phoneCodeHash, phone_code = code}; At MakeAuthAsync Method

### ISSUE THREAD

**Issue by maede71** [sochix/TLSharp#246]
How can I not get  a new security code every time  For TLRequestSignIn instance???

**Comment by aarani** [comment]
It's not TLRequestSignIn that generate code and code generate via TLSendCode (and it's security part and there's no way to bypass it )

**Comment by sochix** [comment]
@maede71 read TLSharp docs carefully
