### ISSUE TITLE
Create a new channel and send message

### ISSUE THREAD

**Issue by rafalrozek** [sochix/TLSharp#247]
Is that possible to create a new channel and the there a message?

**Comment by sochix** [comment]
Yes, it is. Check Telegram API docs. Use `SendRequestAsync`.

**Comment by Gawiga** [comment]
I struggle with this for a while, because I was forgetting to use the namespace `TeleSharp.TL.Channels;`
``` 
var newGroup = new TLRequestCreateChannel()
{
	Broadcast = false,
	Megagroup = false,
	Title = "Group Name",
	About = "Description Group"
};
await client.SendRequestAsync<bool>(newGroup); 
```

**Comment by davidcon** [comment]
Is it possible to modify Channel default permits?
I want to allow "Add users" and deny "Send Pools", "Send sticker".
Thank you very much!
