### ISSUE TITLE
Create new Chat Request function

### ISSUE THREAD

**Issue by rafalrozek** [sochix/TLSharp#249]
I want to create a new chat, but this function doesn't work. Why?
`        private async Task create()
        {
            var c = new TLRequestCreateChat()
            {
                //add to users only me
                users = new TLVector<TLAbsInputUser>(),
                title = "test",
                
            };
            var x = await client.SendRequestAsync<TLMessage>(c);

        }`

Can anyone repair this code? :(

**Comment by sochix** [comment]
Read this https://github.com/sochix/TLSharp#nothing-helps before create new issue!
