### ISSUE TITLE
How can i run telegram instance from multiple numbers

### ISSUE THREAD

**Issue by tsoftit** [sochix/TLSharp#25]
please all can any one help me I want run telegram instance from multiple numbers
I use one of registered number . But is there any way to switch to another number ?

**Comment by sochix** [comment]
No easy way to switch between numbers.
18 окт. 2015 г. 7:28 пользователь "tsoftit" <notifications@github.com>
написал:

**Comment by tsoftit** [comment]
if you have any way please help me

**Comment by sochix** [comment]
Just create a new session instance. But you can't do it from code. This
feature isn't developed.  To speedup development donation needed.
18 окт. 2015 г. 15:26 пользователь "tsoftit" <notifications@github.com>
написал:

**Comment by tsoftit** [comment]
please how create a new session instance out code any sample or help please?

**Comment by sochix** [comment]
See CreateAuth test

**Comment by tsoftit** [comment]
please im try run telegram.org in webbrowser  but not navigate any help?
