### ISSUE TITLE
TLRequestCreateChat - INPUT_CONSTRUCTOR_INVALID

### ISSUE THREAD

**Issue by rafalrozek** [sochix/TLSharp#251]
hey, i want to create a new chat.
my code: http://pastebin.com/raw/eFrJp7PZ
error:
> An exception of type 'System.InvalidOperationException' occurred in mscorlib.dll but was not handled in user code
Additional information: INPUT_CONSTRUCTOR_INVALID

**Comment by sochix** [comment]
Grab the latest library version from git and recheck

**Comment by rafalrozek** [comment]
Ok i grabbed the latest version and i have the same problem.
I think, it's something wrong with this line:
users = new TLVector<TLAbsInputUser>(),

**Comment by rafalrozek** [comment]
My full code:
http://pastebin.com/DMrR4vbX
