### ISSUE TITLE
При попытке добавить контакт выбрасывается исключение "INPUT_REQUEST_TOO_LONG"

### ISSUE THREAD

**Issue by kerlaedra** [sochix/TLSharp#252]
Пробовал на аккаунте с 25-ю контактами и с полностью пустыми контактами(только зарегистрирован).
Мой код:
```
var phoneContact = new TLInputPhoneContact() { phone = phoneNumber, first_name = "", last_name = ""};
var contacts = new List<TLInputPhoneContact>() { phoneContact };
var req = new TLRequestImportContacts() { contacts = new TLVector<TLInputPhoneContact>() { lists = contacts } };
await client.SendRequestAsync<Boolean>(req);
```

**Comment by aarani** [comment]
Duplicate #243

**Comment by mohamadpk** [comment]
this error on add contact or ant using tlvector  occurred.becuse  on SerializeBody of tlvector list count not write.
add this line after write vector contractor hash.
            bw.Write(lists.Count);

**Comment by sochix** [comment]
yep @mohamadpk . You're right! It's fixed now
