### ISSUE TITLE
FILE_MIGRATE_X and AUTH_BYTES_INVALID errors

### ISSUE THREAD

**Issue by rootqey** [sochix/TLSharp#254]
Hello ,
I use request while get profile picture
upload.getFile#e3a6cfb5 location:InputFileLocation offset:int limit:int = upload.File;
in the response return FILE_MIGRATE_X ,
after I added to the TelegramClient.cs  authExportAndImport method. When run code I get AUTH_BYTES_INVALID error from server. why server return invalid for my auth key(128 Byte).
Can you help me please ? Thanks

        public async Task<User> authExportAndImport(int dc_id)
        {
            var request_export = new AuthExport(dc_id);
            await _sender.Send(request_export);
            await _sender.Receive(request_export);
            var exportedAuthorization = (Auth_exportedAuthorizationConstructor)request_export.exportedAuthorization;

            var request_import = new AuthImport(exportedAuthorization.id, exportedAuthorization.bytes);
            await _sender.Send(request_import);
            await _sender.Receive(request_import);

            return request_import.user;
        }

**Comment by sochix** [comment]
Read telegram api manual. Can't help with migration

19 окт. 2016 г. 18:23 пользователь "rootqey" <notifications@github.com>
написал:

**Comment by pishgaman-org** [comment]
before importing authorization you should reconnect to new dcid.
