### ISSUE TITLE
How implement HandleBadMsgNotification in error code 16 and 17 to prevent threw exception?

### ISSUE THREAD

**Issue by majid23** [sochix/TLSharp#257]
Hello,
Some times i receive below exceptions:
" msg_id too low (most likely, client time is wrong; it would be worthwhile to synchronize it using msg_id notifications and re-send the original message with the “correct” msg_id or wrap it in a container with a new msg_id if the original message had waited too long on the client to be transmitted)"
or 
" msg_id too high (similar to the previous case, the client time has to be synchronized, and the message re-sent with the correct msg_id)"

I want handle this errors without delete session file and create new session.
How can i implement this in 
private bool HandleBadMsgNotification(ulong messageId, int sequence, BinaryReader messageReader) function.
thanks.

**Comment by sochix** [comment]
It requires proper HandleUpdate method, which is in roadmap
