### ISSUE TITLE
problem in tlsharp please help me

### ISSUE THREAD

**Issue by tsoftit** [sochix/TLSharp#26]
after I used AuthUser  with defaultConnectionAddress = "91.108.56.165" 
I get this error 
" An exception of type 'System.InvalidOperationException' occurred in mscorlib.dll but was not handled in user code
Additional information: Your phone number registered to 1 dc. Please update settings. See https://github.com/sochix/TLSharp#i-get-an-error-migrate_x for details."
I  go to link  https://github.com/sochix/TLSharp#i-get-an-error-migrate_x and read I must chage server address I change it to defaultConnectionAddress = "149.154.167.51" then try again I get this error 
" An exception of type 'System.IO.EndOfStreamException' occurred in mscorlib.dll but was not handled in user code
Additional information: Unable to read beyond the end of the stream. "
please any help and I hope give me complete work example 
thanks

**Comment by sochix** [comment]
Try delete session, and restart the test.

**Comment by tsoftit** [comment]
thanks for replay
you mean that change line var client = new TelegramClient(store, "session");
to var client = new TelegramClient(store, "");
if you mean this I try but the same problem

**Comment by starbug1** [comment]
@tsoftit :No you must delete session file that is created in bin folder of your project

**Comment by tsoftit** [comment]
thanks my friend but I find this error while I  want send message
An exception of type 'Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException' occurred in Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll but was not handled in user code

Additional information: Assert.IsTrue failed."
please any help

**Comment by hamidpp** [comment]
in invoke sendMessage method in client.Connect() line i get this error:
System.OutOfMemoryException
help please.
