### ISSUE TITLE
Unable to cast object of type 'System.Int32' to type 'TeleSharp.TL.TLObject'

### ISSUE THREAD

**Issue by timocov** [sochix/TLSharp#261]
Hi,
seems that `TLVector<T>` hasn't code to serialize list with `int`, `long`, `string` or `double` (for deserialize it has).
In that case when I try to send `TLRequestGetChats` request I get an error:
```Unable to cast object of type 'System.Int32' to type 'TeleSharp.TL.TLObject'.```

**Comment by sochix** [comment]
That's true. Will fix

**Comment by sochix** [comment]
fixed
