### ISSUE TITLE
How can I send message to a bot and group/supergroup ?

### ISSUE THREAD

**Issue by AndrewChan0513** [sochix/TLSharp#262]
I am trying to use TLGame but not working
.Where(c => c.GetType() == typeof(TLGame))

And the group or super group also haven't type

Thanks

**Comment by sochix** [comment]
Sorry, it's telegram api question can't help. Try to explore what Telegram returns to you.

**Comment by AndrewChan0513** [comment]
I've tryed to use SendMessageAsync to send message to a bot but failed ( nothing happen ) 

Using TLInputPeerUser without access hash:
`            await client.SendMessageAsync(new TLInputPeerUser() { user_id = int.Parse(textBox7.Text)}, textBox6.Text);`

Using TLInputPeerUser with access hash:
`            await client.SendMessageAsync(new TLInputPeerUser() { user_id = int.Parse(textBox7.Text), access_hash = Convert.ToInt64("-332761358708919000") }, textBox6.Text);`

Using TLInputPeerChat with access hash:
`            await client.SendMessageAsync(new TLInputPeerChat() { chat_id = int.Parse(textBox7.Text) }, textBox6.Text);`

Using TLInputPeerChannel with access hash:
`            await client.SendMessageAsync(new TLInputPeerChannel() { channel_id = int.Parse(textBox7.Text), access_hash = Convert.ToInt64("-332761358708919000") }, textBox6.Text);`

the bot id and access hash information
![image](https://cloud.githubusercontent.com/assets/20835419/19640215/4f05f818-9a0e-11e6-9bc6-3c2ccb4d2754.png)

**Comment by sochix** [comment]
```
Using TLInputPeerUser without access hash:
await client.SendMessageAsync(new TLInputPeerUser() { user_id = int.Parse(textBox7.Text)}, textBox6.Text);

Using TLInputPeerUser with access hash:
await client.SendMessageAsync(new TLInputPeerUser() { user_id = int.Parse(textBox7.Text), access_hash = Convert.ToInt64("-332761358708919000") }, textBox6.Text);

Using TLInputPeerChat with access hash:
await client.SendMessageAsync(new TLInputPeerChat() { chat_id = int.Parse(textBox7.Text) }, textBox6.Text);

Using TLInputPeerChannel with access hash:
await client.SendMessageAsync(new TLInputPeerChannel() { channel_id = int.Parse(textBox7.Text), access_hash = Convert.ToInt64("-332761358708919000") }, textBox6.Text);
```
Is something from this method works?
Can you attach an exception that you got?

**Comment by AndrewChan0513** [comment]
I found the problem and fixed. Thanks
Send message to BOT / Group is different:

**SuperGroup  :**
TLInputPeerChannel With Access Code
Can use **`SendMessageToChannelTest()`**


**Group :**
TLInputPeerChat Without Access Code

```
        public async Task SendMessageToGroupTest()
        {
            var client = new TelegramClient(apiId, apiHash);

            await client.ConnectAsync();

            var dialogs = await client.GetUserDialogsAsync();
            var chat = dialogs.chats.lists
                .Where(c => c.GetType() == typeof(TLChat))
                .Cast<TLChat>()
                .FirstOrDefault(c => c.title == "Group Tittle");

            await client.SendMessageAsync(new TLInputPeerChat() { chat_id = chat.id}, "!Test Message!");
        }
```


**MySelf / Bot :**
TLInputPeerUser With Access Code

        public async Task SendMessageToBOTTest()
        {
            var client = new TelegramClient(apiId, apiHash);

            await client.ConnectAsync();

            var dialogs = await client.GetUserDialogsAsync();
            var chat = dialogs.users.lists
                .Where(c => c.GetType() == typeof(TLUser))
                .Cast<TLUser>()
                .FirstOrDefault(c => c.username == "Telegram username"); //Tittle is c.first_name

            await client.SendMessageAsync(new TLInputPeerUser() { user_id = chat.id, access_hash = chat.access_hash.Value }, "text message");
        }

**Comment by sochix** [comment]
Sorry can't help. It's telegram api.

24 окт. 2016 г. 6:26 пользователь "AndrewChan0513" <notifications@github.com>
написал:

**Comment by amirhossein3** [comment]
Hello 

how Forward message to supergroup?

The resources for this library is not enough, I'm trying to Forward a message to channel or superGroup .

I'm not quiet sure how to get channel post peer id (for forward function input parameters)
var store = new FileSessionStore();
            var client = new TelegramClient(apiID,apiHash, store, "session");
            await client.ConnectAsync();
            var dialogs = (TLDialogs)await client.GetUserDialogsAsync();
            var chat = dialogs.chats.lists
                .OfType<TLChannel>()
                .SingleOrDefault(a=>a.title=="test");
            await client.SendRequestAsync<TLAbsUpdates>(
                               new TLRequestForwardMessage()
                               {
                                   id = 2,
                                   peer = new TLInputPeerChannel() { channel_id = chat.id, access_hash = chat.access_hash.Value },
                                   random_id = Helpers.GenerateRandomLong()
                               });

I get this error message :
{"PEER_ID_INVALID"}

Thanks

**Comment by motalebe** [comment]
Forward Mesages:
https://github.com/sochix/TLSharp/issues/503

**Comment by lucfortunato** [comment]
How to get access code?
