### ISSUE TITLE
FILE_MIGRATE_2

### ISSUE THREAD

**Issue by atabaki** [sochix/TLSharp#265]
When i read channel message i encounter this error randomly
An exception of type 'System.InvalidOperationException' occurred in mscorlib.dll but was not handled in user code  Additional information:

**Comment by atabaki** [comment]
Additional information: FILE_MIGRATE_2

**Comment by atabaki** [comment]
![vs](https://cloud.githubusercontent.com/assets/23040214/19663674/d5d40782-9a49-11e6-963b-084ac3980d15.png)

**Comment by atabaki** [comment]
![vs](https://cloud.githubusercontent.com/assets/23040214/19666171/b04762c8-9a55-11e6-8b26-2ec30b1fbbdc.png)

**Comment by sochix** [comment]
It's in our roadmap

**Comment by pishgaman-org** [comment]
@atabaki  @sochix  read this : #232
