### ISSUE TITLE
Unable to cast object of type 'TeleSharp.TL.Messages.TLDialogsSlice' to type 'TeleSharp.TL.Messages.TLDialogs' 

### ISSUE THREAD

**Issue by openrlove** [sochix/TLSharp#267]
i get error 
<Unable to cast object of type 'TeleSharp.TL.Messages.TLDialogsSlice' to type 'TeleSharp.TL.Messages.TLDialogs' >
 when i try to run this code.

var dialogs = await client.GetUserDialogsAsync();

**Comment by atabaki** [comment]
You must change 

```
 public async Task<TLDialogs> GetUserDialogsAsync()
        {
            var peer = new TLInputPeerSelf();
            return await SendRequestAsync<TLDialogs>(
                new TLRequestGetDialogs() { offset_date = 0, offset_peer = peer, limit = 100 });
        }
```
To

```
public async Task<TLDialogsSlice> GetUserDialogsAsync()
        {
            var peer = new TLInputPeerSelf();
            return await SendRequestAsync<TLDialogsSlice>(
                new TLRequestGetDialogs() { offset_date = 0, offset_peer = peer, limit = 100 });
        }
```


in TelegramClient.cs File in TLSharp.Core Project

**Comment by sochix** [comment]
Nope, I think we should return abstract type here. Thanks for bug report

**Comment by aarani** [comment]
@sochix  it's Sochix Mistake by using TLDialogSlice  instead of TLAbsDialogs but Generator work fine and according to [THIS](https://github.com/sochix/TLSharp/blob/master/TeleSharp.TL/TL/Messages/TLRequestGetDialogs.cs#L25) you must use TLAbsDialogs

**Comment by knocte** [comment]
You're doing the cast yourself in your code. The cast is not done inside TLSharp. Fix the cast?

**Comment by AndrewChan0513** [comment]
Solved. Thanks

Using :
`var dialogs = (TLDialogsSlice) await client.GetUserDialogsAsync();`

**Comment by haririan** [comment]
use TLDialogs instead of TLDialogsSlice
this will help you all
var dialogs = await client.GetUserDialogsAsync() **as TLDialogs**;

**Comment by sheldonreddy** [comment]
Haririan's solution worked for me.
