### ISSUE TITLE
MIGRATE_X Error

### ISSUE THREAD

**Issue by rashcms** [sochix/TLSharp#27]
I Got MIGRATE_X error for some numbers
i have tested all 5 servers and there was no luck !
where i can find suitable server address
do i have to test all servers ?

**Comment by delphiassistant** [comment]
149.154.167.90 & 149.154.167.91 both worked for me.

**Comment by rashcms** [comment]
Yes, buy they only works with some numbers.
please test following number : 019706209143
it works with telegram web, but when i test it in Tlsharp it says : 
NETWORK_MIGRATE_1

**Comment by rashcms** [comment]
any suggestion ?

**Comment by sochix** [comment]
Maybe the telegram servers changed, try to see new values in TelegramSession properties.

**Comment by rashcms** [comment]
Unfortunately I cant find TelegramSession  properties.

**Comment by NetherX** [comment]
Be Careful, You Should Set Your Phone Number Like That  +(country code)(city or carrier code)(your number) in App Config.
Then Rebuild.
Notice : You Can Register Your Phone Number With 4 DC (Server Ip - Connection) , Not More

**Comment by JayDi85** [comment]
Telegram register phone number at one Data Center (DC). You can't use that number in another. When you try to login to wrong DC -- you got that error (NETWORK_MIGRATE_X -- there are X -- data center number). Change ip-address to other in config file.

Or you can write and send config-request to got data centers list for auto-change ip-address.

**Comment by sochix** [comment]
@NetherX  @JayDi85 Thanks for answering!
