### ISSUE TITLE
UploadFile

### ISSUE THREAD

**Issue by wolvewilson** [sochix/TLSharp#270]
I´m trying to send a chart through the telegram.
The chart component have a method that save a chart´s image into a memorystream.

Show can i send it with uploadfile method (it´s only accept StreamReader argument)?

**Comment by wolvewilson** [comment]
i´m trying to send it, but not having to save a file in a drive before send it.

**Comment by sochix** [comment]
Yep, it can be done. Basically you can convert pretty everything to Stream
