### ISSUE TITLE
How to find if message is read by receiver or not?

### ISSUE THREAD

**Issue by rukarimi** [sochix/TLSharp#274]
As you know, in web/mobile version we can sure if receiver read the sent message or not? Is there any method or class that help me in this issue so that I can update status of sent messages?

Also, I want to know how to use of "TLsharp.TL" classes? 
Please send me a windows application sample which use of important methods and classes of this project.

**Comment by timocov** [comment]
Just look at telegram [docs](https://core.telegram.org/method/messages.readHistory) ([request](https://github.com/sochix/TLSharp/blob/master/TeleSharp.TL/TL/Messages/TLRequestReadHistory.cs))

**Comment by rukarimi** [comment]
What's the input/output parameters ? would you please give an example how to use this method in application and show how to check status of a sent message/photo/video when user get it and when he read it?

**Comment by sochix** [comment]
You can't do it easily right now. It'll  be possible after we implememt Updates. See roadmap
