### ISSUE TITLE
request for windows application sample of this project

### ISSUE THREAD

**Issue by rukarimi** [sochix/TLSharp#275]
I want to know how to use of "TLsharp.TL" classes? 
Please send me a windows application sample which use of important methods and classes of this project.

**Comment by timocov** [comment]
[Here](https://github.com/sochix/TLSharp/blob/master/TLSharp.Tests/TLSharpTests.cs#L138) is a lot of examples (and [here](https://github.com/sochix/TLSharp/blob/master/README.md))

**Comment by rukarimi** [comment]
I review read me and guide file again ad again, but I think we can understand it better in a real win application.

**Comment by sochix** [comment]
Sorry, it's opensource project. I don't have time to do it for you. Try to read tests
