### ISSUE TITLE
TLVector serialization exception

### ISSUE THREAD

**Issue by timocov** [sochix/TLSharp#278]
Hi!

If generic type of `TLVector` is `TLObject` then body serialization fail with message "Object must implement IConvertible."
I guess in [TLVector.cs:84](https://github.com/sochix/TLSharp/blob/master/TeleSharp.TL/TLVector.cs#L84) should be `var res = (TLObject)(object)item;` (or something like that) or `TLObject` should implement `IConvertible`.

Related to #261

**Comment by sochix** [comment]
Will explore

**Comment by sochix** [comment]
@timocov Thanks for your pull-request!
