### ISSUE TITLE
Short example for sending documents

### ISSUE THREAD

**Issue by schlumpf90** [sochix/TLSharp#280]
Hi !

First of all thanks for your amazing work!

I want to send documents with TLSharp, but I don't understand the following line:

'await client.SendUploadedDocument(new TLInputPeerUser() { user_id = user.id }, fileResult, "Test","application/pdf", ???);'

In this example I want to send a PDF-file.
What about the last argument 'new TLVector<TLAbsDocumentAttribute>()); //document attributes, such as file name'

What's the meaning of this ? The filename is 'Test.pdf'
Could you please give a short example for sending PDF-files ??

Thanks a lot and with best regards,

Matthias

**Comment by schlumpf90** [comment]
Hi, it's me again.

I can send now PDF-files but I've now a little other problem.

As you can see in my screenshot the file is shown as an "unknown file" at the receiver.

What is my mistake / how can I get there the filename ????

Thanks a lot !!!!

![2016-10-31_154120](https://cloud.githubusercontent.com/assets/20926828/19858087/7d6db03e-9f80-11e6-93c8-af24b7db96aa.png)

**Comment by sochix** [comment]
Read telegram api docs carefully

31 окт. 2016 г. 17:43 пользователь "schlumpf90" <notifications@github.com>
написал:

**Comment by Duende1973** [comment]
Hello!!

I can send now EPUB-files but I've now a little other problem.

the file is shown as an "unknown file" at the receiver.

can you indicate in "telegram api docs" how result it? I do not see that.

Thank you

**Comment by schlumpf90** [comment]
Hi,

can you zip the EPUB-file and send it again ?!
How is the file shown at the receiver ?

**Comment by Duende1973** [comment]
If zip de epub-file, the same, file shown at the receiver "unknown file"
this is the code, with any mimetype, but each case file shown at the receiver "unknown file"

var TLDocumentAttributeFilename = await client.UploadFile(Path.GetFileName("Y:/Biblioteca de calibre/Isaac Asimov/Yo, robot (3951)/Yo, robot - Isaac Asimov.epub"), new StreamReader("Y:/Biblioteca de calibre/Isaac Asimov/Yo, robot (3951)/Yo, robot - Isaac Asimov.epub"));
                await client.SendUploadedDocument(
                    new TLInputPeerChannel() { channel_id = chat.id, access_hash = chat.access_hash.Value },
                    TLDocumentAttributeFilename, "","",new TLVector<TLAbsDocumentAttribute>());

                await client.SendUploadedDocument(
                    new TLInputPeerChannel() { channel_id = chat.id, access_hash = chat.access_hash.Value },
                    TLDocumentAttributeFilename, "Libro yo robot", "epub", new TLVector<TLAbsDocumentAttribute>());

                await client.SendUploadedDocument( 
                    new TLInputPeerChannel() { channel_id = chat.id, access_hash = chat.access_hash.Value },
                    TLDocumentAttributeFilename, "", "EPUB", new TLVector<TLAbsDocumentAttribute>());


                await client.SendUploadedDocument(
    new TLInputPeerChannel() { channel_id = chat.id, access_hash = chat.access_hash.Value },
    TLDocumentAttributeFilename, "", "application/EPUB+ZIP", new TLVector<TLAbsDocumentAttribute>());

                await client.SendUploadedDocument(
    new TLInputPeerChannel() { channel_id = chat.id, access_hash = chat.access_hash.Value },
    TLDocumentAttributeFilename, "", "application/EPUB", new TLVector<TLAbsDocumentAttribute>());

                await client.SendUploadedDocument(
    new TLInputPeerChannel() { channel_id = chat.id, access_hash = chat.access_hash.Value },
    TLDocumentAttributeFilename, "", "application/epub+zip", new TLVector<TLAbsDocumentAttribute>());

                await client.SendUploadedDocument(
new TLInputPeerChannel() { channel_id = chat.id, access_hash = chat.access_hash.Value },
TLDocumentAttributeFilename, "", "application/epub", new TLVector< TLAbsDocumentAttribute>());

**Comment by schlumpf90** [comment]
when sending a zip-file you have to use the mimetype "application/zip"

**Comment by Duende1973** [comment]
I use with de file zip, the mimetpye application/zip and the same result, unknown file.

**Comment by schlumpf90** [comment]
OK, then you have the same problem as I.
And I'm sorry: I have read the telegram api and tried and tried - but have no soution...

**Comment by Duende1973** [comment]
Ok, if I see the solution, tell you.

**Comment by schlumpf90** [comment]
@Duende1973 : any results ???
