### ISSUE TITLE
How to i can recieve Dialog Peer

### ISSUE THREAD

**Issue by TheBottleGit** [sochix/TLSharp#285]
![image](https://cloud.githubusercontent.com/assets/13104180/19954080/001097b6-a19f-11e6-9e09-47c1a887e771.png)
![image](https://cloud.githubusercontent.com/assets/13104180/19954094/234ce252-a19f-11e6-9d4d-ea3dc460376c.png)

Have this code, where i can get `TLInputPeerUser` in Dialogs for `TLRequestGetHistory`

**Comment by sochix** [comment]
Read Telegram Api docs

**Comment by TheBottleGit** [comment]
Ахуенный разработчик, прям сразу донат скинул.

**Comment by sochix** [comment]
Pavel think before type, pls. It s open source i shouldn't solve your problems.
