### ISSUE TITLE
get dialog

### ISSUE THREAD

**Issue by sinaprog** [sochix/TLSharp#288]
hi 
chats isn't define in TLDialog???
`

  //get user dialogs
  var dialogs = await client.GetUserDialogsAsync();

  //find channel by title
  var chat = dialogs.chats.lists
    .Where(c => c.GetType() == typeof(TLChannel))
    .Cast<TLChannel>()
    .FirstOrDefault(c => c.title == "<channel_title>");

  //send message
  await client.SendMessageAsync(new TLInputPeerChannel() { channel_id = chat.id, access_hash = chat.access_hash.Value }, "OUR_MESSAGE")`

**Comment by sochix** [comment]
Seems like you have problems with understanding Telegram API. Please read it carefully.

**Comment by RootAparat** [comment]
@sochix **sinaprog** is right. Look at this error: http://uploads.im/eNvtk.png

**Comment by hosseinGanjyar** [comment]
@sinaprog Hi. How I can connect to U? thanks
