### ISSUE TITLE
please i need your help

### ISSUE THREAD

**Issue by tsoftit** [sochix/TLSharp#29]
please can you help me to define InputMedia
I need to send photo then I need to define message content as inputmedia can you help me in this
thanks

**Comment by sochix** [comment]
Can you post here what you already have?

**Comment by tsoftit** [comment]
im try implement send photo in your TLsharp
im define new class call SendMediaRequest 
'-----------------------------
public class SendMediaRequest : MTProtoRequest
	{
		private InputPeer _peer;
		private InputMedia _message;
        
		public SendMediaRequest(InputPeer peer, InputMedia message)
		{
			_peer = peer;
			_message = message;
		}

		public override void OnSend(BinaryWriter writer)
		{
			long random_id =  Helpers.GenerateRandomLong();
			writer.Write(0xa3c85d76);
			_peer.Write(writer);
                        this._message.Write(writer);
			writer.Write(random_id);
        }
-----------------------------------------
and in class TelegramClient I implement this task
------------------------------------------
  public async Task SendMedia(int id, InputMedia message)
        {
            var request = new SendMediaRequest(new InputPeerContactConstructor(id), message);

            await _sender.Send(request);
            await _sender.Recieve(request);
        }
--------------------------------------
now I need send message photo
im try this
 BinaryReader kk = new BinaryReader(File.Open(@"C:\Users\TSOFT\Pictures\colors.jpg", FileMode.Open));
                InputMedia a = TL.Parse<InputMedia> (kk)  ;
                await client.SendMedia(res.Value,a);
but faild 
any help??

**Comment by tsoftit** [comment]
please  in this link
https://core.telegram.org/type/InputPhoto
I need how I obtain the value of ( id & access_hash ) to pass it to function where I need to send photo as I say in last

**Comment by dinhducit** [comment]
I facing same problem, @sochix Can you add features: send media, receive incoming message?

**Comment by sochix** [comment]
Yep I can,  but need a donation for it, because itsn't my main job
10 янв. 2016 г. 6:21 пользователь "Nguyen Dinh Duc" <
notifications@github.com> написал:

**Comment by dinhducit** [comment]
@sochix yes, I need your help, please!

**Comment by sochix** [comment]
@dinhducit send me your contact for private messaging

**Comment by dinhducit** [comment]
@sochix username of me on Telegram is @nguyendinhduc, pls contact with me via Telegram

**Comment by headria** [comment]
@ahmadheadri please help me to

**Comment by sochix** [comment]
Example of send media https://github.com/sochix/TLSharp#send-media-to-contact
