### ISSUE TITLE
PEER_FLOOD error while adding member to participaant

### ISSUE THREAD

**Issue by sinaprog** [sochix/TLSharp#293]
hi
I wrote this code to add member to supergroup 
but it returns "PEER_FLOOD" 
`
            var resuls = await client.GetContactsAsync();
            var uim = resuls.users.lists.Where(x => x.GetType() == typeof(TLUser)).Cast<TLUser>().FirstOrDefault(x => x.phone == "989016467352");

            MessageBox.Show(uim.id.ToString());
            MessageBox.Show(uim.access_hash.ToString());

            var dialogs = await client.GetUserDialogsAsync() as TLDialogs;
            var chat = dialogs.chats.lists.Where(c => c.GetType() == typeof(TLChannel)).Cast<TLChannel>().LastOrDefault(c => c.title == "گروه");

            MessageBox.Show(chat.id.ToString());
            MessageBox.Show(chat.access_hash.ToString());

            var inputuser = new TLInputUser() { access_hash = uim.access_hash.Value, user_id = uim.id };
            var users = new List<TLAbsInputUser>() { inputuser };
            var req2 = new TeleSharp.TL.Channels.TLRequestInviteToChannel() { channel = new TLInputChannel() { access_hash = chat.access_hash.Value, channel_id = chat.id },users=new TLVector<TLAbsInputUser> { lists=users  } };

            var ups = await client.SendRequestAsync <TLUpdates>(req2); `

**Comment by sochix** [comment]
It's Telegram restrictions. Read Telegram API

**Comment by sinaprog** [comment]
@sochix
I am new in c# 
May you help me with example

**Comment by sinaprog** [comment]
THIS API is outdated 
Is there newone?

**Comment by sochix** [comment]
> THIS API is outdated 
> Is there newone?

Sorry, no

**Comment by hosseinGanjyar** [comment]
https://github.com/sochix/TLSharp/issues/535
please see this

**Comment by hosseinGanjyar** [comment]
I solved this issue. please send your question in my group:
https://t.me/joinchat/HhLHow3Ed97A0gRZo7Ggog

**Comment by hosseinGanjyar** [comment]
Hi every body...You can ask your questions in this group:
https://t.me/joinchat/JRwh2w0A-7YlrMT_V4KhFQ

**Comment by hosseinGanjyar** [comment]
Hi every body...You can ask your questions in this group:
https://t.me/joinchat/JRwh2w0A-7YlrMT_V4KhFQ
