### ISSUE TITLE
Get TLObject parameters.

### ISSUE THREAD

**Issue by Pro-Ton** [sochix/TLSharp#298]
Hi,
I created a `TLRequestGetHistory()` request:

            var req = new TeleSharp.TL.Messages.TLRequestGetHistory()
            {
                peer = new TLInputPeerSelf(),
                limit = 5
            };

then got the response:
`            var msgs = await client.SendRequestAsync<TeleSharp.TL.Messages.TLMessagesSlice>(req);
`

and got the first `TLMessage` object:
`            var msg = msgs.messages.lists.First();
`

the `TLMessage` object is equivalent to the tl-scheme's `message` type, right?

Now, is it possible to get the message's parameters? For example the message text, or the ones mentioned here https://tjhorner.com/tl-schema/constructor/message?

Thanks

**Comment by sochix** [comment]
Heh, good question. I think it mostly question about Telegram Api, not TLSharp. So I can't help, sorry.

**Comment by Pro-Ton** [comment]
Well, generally speaking is it _possible_ via TLSharp or not?

**Comment by Pro-Ton** [comment]
Well, generally speaking, is it _possible_ via TLSharp or not?
Is there any relevant example in tests, etc.? 

Thanks again.

**Comment by sochix** [comment]
Yep it's definitely possible via TLSHarp. I recommend you to start from exploring tests

**Comment by Pro-Ton** [comment]
@sochix Thanks a lot, and sorry for duplicate message, I lost my internet connection the first time and github showed a message saying my comment couldn't be posted, but it was posted!  ¯\_(ツ)_/¯
