### ISSUE TITLE
Unit tests return error

### ISSUE THREAD

**Issue by delphiassistant** [sochix/TLSharp#3]
Hi. When i run unit tests i get this error:
TLSharp.Tests.NotificatioClientTests.AuthUser threw exception: 

System.IO.EndOfStreamException: Unable to read beyond the end of the stream.

All test methos except that AuthenticationWorks and TestConnection return same error.

I did every thing including setting api id and hash, and setting server address.

**Comment by sochix** [comment]
See this converstaion https://github.com/sochix/TLSharp/issues/1 , it definetily should help

**Comment by sochix** [comment]
Added info to start guide https://github.com/sochix/TLSharp/blob/master/README.md#sending-messages-set-up
