### ISSUE TITLE
API_ID_INVALID on second run

### ISSUE THREAD

**Issue by arlak** [sochix/TLSharp#30]
Hi. This is the code i'm using.

public static void Send(string message)
var store = new FileSessionStore();
var client = new TelegramClient(store, "session");
var connected = await client.Connect();
if (!client.IsUserAuthorized())
{
	var hash = await client.SendCodeRequest("+myponenumber");
	var code = "33219"; // you can change code in debugger

	var user = await client.MakeAuth("+myponenumber", hash, "33219");
}
var res = await client.ImportContact("@mychannel");

await client.SendMessage(res.Value, message);
}

When I run this function, I get this error:
[InvalidOperationException: API_ID_INVALID]
   TLSharp.Core.Network.MtProtoSender.HandleRpcResult(UInt64 messageId, Int32 sequence, BinaryReader messageReader, MTProtoRequest request) +983
   TLSharp.Core.Network.MtProtoSender.processMessage(UInt64 messageId, Int32 sequence, BinaryReader messageReader, MTProtoRequest request) +945
   TLSharp.Core.Network.<Recieve>d__8.MoveNext() +627
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +28
   TLSharp.Core.<SendCodeRequest>d__14.MoveNext() +538
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +28
   M***************TelegramSender.cs:61

I have set the _apiId and _apiHash values in telegram client with the values I have in https://my.telegram.org/apps
The number I'm using in SendCodeRequest is my number (app owner).

A weird thing is: when I run this function for the first time, the response returned on client.Connect() is good. But for the second time, I get the same API_ID_INVALID exception. But it's catched in MtProtoSender.HandleContainer

Please help

**Comment by tsoftit** [comment]
Change adress of server

**Comment by arlak** [comment]
I did. I set it to the Test configuration Ip address.

**Comment by arlak** [comment]
I'm trying today, and I got this error:

[InvalidOperationException: Ops, wrong size of input packet]
   TLSharp.Core.Network.TcpMessage.Decode(Byte[] body) in D:\Projects\AlMayadeenProjects\AlMayadeen.net\Releases\mayadeen-v1.8.0\sources\TLSharp.Core\Network\TcpMessage.cs:57
   TLSharp.Core.Network.<Receieve>d__6.MoveNext() in D:\Projects\AlMayadeenProjects\AlMayadeen.net\Releases\mayadeen-v1.8.0\sources\TLSharp.Core\Network\TcpTransport.cs:42
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +28
   TLSharp.Core.Network.<Recieve>d__8.MoveNext() in D:\Projects\AlMayadeenProjects\AlMayadeen.net\Releases\mayadeen-v1.8.0\sources\TLSharp.Core\Network\MtProtoSender.cs:131
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +28
   TLSharp.Core.<SendCodeRequest>d__14.MoveNext() in D:\Projects\AlMayadeenProjects\AlMayadeen.net\Releases\mayadeen-v1.8.0\sources\TLSharp.Core\TelegramClient.cs:82
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +28
   *******\TelegramSender.cs:62

**Comment by sochix** [comment]
`var res = await client.ImportContact("@mychannel");` It will not work sorry

**Comment by shabahang4u** [comment]
I have same error API_ID_INVALID in 2 different account new created using tlsharp, but in my old account tlsharp works perfect, I changed server address to test and production IP or { 1, "149.154.175.50", 443 },	{ 2, "149.154.167.51", 443 },{ 3, "149.154.175.100", 443 },{ 4, "149.154.167.91", 443 },	{ 5, "149.154.171.5", 443 } but not result. please help me to resolve this problem. thanks 4 your attention.
