### ISSUE TITLE
HTML5

### ISSUE THREAD

**Issue by mohhsen67** [sochix/TLSharp#302]
Does TLSharp have anything for Telegram Gaming Platform?
I need sending HTML5 to Telegram from C#.

**Comment by Pro-Ton** [comment]
The gaming platform is designed for bots, so if you want to use it you should check telegram's official document on Bot API.
And you don't send anything in HTML5 to telegram in the game platform, you just send a link to you game which is hosted on your own server, and telegram just opens the link on the system's default web browser. it just allows you to do some simple interactions e.g. save scores etc.

**Comment by mohhsen67** [comment]
As you know, Telegram has introduced its Gaming Platform recently which supports HTML5. I developed a WinForms application. You know that Kendo UI supports HTML5, too. My question is that, is it possible to build an HTML5 page using Kendo UI and then render it into Telegram?

Actually, since Telegram supports HTML5 from now on and since Kendo UI supports HTML5, so I want to make some HTML5 pages (Specially GridView) and load them into Telegram and users can interact with my WinForms application using their Telegram app.

If you have any idea about this, please help.

Thanks in advance

**Comment by Pro-Ton** [comment]
No, you can't do this using the Telegram Gaming Platform, please see bots that are currently using this feature (like @gamee) it just opens a link in the browser. That's it.
