### ISSUE TITLE
Error using TLRequestGetHistory CHANNEL_INVALID

### ISSUE THREAD

**Issue by sergiohj** [sochix/TLSharp#313]
Hi,

I'm trying to gather the channel history but I'm not sure if I'm doing something wrong or there is an issue. I'm using the request TLRequestGetHistory sending a TLInputChannel with an Id that I have gathered before using the method GetUserDialogsAsync. I use the property id in TLChannel to call to the TLRequestGetHistory but I'm always receiving the same error.

Could you help me with this issue and gather all the history chat of a channel?

Regards.

**Comment by pooyaco** [comment]
TeleSharp.TL.Messages.TLRequestGetHistory request = new TeleSharp.TL.Messages.TLRequestGetHistory();
                request .peer = new TeleSharp.TL.TLInputPeerChannel { access_hash = xxxxxxx, channel_id = xxxxx };
                request .max_id = -1;
                request .limit = -1;
                var message = await client.SendRequestAsync<TeleSharp.TL.Messages.TLChannelMessages>(request );

see https://core.telegram.org/method/messages.getHistory

**Comment by sergiohj** [comment]
Thanks, I'm able to gather the history chat.

Regards.
