### ISSUE TITLE
sending message work in runtime c#.net project but doesn't work in published project

### ISSUE THREAD

**Issue by mersi77** [sochix/TLSharp#314]
Is there any way to overcome this issue?

**Comment by knocte** [comment]
What does `doesn't work` mean exactly? Be more specific please.

**Comment by mersi77** [comment]
when I run the project in visual studio 2015 IDE, after pressing the related button, it sends corresponding message to specific number in telegram, but when I publish the project and run it from IIS, pressing that button does not do anything.

**Comment by knocte** [comment]
As you're using IIS, I'm using you're using ASP.NET. Please configure your ASP.NET application to log any exceptions that it catches, so that you can look for the exact error.

**Comment by mersi77** [comment]
I couldn't fine useful something in the IIS log files!

**Comment by knocte** [comment]
That's why you have to configure the ASP.NET yourself, or maybe look for it in the event log.
