### ISSUE TITLE
Get user ID by username?

### ISSUE THREAD

**Issue by gmardok** [sochix/TLSharp#315]
How can I get user_id if I have only username and it is not in contact list?

**Comment by sochix** [comment]
You can try to search via Telegram API's. I don't know exact method, but i think its possible. Try to explore a bit TLSchema methods

**Comment by gmardok** [comment]
There is no such info in API doc and I cannot find it in TLSharp also. Basically I need this to be able to search user by username and add to group chat or channel. It is possible to try to see how it works in web version but I don't know how to get readable version of such request:
íîì¡u×J¹&j÷`ëÈ¡°sû Nè8eÔI­4WrÀÛ~ÐV)Zb>ºÃ¯Òï©Û[Ò:±&ozÅc+;©µâK.Ë/r¿k¾MÌn´~Ý07^ÂäT!hÿòa(C>ö_nX2çý¤r]ÚñP

**Comment by sochix** [comment]
Check web version source code, and find what methods they call to get search working

**Comment by gmardok** [comment]
Thanks, I'll try and will make PR in case of success.
