### ISSUE TITLE
Implementation of downloading a contact's photo

### ISSUE THREAD

**Issue by zerodwide** [sochix/TLSharp#32]
hi, before i point out the my problem, i appreciating developers for this nice and clean api code!

## MY QUESTION 1: 
what i have to set for offset and limit? i don't know photo size! to use it in offset!!!
 i know i can use that for chunked download , part by part, but if i wont like to download chunked file
can i set 0, 0 for both?
 i did that and i got this respone:

type =>>  {(storage_fileJpeg)}
mtime =>> 1446716047 
bytes =>> {byte[9484]}

## MY QUESTION 2:
how i can see the photo from {byte[9484]}?

i used this code:

using (var ms = new MemoryStream(byteArrayIn))
{
	return new Bitmap(ms);
}

and set that return for a PictureBox.Image

but it return exception with: Invalid Parameter!
(it says that the byte format is not correct for Bitmap).

* hint:
because i have not offset and limit, i changed some part of code in GetFileRequest:

  public override void OnResponse(BinaryReader reader)
        {
            var code = reader.ReadUInt32(); // upload.file#96a18d5
            
            type = TL.Parse<storage_FileType>(reader);
            mtime = reader.ReadInt32();
             bytes = reader.ReadBytes(int.Parse((reader.BaseStream.Length - reader.BaseStream.Position).ToString()));
	}

thanks in advance!

**Comment by XyLoNaMiyX** [comment]
Hello! I've implemented this in my other repository https://github.com/LonamiWebs/Telebackup. You may want to have a look.
For more information consider reading https://core.telegram.org/api/files where it specifies:

    part_size % 1024 = 0 // (divisible by 1KB)
    524288 % part_size = 0 // (512KB must be evenly divisible by part_size)

So, in answer to your first question, you download n bytes (let's say 512kb) at once, and the next time you make the request, specify a 512kb offset and download another 512kb. When you don't receive more bytes, you'll know the transfer has finished.

Google has great answers for your second question, just look for _Image from byte array_

**Comment by sochix** [comment]
@XyLoNaMiyX it'll be wonderfull if you can made a pull-request with this changes.

**Comment by XyLoNaMiyX** [comment]
@sochix it is still a very work in progress and contains many bugs. Some people tested but either the program didn't load or it quickly crashed. I'm still working to find out which issues can causing this.

**Comment by zerodwide** [comment]
@XyLoNaMiyX  thank you so much, i'll work on that
