### ISSUE TITLE
Sending message works when I run the project in visual studio IDE, but doesn't work when publish on IIS

### ISSUE THREAD

**Issue by mersi77** [sochix/TLSharp#326]
Is there anybody to help?

**Comment by knocte** [comment]
Is this issue a duplicate of https://github.com/sochix/TLSharp/issues/314 ?

**Comment by sochix** [comment]
@mersi77 I bet problem in storage on IIS. It just can't save session.dat

**Comment by mersi77** [comment]
What can I do to solve this problem?

**Comment by mersi77** [comment]
Is it possible to change the location of session.dat?
