### ISSUE TITLE
 Please Fix Errors Library

### ISSUE THREAD

**Issue by Ansel1990B** [sochix/TLSharp#330]
The library is very error to communicate with telegram

Please fix these problems

The errors is repeated

Errors List:
1.Can't decode packet

2.msg_seqno too low (the server has already received a message with a lower msg_id but with either a higher or an equal and odd seqno

3.USER_DEACTIVE

4.Couldn't read the packet length

5.Couldn't read the crc

**Comment by knocte** [comment]
This is an opensource library, therefore the only way to make it better is either by contributing the bugfixes yourself or donating to keep the project going.

Please report each different problem in a separate issue, not all of them together.

**Comment by sochix** [comment]
Thanks @knocte
