### ISSUE TITLE
remove user from channel

### ISSUE THREAD

**Issue by RexProg** [sochix/TLSharp#333]
how can i remove user from channel?

**Comment by Ansel1990B** [comment]
To do this, use TLRequestKickFromChannel

**Comment by RexProg** [comment]
excuse me
would you please write an example for it?

**Comment by hadi77ir** [comment]
Just read Telegram for Android code. In its MessageController.java it has everything you need for managing channels.

(NOTE: A channel is a chat which has more than 2 participants, you may call it a group, a megagroup or a broadcast. Broadcasts are recently called channels, which is incorrect when it comes to API.)
