### ISSUE TITLE
please any example #c or vb.net please for send msg to number not on my contact

### ISSUE THREAD

**Issue by elmagekmosaad** [sochix/TLSharp#338]
please any example #c or vb.net please for send msg to number not on my contact

**Comment by elmagekmosaad** [comment]
هل تمتلك فيس بوك؟
did you have facebook account?

2016-12-13 15:45 GMT+02:00 m0rtal123 <notifications@github.com>:

**Comment by sochix** [comment]
See https://github.com/sochix/TLSharp/issues/340
