### ISSUE TITLE
How get more than 100 messages on TLRequestGetHistory 

### ISSUE THREAD

**Issue by meysam-mo** [sochix/TLSharp#347]
I want to read all messages from a MegaGroup withTLRequestGetHistory on C# with TLSharp library. Everything is ok but it just returns the last 100 messages.

my code for send request:

```
var req = new TLRequestGetHistory
        {
            add_offset = 0,
            limit = Int32.MaxValue,
            peer = new TLInputPeerChannel{ channel_id = **, access_hash = **}
        };
```

How can I read more messages?

**Comment by meysam-mo** [comment]
solved

**Comment by eaba** [comment]
@meysam-mo how did you solve this issue?
Post code sample

**Comment by meysam-mo** [comment]
`int total = 1;
int start = 0;
int end = 100;
while (start <= total)
{
var req = new TLRequestGetHistory
{
        add_offset = start,
         limit = end,
          peer = new TLInputPeerChannel { channel_id = 000 , access_hash = 0000}
};
TLChannelMessages messages = await client.SendRequestAsync<TLChannelMessages>(req);
total = messages.count;
foreach (var channelMessage in messages.messages.lists.OfType<TLMessageService>())
{
       //Your code here
}
start+=101;
}`

**Comment by hosseinGanjyar** [comment]
How use of media into message?

**Comment by hosseinGanjyar** [comment]
@meysam-mo  How crawl most of 100 posts without flood_wait?

**Comment by hosseinGanjyar** [comment]
I solved this issue. please send your question in my group:
https://t.me/joinchat/HhLHow3Ed97A0gRZo7Ggog

**Comment by hosseinGanjyar** [comment]
@meysam-mo Do you have any solution for **get more dialogs than 100**?
same this: https://github.com/sochix/TLSharp/issues/696
