### ISSUE TITLE
send a message to special number

### ISSUE THREAD

**Issue by fatemehramezani** [sochix/TLSharp#35]
Can you put real example. I want to send message to special number which I do not know the telegram's ID! I write this code but it does not work:
static void Main(string[] args)
        {
            try
            {
                Console.WriteLine("Start:");
                Task.Run(() => Send("Hi"));
                Task.Run(() => SendMessage());
                Console.WriteLine("End");
                Console.ReadLine();
            }
            catch (Exception ex)
            {
            }
        }

        public static async Task AuthUser()
        {

            var store = new FileSessionStore();
            var client = new TLSharp.Core.TelegramClient(store, "session");

            await client.Connect();

            var hash = await client.SendCodeRequest("+phone");
            var code = "59149"; // you can change code in debugger

            var user = await client.MakeAuth("+phone", hash, code);

            Assert.IsNotNull(user);
        }

        public static async Task CheckPhones()
        {
            var store = new FileSessionStore();
            var client = new TLSharp.Core.TelegramClient(store, "session");
            await client.Connect();

            var phoneList = new string[]
            {
                "+phone",
                "+phone"
            };

            var rand = new Random();
            foreach (var phone in phoneList)
            {
                var result = await client.IsPhoneRegistered(phone);
                Thread.Sleep(rand.Next(9) * 1000);
                if (result)
                    Console.WriteLine($"{phone} - OK");
            }
        }

        public static async Task ImportContact()
        {
            // User should be already authenticated!

            var store = new FileSessionStore();
            var client = new TLSharp.Core.TelegramClient(store, "session");

            await client.Connect();

            Assert.IsTrue(client.IsUserAuthorized());

            var res = await client.ImportContact("@IrisTed");

            Assert.IsNotNull(res);

        }

        public static async Task SendMessage()
        {
            // User should be already authenticated!

            var store = new FileSessionStore();
            var client = new TLSharp.Core.TelegramClient(store, "session");
            await client.Connect();

            Assert.IsTrue(client.IsUserAuthorized());

            var res = await client.ImportContact("+phone");

            Assert.IsNotNull(res);

            await client.SendMessage(res.Value, "Test message from TelegramClient");
        }

        public static async Task TestConnection()
        {
            var store = new FakeSessionStore();
            var client = new TLSharp.Core.TelegramClient(store, "");

            Assert.IsTrue(await client.Connect());
        }

        public static async Task AuthenticationWorks()
        {
            using (var transport = new TcpTransport())
            {
                var authKey = await Authenticator.DoAuthentication(transport);

                Assert.IsNotNull(authKey.AuthKey.Data);
            }
        }

        public static async Task Send(string message)
        {
            var store = new FileSessionStore();
            var client = new TLSharp.Core.TelegramClient(store, "session");
            var connected = await client.Connect();
            if (!client.IsUserAuthorized())
            {
                var hash = await client.SendCodeRequest("+phone");
                var code = "35828"; // you can change code in debugger

                var user = await client.MakeAuth("+phone", hash, code);
            }
            var res = await client.ImportContact("@IrisTed");

            await client.SendMessage(res.Value, message);
        }

**Comment by zerodwide** [comment]
the procedure is not this simple u think, you should first read whole telegram official  api , after that you will find out what to do. 

for already written requested functionality you could donate, else code it !

**Comment by sochix** [comment]
@fatemehramezani what you mean by *special number*?

**Comment by GeneratorEVil** [comment]
sochix Привет. Подскажи сегодня утром написал код 

 private async void telegramAuthToolStripMenuItem_Click(object sender, EventArgs e)
        {
            cTLSender tlsSndC = new cTLSender();

            await tlsSndC.AuthUser();

        }

cTLSender - это твой TESTS класс и проекта



 public async Task AuthUser()
        {

            var store = new FileSessionStore();
            var client = new TelegramClient(store, "session", apiId, apiHash);
          
            await client.Connect(); // коннект проходит
          
            var hash = await client.SendCodeRequest(NumberToAuthenticate); // а тут висит долго и ничего в ответ 

            TlCodeForm tlCode = new TlCodeForm();
            tlCode.MdiParent = MdiParent.Instance;
            tlCode.Show();


            Stopwatch s = new Stopwatch();
            s.Start();
            int seconds = 20;
            while (s.Elapsed < TimeSpan.FromSeconds(seconds))
            {
                tlCode.timerLabel.Text = "Проверить (" + (TimeSpan.FromSeconds(seconds) - s.Elapsed).Seconds.ToString() + ")";
                Application.DoEvents();
            }
            s.Stop();


            string code = "";
            code = tlCode.codeText.Text;
            if (code.Length == 0) return;
            var user = await client.MakeAuth(NumberToAuthenticate, hash, code);
            Assert.IsNotNull(user);
        }

При всем при этом утром. Все работало и сообщения отправлялись. А в течения дня висит то на коннекте , то на получения hash. 

Пробовал менять ip в session . Пару раз ругался что я не на том dc.
