### ISSUE TITLE
Problems with session.dat file

### ISSUE THREAD

**Issue by ridicoulous** [sochix/TLSharp#351]
I'm host my solution at Microsoft Azure Web Apps and I have an exception "Access to the path 'D:\Windows\system32\session.dat' is denied.". Could I can change a destination of this file?

**Comment by mersi77** [comment]
public class WebSessionStore : ISessionStore
{
	public void Save(Session session)
	{
		var file = HttpContext.Current.Server.MapPath("/App_Data/{0}.dat");

		using (FileStream fileStream = new FileStream(string.Format(file, (object)session.SessionUserId), FileMode.OpenOrCreate))
		{
			byte[] bytes = session.ToBytes();
			fileStream.Write(bytes, 0, bytes.Length);
		}
	}

	public Session Load(string sessionUserId)
	{
		var file = HttpContext.Current.Server.MapPath("/App_Data/{0}.dat");

		string path = string.Format(file, (object)sessionUserId);
		if (!File.Exists(path))
			return (Session)null;

		var buffer = File.ReadAllBytes(path);
		return Session.FromBytes(buffer, this, sessionUserId);
	}
}

FROM SALARCODE

**Comment by ridicoulous** [comment]
Thank you, it works. But in Microsoft Azure it must be an absolute path, like this HttpContext.Current.Server.MapPath("~/App_Data/{0}.dat");

**Comment by aliasadi82** [comment]
how to use that code?

**Comment by barsham** [comment]
Something like below:

var client = new TelegramClient(apiId, apiHash, new WebSessionStore());

**Comment by aliasadi82** [comment]
Thanks a lot.
It works.
