### ISSUE TITLE
How can I download a photo (not a file)?

### ISSUE THREAD

**Issue by sresoft** [sochix/TLSharp#352]
Hi. I'm using the code you wrote in the description for downloading files, but I cannot get it to work for photos. What should I do?

 await client.GetFile(
                new TLInputDocumentFileLocation()
                {
                    access_hash = document.access_hash,
                    id = document.id,
                    version = document.version
                },
                document.size); //size of fileChunk you want to retrieve

**Comment by knocte** [comment]
`Cannot get it to work` is too ambiguous. Please state the specific problem you have. Any error? exception? what?

**Comment by sresoft** [comment]
thanks. I fixed the problem. now when I want to download multiple photos, after a while i get this error:
"Can't decode packet problem"

here is my code:

am I doing something wrong?

```
var inputPeer = new TLInputPeerUser() { user_id = user.id };
            var res = await client.SendRequestAsync<TLMessagesSlice>(new TLRequestGetHistory() { peer = inputPeer,limit=200 });
            var photos = res.messages.lists
                .OfType<TLMessage>()
                .Where(m => m.media != null)
                .Select(m => m.media)
                .OfType<TLMessageMediaPhoto>()
                .Select(md => md.photo)
                .OfType<TLPhoto>();
                

            foreach (TLPhoto ph in photos)
            {
                var photoSize = ph.sizes.lists.OfType<TLPhotoSize>().Last();
                TLFileLocation tf = (TLFileLocation)photoSize.location;

                var resFile = await client.GetFile(new TLInputFileLocation
                {

                    local_id = tf.local_id,
                    secret = tf.secret,
                    volume_id = tf.volume_id
                }
                    ,
                    0);

                FileStream fs = new FileStream("e:\\bk\\"+DateTime.Now.Ticks+".jpg", FileMode.OpenOrCreate);
                StreamWriter sw = new StreamWriter(fs);
                fs.Write(resFile.bytes, 0, resFile.bytes.Length);
                fs.Flush();
                fs.Close();
            }
```

**Comment by knocte** [comment]
> thanks. I fixed the problem.

Why don't you give more details about it so that the next developer that suffers it can fix it?

> now when I...

Open a new issue for a different problem, this is not a forum.

> "Can't decode packet problem"

Please post the whole stacktrace (but in a new issue, I'm closing this one).

**Comment by sresoft** [comment]
> Why don't you give more details about it so that the next developer that suffers it can fix it?
the code above is the solution.

**Comment by barsham** [comment]
I have just change the last portion of your code to cast the byte array to image then save to disk.

From:

 FileStream fs = new FileStream("e:\\bk\\"+DateTime.Now.Ticks+".jpg", FileMode.OpenOrCreate);
                StreamWriter sw = new StreamWriter(fs);
                fs.Write(resFile.bytes, 0, resFile.bytes.Length);
                fs.Flush();
                fs.Close();

To:
using (var ms = new MemoryStream(file.bytes))
                    {
                        Image.FromStream(ms).Save("e:\\bk\\"+DateTime.Now.Ticks+".jpg");
                    }

**Comment by moslem7026** [comment]
how  about png or gif ?

**Comment by amirvenus** [comment]
I used your code that you said is a fix but I am getting Could not read packet error.

` var sd = mm.Message.ToList().OfType<TLMessage>().Where(m => m.Media != null)
                                                .Select(m => m.Media).OfType<TLMessageMediaPhoto>()
                                                .Select(md => md.Photo)
                                                .OfType<TLPhoto>();
                                    foreach (TLPhoto ph in sd)
                                    {

                                        try
                                        {
                                            var photoSize = ph.Sizes.ToList().OfType<TLPhotoSize>().Last();
                                            TLFileLocation tf = (TLFileLocation)photoSize.Location;

 var resFile = await tclient.GetFile(new TLInputFileLocation
                                            {

                                                LocalId = tf.LocalId,
                                                Secret = tf.Secret,
                                                VolumeId = tf.VolumeId
                                            }
                                                ,
                                                0);

                                            using (var ms = new MemoryStream(resFile.Bytes))
                                            {
                                                Image.FromStream(ms).Save(DateTime.Now.Ticks + ".jpg");
                                                Console.WriteLine("bp");
                                            }
                                        }
                                        catch (Exception ex)
                                        {
                                            Console.WriteLine(ex.Message);
                                        }
                                    }`
