### ISSUE TITLE
i need help for using TLRequestForwardMessage

### ISSUE THREAD

**Issue by behzadsadeghi94** [sochix/TLSharp#366]
hi my dear friends. first of all I want to thank you for TLSharp. 
how can i forward a message on TLRequestForwardMessage to group or channels?

await api.SendRequestAsync<TLAbsUpdates>(new TLRequestForwardMessage()
                                    {
                                        peer = new TLInputPeerChannel() { channel_id = chat.id, access_hash =       chat.access_hash.Value },
                                        random_id = TLSharp.Core.Utils.Helpers.GenerateRandomLong(),
                                        MessageId=myTLMessageObj.id
 });

where is my mistake?

**Comment by hagilani** [comment]
hello behzad, are you solve problem?
can you send code to me?
