### ISSUE TITLE
Flaw in TeleSharp.TL

### ISSUE THREAD

**Issue by hadi77ir** [sochix/TLSharp#370]
There is a design flaw in your TL implementation. (probably because of generator)
They don't have proper support for polymorphism and takes none of inheritance goods. For example: While all child classes of TLAbsChat have "id" property, it has NO property in itself. So I have to check its type and cast it 6 times.

Please fix this problem, or this library will be unusable.

Thanks.

**Comment by knocte** [comment]
> While all child classes of TLAbsChat have "id" property, it has NO property in itself.

Thanks for filing a bug @hadi77ir, we appreciate the feedback.

> Please fix this problem, or this library will be unusable.

I'm sad if this problem makes the library unusable to you :-(

If that's the case, you should probably invest time to propose a pull request to fix it (I'm sure it would take you less time than writing a new Telegram library for .NET from scratch :) ).

**Comment by hadi77ir** [comment]
I'm currently relying on this project for rewriting critical parts of Telegram for Android in C#,
I "would" invest some time after I made my app work.
Currently, I found Reflection to be the best solution until TLGenerator gets fixed.

For example: To use reflection for reading properties, you can use `X.GetType().GetProperty("id").GetValue(X)` where `X` is your object and `id` is your property name.
