### ISSUE TITLE
How to implementation of "GetHistoryAsync" ?

### ISSUE THREAD

**Issue by romi4rd1** [sochix/TLSharp#376]
How to implementation of "GetHistoryAsync" ?

**Comment by knocte** [comment]
I don't understand the question

**Comment by romi4rd1** [comment]
i mean is how to handle result of that Method?

**Comment by knocte** [comment]
In the same way as the other methods? What's your issue?

**Comment by Roganik** [comment]
Try to cast result of GetHistoryAsync to TLChannelMessages 
then you can cast TLAbsMessage to TLMessage.

```
 var messages = await Client.GetHistoryAsync(peer, 0, 0, 1);
            var channelMessages = messages as TLChannelMessages;
            if (channelMessages != null)
            {
                foreach (TLAbsMessage message in channelMessages.messages.lists)
                {
                    var tlMessage = message as TLMessage;
                    if (tlMessage != null)
                    {
                        //do stuff with message
                    }
                }
            }
```

**Comment by romi4rd1** [comment]
Solved!
Thanks for all, finally I'm able to gather the history chat.

**Comment by Kazem-ma79** [comment]
Hi
How to get just unread messages ? Using this code but getting all messages except new ones:
`var peer = dia.Peer as TLPeerUser;
                        var chat = dialogs.Users.ToList().OfType<TLUser>().First(x => x.Id == peer.UserId);
                        var inputPeer = new TLInputPeerUser() { UserId = chat.Id, AccessHash = chat.AccessHash.Value };
                        var hist = await client.GetHistoryAsync(inputPeer, 0, -1, dia.UnreadCount) as TLMessagesSlice;
                        if (hist != null)
                            foreach (var m2 in hist.Messages.ToList())`
