### ISSUE TITLE
TLRequestGetDialogs returns only 100 chats

### ISSUE THREAD

**Issue by Hamcker** [sochix/TLSharp#383]
`TLRequestGetDialogs` returns only 100 chats even when the `limit` is set to 1000.

**Comment by ayazzali** [comment]
look at https://github.com/sochix/TLSharp/issues/347

**Comment by Hamcker** [comment]
@ayazzali completely different problems!

**Comment by NaderStar** [comment]
any solutions ?

**Comment by knocte** [comment]
I think this was fixed here: f2a394ea15d14a5482cd815c4b5c2b9c672abf0e

**Comment by Hamcker** [comment]
yes it is, I'll thank you 2 years later :)
