### ISSUE TITLE
No Wiki section in Repository

### ISSUE THREAD

**Issue by hadi77ir** [sochix/TLSharp#389]
Please enable the wiki section, so we can contribute to it by documenting the API and TLSharp.

And also add this text to README.Md:
`If you want to know how to do X, look at tests, wiki or Telegram for Android, and please do not make an issue. Issues are only for bug reporting and feature requests.`

**Comment by knocte** [comment]
> Please enable the wiki section

Not sure I like that idea, because I think wikis in github cannot receive pull requests?
So, maybe it's enough with using inline XML documentation in the public members.

> And also add this text to README.Md:

You can propose changes to README via pull request.
