### ISSUE TITLE
doesn't create session.dat file

### ISSUE THREAD

**Issue by sarazs** [sochix/TLSharp#40]
hi 
i execute tutorial step by step, when i run testConnection test function 
but doesn't create session.dat 
actually i set breakpoint step by step, when reach Receieve function in tcpTransport.cs file suddenly exit and close program,
when run AuthUser function and set breakpoint on "var code = "123"" never reach this line and exit from program
why?
tnx

**Comment by NetherX** [comment]
Test Connection Doesn't Create Session.dat File. You Should Check Your Ip Server and Phone Numbers In App.config.

**Comment by sarazs** [comment]
i checked these server:
Server 1: 149.154.175.50:443
Server 2: 149.154.167.51:443
Server 3: 149.154.175.100:443
Server 4: 149.154.167.91:443
Server 5: 91.108.56.165:443
server 6:149.154.167.40:443
server 7:149.154.167.50:443

and set phone numbers in app.configs but doesn't work,
how can i create Session.dat file?

**Comment by sochix** [comment]
Now automatically select DC, so problem should disappear.
