### ISSUE TITLE
error in session.dat path

### ISSUE THREAD

**Issue by aliasadi82** [sochix/TLSharp#400]
Error after publish web application in the host:
Access to the path 'c:\windows\system32\inetsrv\session.dat' is denied.
How can I solve it?

**Comment by barsham** [comment]
Solution 1:
https://github.com/sochix/TLSharp/issues/351
Solution 2:
Provide enough access to IIS Application Pool User to be able to create that file in the folder.

PS: session.dat is like a token of user after authentication.

**Comment by blacklabelmee** [comment]
@aliasadi82  i managed to solved this problem by running visual studio as administrator .

**Comment by barsham** [comment]
@blacklabelmee The error is after publish not during debug.
I assume the user which runs the Visual Studio is using your admin account although deployment can happen on any server with any user.

**Comment by aliasadi82** [comment]
Thank you @barsham 
i have solved this problem with this Solution: [#351](https://github.com/sochix/TLSharp/issues/351)
