### ISSUE TITLE
Using tlsharp on web application

### ISSUE THREAD

**Issue by rd1975** [sochix/TLSharp#41]
Hi
This wrapper work fine on win app.
Can i use this wrapper on web application or web service?
I tested, but can't work. stop on client.Connect() method!
Thanks

**Comment by sochix** [comment]
Yep, it should work. Please paste your source code snippet here.

**Comment by rd1975** [comment]
Hi sochix, Thanks for reply
I use same method in win & web app, but on web app this line: "await client.Connect();" exit code happening

var store = new FileSessionStore();
var client = new TLSharp.Core.TelegramClient(store, "session");
await client.Connect();
if (client.IsUserAuthorized())
{
          var res = await client.ImportContact("any number");
          await client.SendMessage(res.Value, "Test Telegram Web");
}

**Comment by sochix** [comment]
Check the path at which yout try to save session.dat, maybe it's not
available for web project. Try to use another SessionStore.

2015-12-22 11:31 GMT+03:00 rd1975 <notifications@github.com>:

> Hi sochix, Thanks for reply
> I use same method in win & web app, but on web app this line: "await
> client.Connect();" exit code happening
>
> var store = new FileSessionStore();
> var client = new TLSharp.Core.TelegramClient(store, "session");
> await client.Connect();
> if (client.IsUserAuthorized())
> {
> var res = await client.ImportContact("any number");
> await client.SendMessage(res.Value, "Test Telegram Web");
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sochix/TLSharp/issues/41#issuecomment-166552719>.
>



-- 
Best regards, Ilya (http://sochix.ru)
С уважением, Илья (http://sochix.ru)
