### ISSUE TITLE
Помогите разобраться с  SendRequestAsync

### ISSUE THREAD

**Issue by lih1989** [sochix/TLSharp#411]
Привет всем!
Я начинающий разработчик, и у меня порой много глупых вопросов.
Ну не понимаю я как использовать другие методы при помощи этой библиотеки.
Имеется пример:
```
` //Create request 
  var req = new TLRequestSetTyping()
  {
    action = new TLSendMessageTypingAction(),
    peer = peer
  };

  //run request, and deserialize response to Boolean
  return await SendRequestAsync<Boolean>(req);`

```
но хоть убейте не понимаю что и откуда берется.

Например мне нужно сделать регистрацию пользователя.
Имеем метод auth.signUp
Насколько понимаю нужно использовать TLRequestSignUp
Но как?( Не понимаю...
**Объясните пожалуйста!**

**Comment by ridicoulous** [comment]
Вдумчиво посмотри на работу этих методов у себя локально и все прояснится:
https://github.com/sochix/TLSharp/blob/master/TLSharp.Tests/TLSharpTests.cs

**Comment by lih1989** [comment]
> Вдумчиво посмотри на работу этих методов у себя локально и все прояснится:
> https://github.com/sochix/TLSharp/blob/master/TLSharp.Tests/TLSharpTests.cs

Спасибо!
углядел:
```
            var client = NewClient();
            await client.ConnectAsync();

            var hash = await client.SendCodeRequestAsync(NotRegisteredNumberToSignUp);
            var code = "";

            var registeredUser = await client.SignUpAsync(NotRegisteredNumberToSignUp, hash, code, "TLSharp", "User");
            Assert.IsNotNull(registeredUser);
            Assert.IsTrue(client.IsUserAuthorized());

            var loggedInUser = await client.MakeAuthAsync(NotRegisteredNumberToSignUp, hash, code);
            Assert.IsNotNull(loggedInUser);
```

**Comment by ridicoulous** [comment]
Будь здоров. Закрывай issue


> 1 марта 2017 г., в 13:00, lih1989 <notifications@github.com> написал(а):
> 
> await
