### ISSUE TITLE
join to group via link

### ISSUE THREAD

**Issue by parsibox** [sochix/TLSharp#413]
hi
how can i join to group via join link?
which methods i need to call?

**Comment by emadgha** [comment]
hi
can you find anyway?

**Comment by haririan** [comment]
just change your channel to private and copy the link then change back it to public

**Comment by hagilani** [comment]
@parsibox  تونستید مشکلو حل کنید؟

**Comment by wecanco** [comment]
https://github.com/sochix/TLSharp/issues/591
