### ISSUE TITLE
How to get channels description

### ISSUE THREAD

**Issue by iarash84** [sochix/TLSharp#416]
Hi

I want to get channels description
 is there a way that help me for do this job ??

**Comment by iarash84** [comment]
i use this code below to get user information but object (TLUser) doesn't have description property

                var contacts = await _client.GetContactsAsync();
                var user = contacts.users.lists
                    .Where(x => x.GetType() == typeof(TLUser))
                    .OfType<TLUser>()
                    .FirstOrDefault(x => x.username == userName.TrimStart('@'));

**Comment by iarash84** [comment]
i solve it my self by this code

            var req = new TLRequestGetFullChannel
            {
                channel = new TLInputChannel
                {
                    channel_id = channelId,
                    access_hash = accessHash
                },
            };
            var res = await _client.SendRequestAsync<TeleSharp.TL.Messages.TLChatFull>(req);
            var tlChanelFull = (TLChannelFull) res.full_chat;
	    tlChanelFull.about;

**Comment by hosseinGanjyar** [comment]
@iarash84 thanks, I've got a error:

> 'Unable to cast object of type 'TeleSharp.TL.Messages.TLChannelMessages' to type 'TeleSharp.TL.Messages.TLChatFull'.'

line: 
`var res = await _client.SendRequestAsync<TeleSharp.TL.Messages.TLChatFull>(req);`
