### ISSUE TITLE
Not getting _phoneCodeHash Value

### ISSUE THREAD

**Issue by wasimjee** [sochix/TLSharp#42]
I am using the following Code

    private async void btrequestcode_Click(object sender, EventArgs e)
        {
            var store = new FileSessionStore();
            var client = new TelegramClient(store, "session");
            await client.Connect();
            var hash = await client.SendCodeRequest(tbmobile.Text);
            MessageBox.Show(hash);
        }

but i am unable to get the hash variable.

I am using 149.154.167.50 and also used other IPs : 91.108.56.165 , 149.154.167.90, 149.154.167.91 

Please guide me , where i am wrong.

**Comment by keyvanarasteh** [comment]
i have the same problem :-( somebody help plzzzzzzz

**Comment by sochix** [comment]
Sorry guys have no time to answer all questions =( You can try to review what returns function init()

**Comment by wasimjee** [comment]
@keyvanarasteh  did u got the solution

**Comment by keyvanarasteh** [comment]
nope

**Comment by sochix** [comment]
Too old
