### ISSUE TITLE
i need Forwarding message with TLSharp library (C#)

### ISSUE THREAD

**Issue by amirhossein3** [sochix/TLSharp#427]
I'm connecting to Telegram API with this C# library: TLSharp

The resources for this library is not enough, I'm trying to Forward a message to channel or supergroup .

I'm not quiet sure how to get channel post peer id (for forward function input parameters)

  await client.SendRequestAsync<TLAbsUpdates>(
                               new TLRequestForwardMessage()
                               {
                                   id = 2,
                                   peer = new TLInputPeerChannel() { channel_id = chat.id, access_hash = chat.access_hash.Value },
                                   random_id = Helpers.GenerateRandomLong()
                               });

I get this error message :

{"PEER_ID_INVALID"}

**Comment by SergeyIvann** [comment]
Hello. 

Have you got any solution on this issue? I also need functionality in my app. 

Thanks.

**Comment by navaei** [comment]
+1

**Comment by motalebe** [comment]
https://github.com/sochix/TLSharp/issues/503

**Comment by mgh9** [comment]
And this is my code to Forward a message:

```
/* e.g you can use TLInputPeerUser, TLInputPeerChat, TLInputPeerChannel here as an SourcePeer */
// a Person
var sourcePeer = new TLInputPeerUser { UserId = <<<USER.ID>>>, AccessHash = <<<USER.AccessHash>>> };
	
// normal Group
//var sourcePeer = new TLInputPeerChat { ChatId = <<<USER.ID>>> };

// SuperGroup or Channel
//var sourcePeer = new TLInputPeerChannel { ChatId = <<<USER.ID>>> , AccessHash = <<<USER.AccessHash>>> };


/* e.g you can use TLInputPeerUser, TLInputPeerChat, TLInputPeerChannel here as an SourcePeer */
// a Person
//var targetPeer = new TLInputPeerUser { UserId = <<<USER.ID>>>, AccessHash = <<<USER.AccessHash>>> };

// normal Group
var targetPeer = new TLInputPeerChat { ChatId = <<<USER.ID>>> };

// SuperGroup or Channel
//var targetPeer = new TLInputPeerChannel { ChatId = <<<USER.ID>>> , AccessHash = <<<USER.AccessHash>>> };

// random Ids to prevent bombinggg
var randomIds = new TLVector<long>
{
	TLSharp.Core.Utils.Helpers.GenerateRandomLong()
};

// source messages
var sourceMessageIds = new TLVector<int>
{
	messageIdInSourceContactToForward	// this ID should be in the SourcePeer's Messages
};

var forwardRequest = new TLRequestForwardMessages()
{
	FromPeer = sourcePeer,
	Id = sourceMessageIds,
	ToPeer = targetPeer,
	RandomId = randomIds,
	//Silent = false
};

var result = await myTelegramClient.SendRequestAsync<TLUpdates>(forwardRequest);

```

I can't use the [single form of the method](https://core.telegram.org/method/messages.forwardMessage), but have to use [this one](https://core.telegram.org/method/messages.forwardMessages)

**Comment by amirhossein3** [comment]
hello , i resolved it , just about two years ago
currently i've forgotten .
but i will try found my code
