### ISSUE TITLE
Account had been deactivated and banned

### ISSUE THREAD

**Issue by samuelg78** [sochix/TLSharp#439]
My account had been deactivated and banned this morning. I had tried another number but also encountered the same issue. I tried to login from my phone App but show the "Banned Phone Number".

The sequence of errors before deactivated:
1. Unable to read data from transport connection
2. Client not connected to server
3. USER_DEACTIVATED

Anyone encounter the same issue? How to unban the number?

**Comment by gviddy** [comment]
Wtf.. Same thing just happened to me.. Wtf.. I cannot even use the official app anywhere.. Using this library has somehow gotten me banned... Not impressed! 🙁

**Comment by ali-kamali** [comment]
Same thing just happened to me!!

**Comment by ridicoulous** [comment]
The same problem was happen with me. I write about this problem at abuse@telegram.org and twitter-accounts: telegram, smstelegram, but I have not feedback.

**Comment by ali-kamali** [comment]
This error appear when i try to active in web :
Method: auth.sendCode
Url: N/A
Result: {"_":"rpc_error","error_code":400,"error_message":"PHONE_NUMBER_BANNED"}

**Comment by ridicoulous** [comment]
Yes. the same error. Write about this at abuse@telegram.org or at https://twitter.com/smstelegram

**Comment by samuelg78** [comment]
I had also written at https://twitter.com/smstelegram, but no reply from them yet.

**Comment by gviddy** [comment]
OK, so today I am unbanned..

Personally I did not realise Telegram bans users from their service. If anything all I did with this library was send maximum 5 messages, and grabbed the contact list a couple times.. Just a quick play with the library... 

If this results in my phone number being banned then I don't know how Telegram expects anyone to use their API....  :(

**Comment by ali-kamali** [comment]
I had also written about this. no reply yet.
@gviddy How do you get unbanned?

**Comment by ridicoulous** [comment]
@gviddy How do you get unbanned, tell us please

**Comment by gviddy** [comment]
Oh i did nothing.. I just assumed it was a 24 hour ban? Maybe you guys check again tomorrow?

Possibly this library is doing something it shouldn't and thats why we all got banned....

**Comment by MikhailKrasnobaev** [comment]
Wrote to twitter, telegram support, vk.com telegram support -  account got unbanned. Still don't know what happened.

**Comment by hadi77ir** [comment]
Probably it's because you don't use the server provided by Telegram for development. (When you opt-in for an API key and hash, it gives you two IP addresses: one for production, one for development)
We may have to modify "Session.cs" and "TelegramClient.cs" to support custom server addresses.

**Comment by ali-kamali** [comment]
today I am unbanned too.

**Comment by samuelg78** [comment]
Yes.... i was unbanned. Wrote to @smstelegram but no reply. Is the support dead?

**Comment by omarmaher100** [comment]
The same with me but I sent to them on this email
abuse@telegram.org
And asked them to remove ban and it's done
After they removed ban you will need to authorize your number again

**Comment by mintmilk** [comment]
Mine's banned too.but Why so many people has been banned?

**Comment by bedefaced** [comment]
@mintmilk see hadi77ir's comment. Problem is IP to which library is connecting _by default_.

**Comment by Zack-Bee** [comment]
I think my account is banned too and the website show something like following
(I just login in on the official website : p)

One of the params is missing or invalid.
Method: auth.sendCode
Result: {"_":"rpc_error","error_code":400,"error_message":"PHONE_NUMBER_BANNED"}

**Comment by ppanhoto78** [comment]
I've done a small change to the API to address this issue: this way, once you've registered your session, You don't need to authorise again until client.IsUserAuthorised returns false. 

I've just exposed a property named `Session { get { return _session; } }` so that I can retrieve its TLUser without signing in again. Apparently, that worked.


Sample App code:

                client = new TelegramClient(APIId, APIHash, session);
                await client.ConnectAsync();
                Console.WriteLine($"Authorised: {client.IsUserAuthorized()}");
                TLUser user = null;
                if (client.IsUserAuthorized())
                    user = client.Session.TLUser;
                else
                {
                    var registered = await client.IsPhoneRegisteredAsync(phone);
                    var hash = await client.SendCodeRequestAsync(phone);
                    Console.Write("Code: ");
                    var code = Console.ReadLine();
                    if (!registered)
                    {
                        Console.WriteLine($"Sign up {phone}");
                        user = await client.SignUpAsync(phone, hash, code, "first", "last");
                    }
                    Console.WriteLine($"Sign in {phone}");
                    user = await client.MakeAuthAsync(phone, hash, code);
                }

Perhaps it would be more consistent if the class was changed from `bool IsUserAuthorized()` to a `TLUser AuthorizedUser()` that returns `null` whenever no one has signed in yet.

**Comment by knocte** [comment]
@ppanhoto78 interesting, did you publish a pull request for this?

**Comment by Kamahoro** [comment]
Hi, 

I'm trying to create a telegram group and I get this message : INPUT_USER_DEACTIVATED. What does it mean and what should I do to create the group?

I've reached out to Telegram both from the phone App and on Twitter but no response!

**Comment by ppanhoto78** [comment]
@knocte I was in such a hurry that I just committed to master along with other changes. Sorry for that.

**Comment by pieuxvu** [comment]
Fucking telegram, my account is banned without any reason. Shit company

**Comment by nguyenvu1981** [comment]
my account is banned without any reason. Please help reopen it

**Comment by veptagg** [comment]
Telegram is a useless program . fucking shit. banning someone without a reason they are stupid

**Comment by aklema** [comment]
can my account be fixed? " ?

**Comment by ilya-palachev** [comment]
I had the same problem, and wrote to "login@stel.com". After several hours they replied as follows:

> Hello,
> The issue with your phone number should be solved now, please check.
> We apologize for all the inconvenience caused.
> Do not hesitate to contact us again if you encounter any similar problem.
> Please contact our support service (Settings - Ask a Question), should
> you have any questions about Telegram.
> Regards,
> Telegram Recovery Team

and the problem has been resolved, now my phone number is unbanned.
