### ISSUE TITLE
invalid packet length

### ISSUE THREAD

**Issue by ra0o0f** [sochix/TLSharp#44]
the library works fine for me, i could make it work with layer40, except at [TcpMessage.cs](https://github.com/sochix/TLSharp/blob/master/TLSharp.Core/Network/TcpMessage.cs#L63) line 63, sometimes the `packetLength` is negative or more than packet size.

thanks for your great work

**Comment by sochix** [comment]
Try to ignore such TcpMessages, maybe it's failure of network.

**Comment by ra0o0f** [comment]
@sochix yes i tried to ignore and continute but it happen again and again, and one thing is strange that sometime `sequence` is valid, take a look at results i'm receiving:

```
first response:
avaliableBytes: 256
packageLength:1076
seq: 0 => which is correct

second response:
avaliableBytes: 1608
packageLength:1891970753
seq: 1992984927

third response:
avaliableBytes: 6644
packageLength: 6644
seq: 2 => correct
// this will fail too, because 12byte less read binaryReader.ReadBytes(packetLength - 12);

forth response:
avaliableBytes: 36860
packageLength:30916
seq: 3 => correct
```

**Comment by ra0o0f** [comment]
@sochix i found something, a response can be send in several tcp messages,

i get this response:
```
first availableBytes: 2920
packetLength: 3188

second availableBytes: 268
packetLength : -332744926

// which 2920 + 268 = 3188
```

i think it's because i use layer40, and telegram has not documention for it yet

**Comment by ra0o0f** [comment]
@sochix changing receive to below solve the problem:

```csharp
            var stream = _tcpClient.GetStream();

            var packetLengthBytes = new byte[4];
            await stream.ReadAsync(packetLengthBytes, 0, 4);
            int packetLength = BitConverter.ToInt32(packetLengthBytes, 0);

            var seqBytes = new byte[4];
            await stream.ReadAsync(seqBytes, 0, 4);
            int seq = BitConverter.ToInt32(seqBytes, 0);

            int readBytes = 0;
            var body = new byte[packetLength - 12];
            int neededToRead = packetLength - 12;

            do
            {
                var bodyByte = new byte[packetLength - 12];
                var availableBytes = await stream.ReadAsync(bodyByte, 0, neededToRead);
                neededToRead -= availableBytes;
                Buffer.BlockCopy(bodyByte, 0, body, readBytes, availableBytes);
                readBytes += availableBytes;
            }
            while (readBytes != packetLength - 12);

            var crcBytes = new byte[4];
            await stream.ReadAsync(crcBytes, 0, 4);
            int checksum = BitConverter.ToInt32(crcBytes, 0);

            byte[] rv = new byte[packetLengthBytes.Length + seqBytes.Length + body.Length];

            Buffer.BlockCopy(packetLengthBytes, 0, rv, 0, packetLengthBytes.Length);
            Buffer.BlockCopy(seqBytes, 0, rv, packetLengthBytes.Length, seqBytes.Length);
            Buffer.BlockCopy(body, 0, rv, packetLengthBytes.Length + seqBytes.Length, body.Length);
            var crc32 = new Ionic.Crc.CRC32();
            crc32.SlurpBlock(rv, 0, rv.Length);
            var validChecksum = crc32.Crc32Result;

            if (checksum != validChecksum)
            {
                throw new InvalidOperationException("invalid checksum! skip");
            }

            return new TcpMessage(seq, body);
```

**Comment by sochix** [comment]
Can you please, make a pull request?

**Comment by ra0o0f** [comment]
@sochix of course, is the code approved by your standards? any changes?

**Comment by sochix** [comment]
seems to be ok =) Thank you!

**Comment by siml173** [comment]
where do i have to copy that code?

**Comment by ra0o0f** [comment]
@siml173 at https://github.com/sochix/TLSharp/blob/master/TLSharp.Core/Network/MtProtoSender.cs#L131

replace _transport.Receieve() with it.

i'm sorry i will send the PR asap

**Comment by ra0o0f** [comment]
PR created

**Comment by sochix** [comment]
@ra0o0f merged. Thanks!

**Comment by schlumpf90** [comment]
Hi to all,

I have the same problem : "couldn't read the packet length"

From the first use of my application, I can register my phone account. After this I can send one message successfully from my application. But from the second message I get this error.
I'm using the telegram server 149.154.167.50    I changed it to several other ip adresses, but the result was the same error.

Then I tried the solution from "ra0o0f" from x-mas 2015 (see above), but then I get an arithmetic error at "var body = new byte[packetLength - 12];"

So I think, that the length of the received packet is less than 4 bytes.

Does anyone solved this problem or can help me please !?!?!?

Thanx and best wishes,
Matthias

**Comment by cyberyak** [comment]
After last update I start receiving this error very often (every 2 minutes in my telegram client). Couldn't replicate and understand conditions because it appears randomly, but seems still actual problem.
