### ISSUE TITLE
Is it better to rewrite TeleSharp namespace to use SharpTL project inside TLSharp?

### ISSUE THREAD

**Issue by hadi77ir** [sochix/TLSharp#443]
I saw a TL serializer named [SharpTL](https://github.com/everbytes/SharpTL) which will be very helpful when generating codes. Code generation becomes way better, as we don't have to mess with serialization/deserialization.
Our code will become way cleaner too.

How's that? If I do that, will it be accepted?

**Comment by knocte** [comment]
Our code would become cleaner because you would be removing a bunch of code from our library which is doing what SharpTL is doing.

Therefore, the question we have to answer first is: is SharpTL better doing serialization/deserialization than TLSharp?

**Comment by sochix** [comment]
@hadi77ir I'm against it, as SharpTL isn't developed for ~2 years.
