### ISSUE TITLE
Request an Example for using TLsharp

### ISSUE THREAD

**Issue by mahdibg** [sochix/TLSharp#45]
I studied issues but still have problems in using the TLSharp.

Please give the following code:
One Button(btnSend) and two TextBox(txtMessage,txtNumber) on a form, each time the button is clicked text in 'txtMessage' is send to the 'txtNumber' 

thanks

**Comment by mahdibg** [comment]
what's the different between these keys?
numberToAuthenticate
registeredNumber"
unregisteredNumber

What number must be entered for these cases?

**Comment by sochix** [comment]
numberToAuthenticate - number of your phone registered in Telegram
registeredNumber - any number registered in Telegram
unregisteredNumber - any number that isn't registered in Telegram
