### ISSUE TITLE
Import Contact

### ISSUE THREAD

**Issue by mehdiyahyavi** [sochix/TLSharp#454]
hi.
i can't to use method importByUserNameAndSendMessage like client.importByUserNameAndSendMessage
or importByPhone

when i typed client. , this method unavailable for me.

help me .

**Comment by jak65** [comment]
I have same problem. ImportContact method is missing

**Comment by mehdiyahyavi** [comment]
you must to use this mthod : TLRequestImportContacts

**Comment by hosseinGanjyar** [comment]
@mehdiyahyavi How I connect to u?

**Comment by mehdiyahyavi** [comment]
mehdiyahyavi@hotmail.com
