### ISSUE TITLE
How i can AuthUser for new Telegram Number

### ISSUE THREAD

**Issue by novinp** [sochix/TLSharp#46]
Hi
i have problem with AuthUser  when my number is new Telegram Number and not registered on tegegram yet. in this cases i recive sms on my phone but error on MakeAuth func.
for telegram numbers i can recive code via sms and on actived telegram and no problem.
thank's

**Comment by sochix** [comment]
Library don't support registrating new numbers. You can donate for this
future.
2 янв. 2016 г. 18:18 пользователь "novinp" <notifications@github.com>
написал:

**Comment by siml173** [comment]
my phone number is registered in telegram with android app. when im trying to makeauth it return following error : 
PHONE_NUMBER_UNOCCUPIED
please help

**Comment by sochix** [comment]
See https://github.com/sochix/TLSharp/issues/48#issuecomment-170209214
