### ISSUE TITLE
how to get all members in channel?

### ISSUE THREAD

**Issue by elmagekmosaad** [sochix/TLSharp#461]
how to get all members in channel?

**Comment by an2114** [comment]
You need a channel id and hash to get things done, here is a code sample:
`var request = new TLRequestGetParticipants
                {
                    offset = offset,
                    limit = limit,
                    channel = new TLInputChannel { access_hash = channelHash, channel_id = channelId },
                    filter = new TLChannelParticipantsRecent()
                };
                TLChannelParticipants found = await client.SendRequestAsync<TLChannelParticipants>(request);`

**Comment by elmagekmosaad** [comment]
can u tell me whene i can get chanal hash?
and
can u give me code vb.net not #c ?

**Comment by an2114** [comment]
Sorry, I haven't written any vb.net code, but there must be online tools for code conversion. Here is simplified c# code you can use to get the hash:

```
TLFound found = await client.SearchUserAsync(channelName, 1);
 var channel = found.GetChannels().FirstOrDefault();
if (channel != null)
{
   //channel object will contain 'id' and 'access_hash' properties you need
}
```

**Comment by elmagekmosaad** [comment]
ok thanks

**Comment by parabola949** [comment]
You'll also need to use offsets to get all the members, if a large group.  Here's a snippet from one of my projects, though I like how @an2114 is getting the hash better, I'll probably use that :)

```cs
public static async Task<ChannelInfo> GetChatInfo(string groupName)
        {
            if (! await AuthUser()) return null;
            var result = new ChannelInfo();
            var dialogs = (TLDialogs)await client.GetUserDialogsAsync();
            var main = dialogs.chats.lists.Where(c => c.GetType() == typeof(TLChannel))
                        .Cast<TLChannel>()
                        .FirstOrDefault(c => c.title == (groupName));
            var req = new TLRequestGetFullChannel()
            {
                channel = new TLInputChannel() { access_hash = main.access_hash.Value, channel_id = main.id }
            };
             
            var res = await client.SendRequestAsync<TeleSharp.TL.Messages.TLChatFull>(req);

            //we have to do this in slices
            var offset = 0;
            result.Channel = main;
            result.ChatFull = res;
            while (offset < (res.full_chat as TLChannelFull).participants_count)
            {
                var pReq = new TLRequestGetParticipants()
                {
                    channel = new TLInputChannel() { access_hash = main.access_hash.Value, channel_id = main.id },
                    filter = new TLChannelParticipantsRecent() { },
                    limit = 200,
                    offset = offset
                };
                var pRes = await client.SendRequestAsync<TLChannelParticipants>(pReq);
                result.Users.AddRange(pRes.users.lists.Cast<TLUser>());
                offset += 200;
                await Task.Delay(500);
            }

            return result;
        }
```
Channelnfo() was just a quick class I made, modify as needed of course
```cs
public class ChannelInfo
    {
        public TLChannel Channel { get; set; }
        public TeleSharp.TL.Messages.TLChatFull ChatFull { get; set; }
        public List<TLUser> Users { get; set; } = new List<TLUser>();

        private DateTime _dateCreated;
        public DateTime DateCreated
        {
            get { return _dateCreated; }
            set
            {
                _dateCreated = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc).AddSeconds(Channel.date).ToLocalTime();
            }
        }
    }
```

**Comment by hosseinGanjyar** [comment]
I've error: **_"CHAT_ADMIN_REQUIRED"_**

**Comment by an2114** [comment]
That happens because of a  security configuration of a channel that means a user is not allowed to view the members. You can see the same behavior in different Telegram clients (e.g. a desktop or web app).

**Comment by hosseinGanjyar** [comment]
Many times **_TLRequestGetParticipants_** return 1 more record. That's mean if I want to get 200 of 4200 contacts, many times get 201 contacts in result....!!!
This is bug of TELESHARP @knocte

**Comment by knocte** [comment]
@hosseinGanjyar good catch! please propose a pull-request to fix it

**Comment by ocecer** [comment]
also where can i put these codes?

**Comment by knocte** [comment]
We don't use github issues as a forum but to report bugs, so I'm closing this. If you want to have a more forum-like experience, you can ask questions in our gitter and telegram channels.

**Comment by evo11x** [comment]
It is blocking in this line forever var dialogs = (TLDialogs)await client.GetUserDialogsAsync(); and no error
