### ISSUE TITLE
How To Connect Multiply Accounts To The Client

### ISSUE THREAD

**Issue by FarhadMohseni** [sochix/TLSharp#463]
I Want Connect Multi Play Numbers To The Client And Send Message with Those Numbers At The Same Time . any way for this?

**Comment by parabola949** [comment]
You would most likely need to have multiple instances of the `TelegramClient`.  When you create each instance, you can use the `sessionUserId` parameter so each has their own `.dat` file.
```cs
var client = new TelegramClient(appid, apihash, sessionUserId: "some unique name here");
```

**Comment by mahdivpg** [comment]
I ask them a sample code please please

**Comment by parabola949** [comment]
just do something like this:
```cs
var client = new TelegramClient(appid, apihash, sessionUserId: "client1");
var client2 = new TelegramClient(appid, apihash, sessionUserId: "client2");
```

and so on

**Comment by mahdivpg** [comment]
very tanx
