### ISSUE TITLE
deletemessages request Problem

### ISSUE THREAD

**Issue by gilsefidi** [sochix/TLSharp#466]
hey
i want to delete some message and this is my code :

var dels = new TLVector<int>() { lists = new List<int>() { message.id } };
var G = await client.SendRequestAsync<TLAffectedMessages>(new TLRequestDeleteMessages() { id = dels , MessageId = message.id });

but this request cant delete any messages !
what can i do ?

**Comment by fargom** [comment]
Look carefull at use:
TeleSharp.TL.Channels.TLRequestDeleteMessages()
or
TeleSharp.TL.Messages.TLRequestDeleteMessages()
