### ISSUE TITLE
sending message to a user with  just "username" (not in contacts)

### ISSUE THREAD

**Issue by dev-masih** [sochix/TLSharp#467]
hello
i have a question, is there a way to sending message to a user with just his "username" that is not in contacts?
thanks in advance for this great project.

**Comment by parabola949** [comment]
Try this:
```cs
var found = await client.SearchUserAsync("username", 1);
            var u = found.users.lists.OfType<TLUser>().FirstOrDefault();
            if (u != null)
            {
                await client.SendMessageAsync(new TLInputPeerUser() {user_id = u.id, access_hash = (long)u.access_hash  }, "Hi there!");
            }
```

**Comment by Vilyak** [comment]
I have the same question. I do not have a method ".SearchUserAsync" (What should I do?

**Comment by Vilyak** [comment]
I have the same question. I do not have a method ".SearchUserAsync" (What should I do?
