### ISSUE TITLE
numberToAuthenticate , RegisteredNumber, UnRegisteredNumber

### ISSUE THREAD

**Issue by damianfixel** [sochix/TLSharp#47]
Hi in app.config file we have:
  <add key="numberToAuthenticate" value="" />
    <add key="registeredNumber" value="" />
    <add key="unregisteredNumber" value="" />

What is the meaning of each?
Thank you!

**Comment by sochix** [comment]
See here https://github.com/sochix/TLSharp/issues/45#issuecomment-167742503
