### ISSUE TITLE
client.ConnectAsync doesn't work

### ISSUE THREAD

**Issue by Dolsha** [sochix/TLSharp#480]
Hello!

I'll can't use Async method, i'll try wrapped it in:
```C#
public bool ConnectTest(bool reconnect = false)
        {
            Task<Boolean> t = ConnectAsync(false);
            t.Wait();
            return (t.Result);
        }
```

But it didn't help me. After that line in ConnectAsync: 
```C#
var result = await Authenticator.DoAuthentication(_transport);
``` 
debugger go to: 
```C#
t.Wait();
```

And takes off on different lines:
```C#
await sender.Send(step1.ToBytes());
```
```C#
var step1Response = step1.FromBytes(await sender.Receive());
```
```C#
var step2 = new Step2_DHExchange();
```
Farther than this code debugger didn't reach:
```C#
await sender.Send(step2.ToBytes(
                step1Response.Nonce,
                step1Response.ServerNonce,
                step1Response.Fingerprints,
                step1Response.Pq));
```

Status of Task(t) = WaitingForActivation. 

Can someone have any idea?
Thanks!

P.S. Sorry for my bad English

**Comment by pesar368** [comment]
Hello !
I Have This Issue.
Can you Find Any Idea To Resolve it ?

**Comment by knocte** [comment]
@pesar368 what issue exactly? I don't see any exception or error being reported here, can you paste your exception with full stack trace here?

By the way, are you using the last version of TLSharp? (latest master branch)

Thanks

**Comment by pesar368** [comment]
Hi  @knocte 
I Do This In New Console Application : 
Step 1 :
 Install-Package TLSharp

Step 2 : 
`
var apiHash = ConfigurationManager.AppSettings["ApiHash"];
            var apiId = Convert.ToInt32(ConfigurationManager.AppSettings["ApiId"] );

            var client = new TelegramClient(apiId, apiHash);
            var con = client.ConnectAsync();`
Step 3 :  In ConnectAsync(..)
`

                var result = await Authenticator.DoAuthentication(_transport);
                _session.AuthKey = result.AuthKey;
                _session.TimeOffset = result.TimeOffset;
            
`
Step 4 : In DoAuthentication(

`


            await sender.Send(step1.ToBytes());
            var step1Response = step1.FromBytes(await sender.Receive());
`
Step 5 : In await sender.Receive()


`

            var result = await _transport.Receieve();
`
Step 6 : 
`

            var stream = _tcpClient.GetStream();
            var packetLengthBytes = new byte[4];
            if (await stream.ReadAsync(packetLengthBytes, 0, 4) != 4)
                throw new InvalidOperationException("Couldn't read the packet length");
            int packetLength = BitConverter.ToInt32(packetLengthBytes, 0);
`
In This Step When Call => await stream.ReadAsync(...)
Without any Exception Jump to End line of Program 
Without Any Result
![test](https://user-images.githubusercontent.com/3647223/33124530-89cfe994-cf92-11e7-88ee-b0ff196420bc.png)

**Comment by knocte** [comment]
What result do you expect? If the connection is achieved, it doesn't throw any exception. Then you can start using the rest of the functions. If you don't use anything, the end of Main() is reached and the program finishes. Do you need some help on how to program in C#?

**Comment by pesar368** [comment]
I Expect Debug line by line program .
but many of lines code not reached
and in Any Function crash in This line.

this line is common in manay of functions .
 I Call Other Functions
and Jump to Jump At this line .

**Comment by knocte** [comment]
Sorry it's still not clear to me what you're asking. Explain in better way in a new issue. Thanks!
