### ISSUE TITLE
Why i cant get to work any api..

### ISSUE THREAD

**Issue by Axe-Usa** [sochix/TLSharp#482]
Hello i opened this issue before, i enter all things well to make my api in telegram
```
const string apiHash = "3e368f6bc7a6b30844b9e88cc940c151";
const string number = "2067177907";
const int groupId = 376934156;
```
But i cant handle these message or intercept or connect all time throws me an exception i cant do nothing with this library i'm frustated really :S

**Comment by knocte** [comment]
What exception?

**Comment by Dolsha** [comment]
1. What exception?
2. Try add 7 before ur number `"**7**2067177907"`

**Comment by Axe-Usa** [comment]
The exception i explained here:
https://github.com/sochix/TLSharp/issues/424

I tried all but never works the extension for telegram i tried everything.. sorry again.. the exception is.. in await i tried with async however didnt work for me.

**Comment by knocte** [comment]
> The exception i explained here:

Don't open new duplicate issues for the same problem please. Closing this one.
