### ISSUE TITLE
how to get all channel list

### ISSUE THREAD

**Issue by shedayat** [sochix/TLSharp#483]
how to get all channel list even with read messages?
I've join in 500 channels but GetUserDialogsAsync only return 103 channels chats!

**Comment by hagilani** [comment]
hello shedayat.
i want to join a channel but no code are exists, please if you have a code to join channel and group please send it,
thankyou

**Comment by hosseinGanjyar** [comment]
@shedayat Did u solve problem?

**Comment by mkellerman** [comment]
Can someone post a clear example how to accomplish this? I'm stuck here too.

**Comment by knocte** [comment]
Fixed by https://github.com/sochix/TLSharp/commit/f2a394ea15d14a5482cd815c4b5c2b9c672abf0e

**Comment by Mohammad-amiri-code** [comment]
how to get all channel list tlsharp
