### ISSUE TITLE
[Question] CloudPasswordNeededException: This Account has Cloud Password !

### ISSUE THREAD

**Issue by HamedFathi** [sochix/TLSharp#486]
I want to use MakeAuthAsync() fot getting the user info (Myself). I activated Two step verification so TLSharp get an error 'CloudPasswordNeededException: This Account has Cloud Password !' 

How to get User info and MakeAuth ?

**Comment by FarhadMohseni** [comment]
Use MakeAuthWithPasswordAsync Method.
