### ISSUE TITLE
convert format .dat to .stat

### ISSUE THREAD

**Issue by mahdivpg** [sochix/TLSharp#489]
Hello to everybody
When i want to connect with client inside the software,a file created for me with dat. Format and i can use it.so i want to change the format to stat. When  i connected.
Can you help me please?

**Comment by jorgelg** [comment]
Maybe I missunderstood you, but if you just want to change the file extension from ".dat" to ".stat" you might want to implement your own SessionStore so you can save your session with the filename and extension you need...

**Comment by mahdivpg** [comment]
tnx
