### ISSUE TITLE
PHONE_CODE_EXPIRED

### ISSUE THREAD

**Issue by dinhducit** [sochix/TLSharp#49]
I always receive error PHONE_CODE_EXPIRED.
i receive two message with only one code from Telegram but this code not work :(
any idea for this bug? and why telegram send 2 message for one code?

**Comment by dinhducit** [comment]
Can someone help me?

**Comment by sochix** [comment]
Maybe you run program twice?

**Comment by dinhducit** [comment]
I dont know, I just debug your source code to try test functions, and I got 2 SMS from Telegram, i try change variable code to number I receive but I got this error :(

**Comment by sochix** [comment]
Does it happen several times?


2016-01-09 17:49 GMT+03:00 Nguyen Dinh Duc <notifications@github.com>:

> I dont know, I just debug your source code to try test functions, and I
> got 2 SMS from Telegram, i try change variable code to number I receive but
> I got this error :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sochix/TLSharp/issues/49#issuecomment-170244589>.
>



-- 
Best regards, Ilya (http://sochix.ru)
С уважением, Илья (http://sochix.ru)

**Comment by dinhducit** [comment]
yes, i always receive 2 message for only one code from Telegram

**Comment by dinhducit** [comment]
i solve it, just change IP to: 91.108.56.165

**Comment by sajadghobadi** [comment]
you change which IP address?!
i have one internet connection and get IP address from ISP
