### ISSUE TITLE
Burn account 

### ISSUE THREAD

**Issue by mahdivpg** [sochix/TLSharp#491]
hello to every body
I with TLSharp create many program

but when connect to telegram if number Usa or Russian instant delete number and burn number

please help

solution please
tnx

**Comment by Axe-Usa** [comment]
You could to run any "basic" example ¿? instant delete what you mean's? First do the extension and after run it. however at the moment for me happen the same i put number and api hash and never works.

**Comment by FarhadMohseni** [comment]
Telegram Security System Is Banned Your Phone Number. Because You Are Using Illegal Virtual Numbers .
Please Improve Your English And See #475  and #439 .

**Comment by mahdivpg** [comment]
Thank you all solved
