### ISSUE TITLE
how to join channel

### ISSUE THREAD

**Issue by hagilani** [sochix/TLSharp#493]
hi, i am using this code , but have error
`

 var client = NewClient();

            await client.ConnectAsync();
             
            var dialogs = (TLDialogsSlice)await client.GetUserDialogsAsync();
             

            var channel = dialogs.chats.lists
                .OfType<TLChannel>()
                .FirstOrDefault(c => c.title == "akhbarefori");

            long access_hash = (long)channel.access_hash;

`
but access_hash are null.
please help;

**Comment by hagilani** [comment]
i want to join channel , but can't

**Comment by hosseinGanjyar** [comment]
Why closed?
Do you solved your problem?
