### ISSUE TITLE
Bot

### ISSUE THREAD

**Issue by amirhododi** [sochix/TLSharp#494]
Hi Guys

I like To make Bot using TlSharp But I need A sample Code to read new messages from chats but i cant 

Take me a sample code 

Very Thanks

**Comment by AbolfazlRajabpour** [comment]
Hi
you need another library for create telegram bot .
eg [telegram.bot](https://github.com/MrRoundRobin/telegram.bot) from [@MrRoundRobin](https://github.com/MrRoundRobin)

**Comment by amirhododi** [comment]
My friend i like to make cli bot and telegram real account

**Comment by knocte** [comment]
We don't use github issues as a forum, but as a way to report bugs in TLSharp library. For discussion, please join our gitter channel. Thanks
