### ISSUE TITLE
USER_BANNED_IN_CHANNEL

### ISSUE THREAD

**Issue by mahdivpg** [sochix/TLSharp#496]
Hi Guys

I can't forward messages to supergroups
message I receive when try to send something is that
USER_BANNED_IN_CHANNEL     
please help

**Comment by mahdivpg** [comment]
Solved

**Comment by dvygolov** [comment]
@mahdivpg So, how did you solve it?

**Comment by Cappadonna** [comment]
How did you solved man?Tell us.
