### ISSUE TITLE
Add user to supergroup

### ISSUE THREAD

**Issue by atabaki** [sochix/TLSharp#499]
i used TLRequestGetDialogs and found all super groups that i joined before.
i need to add one user to one of this supergroups
but i'm not admin of this super group
each supergroup is TLChannel type and therfore we have channel.id and channel.accessHash
but when i use TLRequestAddChatUser as below: 
```
public static async Task<TLAbsUpdates> AddToChatAsync(this TelegramClient client, TLAbsInputUser user, int chatId)
        {
            var req = new TLRequestAddChatUser()
            {
                user_id = user,
                chat_id = chatId,
                fwd_limit = 100

            };
            if (!client.IsUserAuthorized())
                await client.ConnectAsync();
            return await client.SendRequestAsync<TLAbsUpdates>(req);
        }
```
I must have chat_id
i used channel.Id but Invalid_Chat_Id encountered;

what't your idea about add user to another super group
(it's implemented in telegram desktop and android and other)

thanks for your reply

**Comment by atabaki** [comment]
`

**Comment by gmardok** [comment]
Why this issue closed? Any way to add/remove user to/from supergroup?

**Comment by hosseinGanjyar** [comment]
@atabaki  Why no answer people?

**Comment by gmardok** [comment]
@hosseinGanjyar my solution in update doesn't work for you?

**Comment by hosseinGanjyar** [comment]
@gmardok tnks, but Can I join to group from link. for example this group:

> https://t.me/joinchat/C7s3l0JHChP4SXJQkvAuBw

**Comment by hosseinGanjyar** [comment]
@gmardok please write a sample code for every body.
thnks

**Comment by gmardok** [comment]
@hosseinGanjyar, 
I didn't tried to invite person by link. I'm writing some kind of administrative bot, which used to create groups and administrate them for my guild.
As for sample of code - it is the same as with adding person to regular group, just use TLRequestInviteToChannel request object.

**Comment by hosseinGanjyar** [comment]
@gmardok How using of **TLRequestInviteToChannel**  service? What's it's attributes?

**Comment by gmardok** [comment]
`				var r = new TLRequestInviteToChannel
				{
					channel = new TLInputChannel {channel_id = chat.Id, access_hash = chat.AccessHash.Value},
					users = new TLVector<TLAbsInputUser>
					{
						lists = new List<TLAbsInputUser> {new TLInputUser {user_id = user.Id, access_hash = user.AccessHash.Value}}
					}
				};
			await _telegramClient.SendRequestAsync<object>(r);
`

**Comment by hosseinGanjyar** [comment]
@gmardok please see this:
https://github.com/sochix/TLSharp/issues/535

**Comment by dvygolov** [comment]
@hosseinGanjyar you should use the TLRequestImportChatInvite like this:
```
var inviteReq = new TLRequestImportChatInvite()
{
    hash = your_chat_hash //in your example it will be C7s3l0JHChP4SXJQkvAuBw
};
var inviteResp = await _client.SendRequestAsync<object>(inviteReq);
```

**Comment by dvygolov** [comment]
Also, use TLRequestCheckChatInvite, if you were already invited and you just want to find channel id and access hash.

**Comment by wecanco** [comment]
https://github.com/sochix/TLSharp/issues/591

**Comment by hosseinGanjyar** [comment]
Special thanks from @dvygolov , @wecanco for helping.

**Comment by ahron33** [comment]
> Special thanks from @dvygolov , @wecanco for helping.

can you help me please??

**Comment by davidcon** [comment]
I still have the same problem. I need to create a chat and add several users. I can do it but by default users added hasn't admin rights. Do you know how to promote them to admin?
