### ISSUE TITLE
How to Using from Library

### ISSUE THREAD

**Issue by Mahdihp** [sochix/TLSharp#5]
hello
How can I use the library
And send me the telegram
please advice
Thank you

**Comment by Mahdihp** [comment]
If the check was a practical example

**Comment by sochix** [comment]
See the [starter guide](https://github.com/sochix/TLSharp#starter-guide)

**Comment by Mahdihp** [comment]
add example worked!!

**Comment by sochix** [comment]
Don't get what you mean

**Comment by Mahdihp** [comment]
An example check

**Comment by Mahdihp** [comment]
An example of how it works

**Comment by Mahdihp** [comment]
Please

**Comment by Mahdihp** [comment]
email me : mahdihp_devsq@yahoo.com

**Comment by sochix** [comment]
The best example is tests :)
