### ISSUE TITLE
Forward Message 100% work!

### ISSUE THREAD

**Issue by motalebe** [sochix/TLSharp#503]
Worked 100%!:

                                   List<TLChannel> TargetChannel = new List<TLChannel>();

                                   TLChannel targetchanel = TargetChannel[TargetChannelList.SelectedIndex];
                                    TLInputPeerChannel cha = new TLInputPeerChannel();
                                    cha.channel_id = targetchanel.id;
                                    cha.access_hash = (long)targetchanel.access_hash;

                                    Random rand = new Random();

                                    TLVector<long> a = new TLVector<long>();
                                    a.lists.Add(rand.Next());
                                    TLVector<int> b = new TLVector<int>();
                                    b.lists.Add(tlMessage.id);
                                    TLRequestForwardMessages aa = new TLRequestForwardMessages();
                                    aa.from_peer = peer;
                                    aa.to_peer = cha;
                                    aa.random_id = a;
                                    aa.MessageId = tlMessage.id;
                                    aa.id = b;
                                    aa.silent = true;
                                    aa.with_my_score = true;

                                   TLUpdates rr = await client.SendRequestAsync<TLUpdates>(aa);

جهت شادی روح شهدا، صلوات

**Comment by mahdivpg** [comment]
http://uupload.ir/files/26jm_tlforward.jpg

:(

**Comment by motalebe** [comment]
hi,you are banned in this channel or you are'nt channel admin (can't post for this channel), try another channel.
سلام. شما توی این کانال بلاک شدید. یه کانال دیگه رو تست کنید.
یا یه کانال بسازید و روبات رو ادمین کانال کنید و تست بگیرید.

**Comment by mahdivpg** [comment]
سلام و عرض ادب من یه نرم افزار نوشتم که پیام رو از کانال میگیره و به گروه
ها فوروارد میکنه قبلا خیلی عالی کار میکرد و مشکلی نداشت ولی از زمانی که
تلگرام آپدیت شده یهو به 10 تا گروه میفرسته این ارور رو میده یهو به 100 تا
گروه متد فوروارد تو لایه جدید آپدیت شده ولی آقای sochix هیچ آپدیتی از
tlsharp نداره خیلی این مسئله برام مهمه شما اطلاعای از متد جدید ندارید همین
رو فورواردش رو توسعه بدیم ؟

**Comment by motalebe** [comment]
بنده هم دقیقا روی همین مسئاله دارم کار میکنم. به این شکل ک پیام ها رو از کاناها میگیره و با تغییر لینک ها و آی دی ها و محتوای تبلیغاتی کانال مبدا (ک از طریق پنل تحت وب هم این فیلترها قابل مدیریت هست) به کانالها و روبات های مقصد ارسال میکنه.
شما باید در ارسالهاتون وقفه ایجاد کنید و یک مرتبه ارسال نکنید، و به این نکته هم توجه کنید که ادمین های گروه ها اکثرا آنتی اسپم توی گروه گذاشتن و ممکنه اون روبات ها شما رو بلاک کنن. پس رباتی که می سازید باید رفتاری انسانی داشته باشه و مشخص نباشه ک یک اکانت اتوماتیک هست.

راجع به آپدیت های تلگرام هم در حال بررسی هستم، و اینکه احتمالا متدهای تلگرام برای کلاینت رو بازنویسی کنم و dll رو در اینجا منتشر کنم. البته هنوز وارد این فاز نشدم.

**Comment by mahdivpg** [comment]
میتونم آیدی تلگرامتون رو داشته باشم و اونجا بهتون پیام بدم ؟

**Comment by motalebe** [comment]
@WeCanCo

**Comment by mahdivpg** [comment]
تشکر

**Comment by hagilani** [comment]
سلام @wecanco , 

اجازه دارم توی تلگرام مزاحم شما بشوم؟

**Comment by motalebe** [comment]
@hagilani 
سلام. مراحمید

**Comment by hanigamini** [comment]
@wecanco 
سلام من کد شما را نوشتم ولی خطای زیر را میده

MESSAGE_IDS_EMPTY

TLInputPeerChannel cha = new TLInputPeerChannel();

                                cha.ChannelId = دستی دادم;
                                cha.AccessHash = دستی دادم;
                                

                                Random rand = new Random();

                                TLVector<long> a = new TLVector<long>();
                                a.ToList().Add(rand.Next());
                                TLVector<int> b = new TLVector<int>();
                                b.ToList().Add(10);
                                TLRequestForwardMessages aa = new TLRequestForwardMessages();
                                aa.FromPeer = cha;
                                aa.ToPeer = new TLInputPeerChannel() { ChannelId = c.Id, AccessHash = c.AccessHash.Value };
                                aa.RandomId = a;
                                aa.MessageId = 10;
                                aa.Id = b;
                                aa.Silent = true;
                                aa.WithMyScore = true;

                                TLUpdates rr = await client.SendRequestAsync<TLUpdates>(aa);

**Comment by hossein1t** [comment]
Hi,
cha.ChannelId Should be int32 as declared in  TLInputPeerChannel, but the id of channels in telegram are int64 (longer than int32) So, I get error for this. Any idea ?

**Comment by amirvenus** [comment]
> بنده هم دقیقا روی همین مسئاله دارم کار میکنم. به این شکل ک پیام ها رو از کاناها میگیره و با تغییر لینک ها و آی دی ها و محتوای تبلیغاتی کانال مبدا (ک از طریق پنل تحت وب هم این فیلترها قابل مدیریت هست) به کانالها و روبات های مقصد ارسال میکنه.
> شما باید در ارسالهاتون وقفه ایجاد کنید و یک مرتبه ارسال نکنید، و به این نکته هم توجه کنید که ادمین های گروه ها اکثرا آنتی اسپم توی گروه گذاشتن و ممکنه اون روبات ها شما رو بلاک کنن. پس رباتی که می سازید باید رفتاری انسانی داشته باشه و مشخص نباشه ک یک اکانت اتوماتیک هست.
> 
> راجع به آپدیت های تلگرام هم در حال بررسی هستم، و اینکه احتمالا متدهای تلگرام برای کلاینت رو بازنویسی کنم و dll رو در اینجا منتشر کنم. البته هنوز وارد این فاز نشدم.

میشه لطفا یکم رو داتنت کور کار کنید؟


رو مک مشکل
 Authentication 
داره!

**Comment by sina9857** [comment]
> peer

سلام
````
aa.from_peer = peer;
aa.to_peer = cha;
aa.random_id = a;
aa.MessageId = tlMessage.id;
aa.id = b;
aa.silent = true;
aa.with_my_score = true;
````
&rlm; from_peer رو چطور مقدار دهی کردید؟
&#8207; منظور از with_my_score چیه؟

**Comment by mgh9** [comment]
If somebody still looking for a sample code :
[here](https://github.com/sochix/TLSharp/issues/427#issuecomment-653803132)
