### ISSUE TITLE
c# problem

### ISSUE THREAD

**Issue by siml173** [sochix/TLSharp#51]
hi.
in TLSharp.Core.Requests.AckRequest you in line 36 you wrote :
public override bool Confirmed => false;
i have VS 2013, why my VS doesn't recognize this?
please help, i can't build the project. :-(

**Comment by dinhducit** [comment]
this code using C# 6, you need use VS 2015 to build project or install .NET 4.5.2 or higher :)

**Comment by siml173** [comment]
could you please compile it and send .dll for me. i want use it in vs 2013

**Comment by sochix** [comment]
Better to use VS 2015
