### ISSUE TITLE
Flood prevention after run/stop app for 10 times

### ISSUE THREAD

**Issue by hosseinGanjyar** [sochix/TLSharp#511]
I want test app and add/remove some of code, so run app and stop it (maybe 10 times in 15 minutes). After last run I get this error:

> Flood prevention. Telegram now requires your program to do requests again only after 82470 seconds have passed (TimeToWait property). If you think the culprit of this problem may lie in TLSharp's implementation, open a Github issue please.

My code:
```
var client = new TelegramClient(apiId, apiHash);
await client.ConnectAsync();

var hash = await client.SendCodeRequestAsync(NumberToAuthenticate);
var code = "83238"; // you can change code in debugger

var user = await client.MakeAuthAsync(NumberToAuthenticate, hash, code);

var history = await client.GetHistoryAsync(new TLInputPeerUser() { user_id = user.id }, 0, -1, 100);
```

**Comment by jinny3770** [comment]
I had same exception. 
The exception is occurred when you request too many authentication code.
Session may solve your problem.

```
                var session = new FileSessionStore();
                var client = new TelegramClient(api_key, api_hash, session, "session");
                await client.ConnectAsync();
```

With the session, you don't have to request authentication code every time.

**Comment by hosseinGanjyar** [comment]
I solved this with a formula that me created it. For helping pleaase contact to me.

**Comment by knocte** [comment]
If you're not willing to share this info publicly, I'm closing this issue.

**Comment by hosseinGanjyar** [comment]
#474

**Comment by CrazyminerMC** [comment]
@hosseinGanjyar what's your Telegram username ?

**Comment by hosseinGanjyar** [comment]
@CrazyminerMC see my profile...

**Comment by hosseinGanjyar** [comment]
I solved this issue. please send your question in my group:
https://t.me/joinchat/HhLHow3Ed97A0gRZo7Ggog

**Comment by hosseinGanjyar** [comment]
Hi every body...You can ask your questions in this group:
https://t.me/joinchat/JRwh2w0A-7YlrMT_V4KhFQ

**Comment by Mongo71** [comment]
OUR SCRIPTS DO NOT HAVE 'PEER FLOOD ERRORS' LIKE ALL THE OTHER SCRIPTS YOU CAN GET ONLINE. 
WE FIX THAT ON OUR SCRIPTS..
http://telegram-groups-scraper-adder.com/

**Comment by AnandHiggs** [comment]
@hosseinGanjyar I am unable to join the group using the link. I need help get rid of this floodwait bullshit. Help please.

**Comment by AnandHiggs** [comment]
BTW found this in the documentation of a PHP API called MadelineProto:

floodwaitrate = time it took you to make the method calls + X   
Use sleep to execute max N calls in floodwaitrate seconds, this way you won’t get flood waited!

Can something similar be done on TLSharp?

PS: I realize I am a little late, so hopefully you guys have resolved this issue......Help ME
