### ISSUE TITLE
How can I change the DC?

### ISSUE THREAD

**Issue by brunokenj** [sochix/TLSharp#514]
Hi, i tried to use this code, but didn't work. How can I force a change of the DC when I connect?

var user = await client.MakeAuthAsync(phoneNumber, hash, code);

var exportedAuth = await client.SendRequestAsync<TLExportedAuthorization>(new TLRequestExportAuthorization() { dc_id = 5 });

await client.ReconnectToDcAsync(5); // Force Russia Id

var auth = await client.SendRequestAsync<TeleSharp.TL.Auth.TLAuthorization>(new TLRequestImportAuthorization
					{
						bytes = exportedAuth.bytes,
						id = exportedAuth.id
					});

....

After, I tried to get the State and received the error: TLSharp.Core.Network.UserMigrationException: User located on a different DC: 1.

**Comment by hadi77ir** [comment]
Catch this exception and move to the DC that exception says.

**Comment by knocte** [comment]
Can you try latest git master to see if it fixes your problems? Some changes have been done in this area. Please reopen this issue if you still have problems.
