### ISSUE TITLE
فروش سورس 2 نرم افزار تبلیغات انبوه تلگرام

### ISSUE THREAD

**Issue by mahdivpg** [sochix/TLSharp#515]
سلام و عرض ادب به همه دوستان عذرخواهی میکنم فارسی مینویسم انگلیسیم زیاد خوب نیست ببخشید
حسینی هستم و 2 نرم افزار تبلیغات انبوه با کتابخانه TLSharp نوشتم 
البته کتابخانه رو توسعه دادم و خیلی محدودیت ها و باگ هاش رو رفع کردم 
سورس پروژه رو میفروشم فیلم نرم افزار هم میزارم براتون میتونید نگاه کنید 
به خریدار کامل توضیح میدم چه محدودیت هایی داره تی ال شارپ و رفعش کردم و ...

http://www.aparat.com/tlamazing

**Comment by hadi77ir** [comment]
It is not the marketing section.
@sochix @knocte Please close this issue, as he's trying to sell "Send Mass Messages on Groups" software here.
