### ISSUE TITLE
Using multiple session.dat (account)

### ISSUE THREAD

**Issue by hosseinGanjyar** [sochix/TLSharp#516]
I have a API that access to many account's telegram and get data (use of parallel algorithm). 
My problem is: I don't know how create multiple **session.dat** and use those in different address?

session_1 > c:/sessions/session_1.dat
session_2 > c:/sessions/session_2.dat
...

**Comment by hadi77ir** [comment]
Use FileSessionStore with different session IDs (e.g. "session_1", "session_2", ...) when instantiating TelegramClient.

**Comment by hosseinGanjyar** [comment]
I've many number and account. I don't want using a acount.

**Comment by hosseinGanjyar** [comment]
Solved my problem with this code:
```
var session = new FileSessionStore();
var client = new TelegramClient(apiId, apiHash, session, "session_1");
await client.ConnectAsync();
```
**session_1** is file name.

**Comment by hadi77ir** [comment]
@hosseinGanjyar If your problem is solved, then please close the issue. :)

**Comment by hanigamini** [comment]
Hi @hosseinGanjyar  
موقعی که برای هر شماره سشن با اسم همون شماره میسازم خطا دارم و
IsUserAuthorized 
false
برمیگردونه
