### ISSUE TITLE
TL-Layer 66

### ISSUE THREAD

**Issue by aarani** [sochix/TLSharp#518]
TL-Layer must update to Layer 66:
[TL-Schema](https://gist.github.com/aarani/702232928ef06cbd7cefacfbc73b71c8#file-tl-schema-66-json)

I Assign this To Myself for now

**Comment by mahdivpg** [comment]
Hi Very Veryyyyyyyy GoooD

TNX

**Comment by mirror-neuron** [comment]
Thanks!
