### ISSUE TITLE
How to Send Message To Supergroup?

### ISSUE THREAD

**Issue by eightdna** [sochix/TLSharp#523]
with this script send message to group is success

`await client.SendMessageAsync(new TLInputPeerChat() { chat_id = group.id }, "!Test Message!");`

but if `group.migrated_to != null` (supergroup) i can't send message...
`
                    await client.ConnectAsync();

                    TLDialogs dialogs = (TLDialogs)await client.GetUserDialogsAsync();
                    TLChat group = dialogs.chats.lists
                        .Where(c => c.GetType() == typeof(TLChat))
                        .Cast<TLChat>()
                        .FirstOrDefault(c => c.title.Contains(id));
                    if (group.migrated_to != null)
                    {
                        TLInputChannel supergroup = group.migrated_to;
                        await client.SendMessageAsync(new TLInputPeerChat() { chat_id = group.id }, "!Test Message!"); //return PEER_ID_INVALID 
                        await client.SendMessageAsync(new TLInputPeerChat() { chat_id = group.migrated_to.channel_id }, "!Test Message!"); //return CHAT_ID_INVALID 
                        return Json(supergroup, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        await client.SendMessageAsync(new TLInputPeerChat() { chat_id = group.id }, "!Test Message!"); // SENT
                        return Json(group, JsonRequestBehavior.AllowGet);
                    }`
Can anyone help me?

**Comment by eightdna** [comment]
`await client.SendMessageAsync(new TLInputPeerChannel() { channel_id = chat.id, access_hash = chat.access_hash.Value }, "OUR_MESSAGE");`
SOLVED thanks

**Comment by lucfortunato** [comment]
How to get access_hash of supergroup?
