### ISSUE TITLE
Massive requests (discuss about flood prevention limit)

### ISSUE THREAD

**Issue by hosseinGanjyar** [sochix/TLSharp#525]
I want search 400,000 channels, so call **_SearchUserAsync_** for 400,000 times. I call this service every 15 seconds, but I get _flood prevention_ for **1 day** (~70000 seconds). 
Come on every body for solved this problem: Call telegram services for **n** times.

**Comment by knocte** [comment]
@hosseinGanjyar stop asking questions about how to use telegram for spam purposes, or you will be banned from this repository.

**Comment by hosseinGanjyar** [comment]
Why, so I have a problem with this. Are u angry?

**Comment by hosseinGanjyar** [comment]
I solved this issue. please send your question in my group:
https://t.me/joinchat/HhLHow3Ed97A0gRZo7Ggog

**Comment by Tulga** [comment]
hi hosseinGanjyar, ur group link not working ...

**Comment by hosseinGanjyar** [comment]
Hi every body...You can ask your questions in this group:
https://t.me/joinchat/JRwh2w0A-7YlrMT_V4KhFQ
