### ISSUE TITLE
Error while reading messages from chat

### ISSUE THREAD

**Issue by Hvzh** [sochix/TLSharp#528]
This is a part of my function for reading new messages from chat:

`                      public async Task GatherChatHistory(string channelName, string ch_id, string mid, int offset = 0, int minId = 0, int maxId = -1, int limit = 1)
		     {
			Log.Info(Tag, "In GatherChatHistory Start ch_id = " + ch_id);
			//TelegramClient client = CreateClient();
			//await InitializeAndAuthenticateClient(client);

			int maximal = Convert.ToInt32(mid);

			Log.Info(Tag, "In GatherChatHistory Before GetUserDialogAsync");

			try
			{
				var dialogs = (TLDialogs)await MainActivity.client.GetUserDialogsAsync();
				var chat = dialogs.chats.lists
					.OfType<TLChat>()
					.FirstOrDefault(c => c.title == channelName);

				Log.Info(Tag, "In GatherChatHistory After GetUserDialogAsync " + (chat != null));

				if (chat != null)
				{
					Log.Info(Tag, "ChТестat != null, " + channelName);
					try
					{
						var tlAbsMessages =
							await MainActivity.client.GetHistoryAsync(
								new TLInputPeerChat { chat_id = chat.id }, offset,
								minId, maxId, limit);
						Log.Info(Tag, "After GetHistoryAsync");

						var tlChannelMessages = (TLMessages)tlAbsMessages;
`
It worked normally until last Friday. At Friday I began receive exdception at last string of the code above. "Can not cast "TeleSharp.TL.Messages.TLMessagesSlice to TeleSharp.TL.Messages.TLMessages". Anybody know the reason of it?

**Comment by mHCio** [comment]
I have the same issue :( Need help, thank you
