### ISSUE TITLE
GetHistoryAsync Exception

### ISSUE THREAD

**Issue by mHCio** [sochix/TLSharp#532]
Hi all,
for reading chat history i use the following code:
`TLAbsMessages messages = await mw.publicTeleClient.GetHistoryAsync(new TLInputPeerUser() { user_id = user.id }, offset, -1, limit);

var tlMessages = (TLMessages)messages;

foreach(var index = tlMessages.messages.lists.Count - 1; index >= 0; index--)
{
//Display message in GUI
}`

This worked well till today, now i get an Exception(Can not cast "TeleSharp.TL.Messages.TLMessagesSlice to TeleSharp.TL.Messages.TLMessages) on this line:
var tlMessages = (TLMessages)messages;

This line works with one chat, but with all other chats i get the Exception and dont know why ?

Would be great to get some help, thank you

**Comment by Hvzh** [comment]
I have the same problem

**Comment by mHCio** [comment]
Try this, but same Problem - for some chats i get TLMessages and for others TLMessagesSlice ?!

                            TLRequestGetHistory req = new TLRequestGetHistory
                            {
                                peer = new TLInputPeerUser() { user_id = user.id },
                                limit = limit,
                                add_offset = offset,
                                max_id = -1
                            };
                            TLMessages tlMessages = await mw.publicTeleClient.SendRequestAsync<TLMessages>
                            (req);`

**Comment by mHCio** [comment]
I think the problem is if a chat has more messages as your "limit" you get a MessagesSlice [https://core.telegram.org/constructor/messages.messagesSlice](url)

**Comment by Hvzh** [comment]
Yes! Thank you! This is a point!!

**Comment by Hvzh** [comment]
Problem still left. In chat 2712 new messages. I set limit parameter to 10000, but function returns only 100 last new messages. Again I have cast error.

**Comment by mHCio** [comment]
max limit=100, i think it isn't possible to receive more messages in one request, i sovled it with a while loop und changed offset and limit in each iteration

**Comment by Hvzh** [comment]
I'm not very sophisticated in C#, but how you use castMessage? Out of if-else construction this variable undefined

**Comment by mHCio** [comment]
I dont use it out of if-else. I show the messages in a winform and iterate through each Messag inside if-else like this:

                            if(messages.GetType() == typeof(TLMessagesSlice))
                            {
                                var castMessages = (TLMessagesSlice)messages;
                                foreach(TLMessage mess in messages.messages.lists)
                                {
                                    //Display in GUI mess.message (Text of Message)
                                }
                            }

**Comment by Hvzh** [comment]
Ok, I understand

**Comment by hosseinGanjyar** [comment]
How can i get all dialogs? All of my dialogs are 500, but below code just returned ~130 dialogs.
Why?!

`var dialogs = await client.GetUserDialogsAsync();`

**Comment by hosseinGanjyar** [comment]
@mHCio I have seen https://github.com/sochix/TLSharp/issues/347 and https://github.com/sochix/TLSharp/issues/696  for get more dialogs than 100, but I haven't seen any solution.
Please help me or show a solution code here.
Thanks

**Comment by theFra985** [comment]
Hi @hosseinGanjyar 
I've commented with a solution in #696
