### ISSUE TITLE
AuthUser Doesn't work

### ISSUE THREAD

**Issue by siml173** [sochix/TLSharp#54]
hi.
in following method : OnResponse in class : AuthSendCodeRequest
in following lines :

var sendCodeTimeout = reader.ReadInt32();
var isPassword = reader.ReadUInt32() == boolTrue;

it return an exception with following content : 
unable to read beyond the end of stream.

in register form in telegram api, i get Public keys, should i put it some where?

and also im getting PHONE_NUMBER_UNOCCUPIED , but im registered in telegram

please help. im realy stucked on this

**Comment by siml173** [comment]
hi. why nobody help me? :-(

**Comment by sochix** [comment]
Duplicate #64
