### ISSUE TITLE
Object reference not set to an instance of an object error When execute SendCodeRequestAsync() method

### ISSUE THREAD

**Issue by hmahdavi921** [sochix/TLSharp#544]
I try to send message by tlsharp .First get api from telegram website then used documentation such as below : 
try
```
            {
                var store = new Core.FileSessionStore();
                int apiId = 111xxx;
                string apiHash = "3bd8xxxxxx";
                var client = new TelegramClient(apiId, apiHash);
                if (!client.IsConnected)
                {
                    var isConnect = await client.ConnectAsync(true);
                }
                string mobileNumber = "+989149064494";
                string hash = await client.SendCodeRequestAsync(mobileNumber);
                var user = await client.MakeAuthAsync(mobileNumber, hash, "");
                var result = await client.GetContactsAsync();
            }
            catch (Exception e)
            {
              throw;
            }
```
but when execute SendCodeRequestAsync() get error:  

> Object reference not set to an instance of an object

what is problem?

**Comment by knocte** [comment]
Please copy+paste the full stack trace, with line numbers, so that we know which variable was null.

**Comment by AbbasKhalili** [comment]
Hi.
I has same problem. I fix it by : _teleg.ConnectAsync().Wait();
main's that for every request you should to call ConnectAsync. so _sender get to not null.

**Comment by knocte** [comment]
@AbbasKhalili can you share the stacktrace that you were getting?

And, is the fix you're proposing a fix for TLSharp or your program?

**Comment by knocte** [comment]
@hmahdavi921 can you say the reason of why you close this please?
