### ISSUE TITLE
Unable to read beyond the end of the stream.  Receiving 4 bytes response on connecting

### ISSUE THREAD

**Issue by zerodwide** [sochix/TLSharp#55]
hi, i am using latest version

but sometimes for a period of  time i get strange response from InitConnection Request

at this line i have this exception! : 
Unable to read beyond the end of the stream. 
on ulong remoteAuthKeyId = inputReader.ReadUInt64(); 
on DecodeMessage(byte[] body) :: MTProtoSender.cs

the reason is because the body have only 4 bytes! but the code reading Int64! 

the question is why that kind of response?

body bytes:
108 254 255 255

**Comment by dinhducit** [comment]
I got message in past, but when I change IP address to: 91.108.56.165, package work well

**Comment by zerodwide** [comment]
@dinhducit  thank you

you were right, the last time i got PHONE_MIGRATE error and by  TcpTransport.UpdateDC(dcIdx);
the dc changed in run time.

in next run, i wasn't able to log in at all, and i thought TcpTransport.UpdateDC(dcIdx) effect was only in prev run, but it wasn't! 
before any code, i set TcpTransport.UpdateDC(MY_DEFAULT_DC) and it worked!

how that function effects remain for next run?
