### ISSUE TITLE
PHONE_MIGRATE_

### ISSUE THREAD

**Issue by siml173** [sochix/TLSharp#56]
hi.
my project  worked fine finally :-) , but there is a small problem here, i will be really glad if any body help me.
problem is:
in some phone number in login action i get your phone number registered on X dc. i did search a lot, many people said i have to change my dc, my question is should i change it at run time ? for example put those in array and check them in for loop?
please help.

**Comment by sochix** [comment]
Hi! Yes you should get all available DC, and then select one for current
user. Do it in a run-time. After you develop it, pls make a pull-request.
It'll appreciated! If you have any questions about it don't afraid to ask
11 янв. 2016 г. 10:46 пользователь "siml173" <notifications@github.com>
написал:

**Comment by sochix** [comment]
Reconnect functionality added to lib, should never happen again.
