### ISSUE TITLE
Получить отчет о доставке сообщения 

### ISSUE THREAD

**Issue by damonx009** [sochix/TLSharp#563]
Добрый день подскажите как получить отчет о доставки сообщения, отправляю следующим кодом:
`
 var client = new TelegramClient(YYYYYY, "YYYYYYYYYYYYYYYY");
            await client.ConnectAsync();
            //get available contacts
            var result = await client.GetContactsAsync();

            //find recipient in contacts
            var user = result.users.lists
                .Where(x => x.GetType() == typeof(TLUser))
                .Cast<TLUser>()
                .FirstOrDefault(x => x.phone == "ХХХХХХХХХХХХХ");

            //send message
            await client.SendMessageAsync(new TLInputPeerUser() { user_id = user.id }, "Привет123");
`

**Comment by knocte** [comment]
Open new issue but in English please. (I'm not English native speaker either, but I don't understand Russian)
