### ISSUE TITLE
Send Message with Markdown style

### ISSUE THREAD

**Issue by sginfoocio** [sochix/TLSharp#565]
Hi,

  It´s possible send message with bold, italic, inline etc.. i send parse_mode in TLRequestSendMessage but not work

Thanks

**Comment by akartynnik** [comment]
The same question.

**Comment by ruben0909** [comment]
+1
But I think only Api Bot can do it.

**Comment by knocte** [comment]
We don't use github issues as a forum, but as a way to report bugs in TLSharp library. For discussion, please join our gitter channel. Thanks
