### ISSUE TITLE
Unable to read beyond / DecodeMessage(byte[] body)

### ISSUE THREAD

**Issue by DaveOff** [sochix/TLSharp#57]
hi guys,, first thanks for TLSharp.

AuthenticationWorks method WORK Fine without error but TestConnection i get Unable to read beyond the end of the stream.

i have problem on Connect() and DecodeMessage() method.

on this line i get error (Unable to read beyond) : 
ulong remoteAuthKeyId = inputReader.ReadUInt64(); // TODO: check auth key id

please help me,, thanks.

**Comment by ra0o0f** [comment]
maybe this issue is related to you:
https://github.com/sochix/TLSharp/issues/55
