### ISSUE TITLE
فروش سورس کتابخانه توسعه داده شده TLSharp

### ISSUE THREAD

**Issue by mahdivpg** [sochix/TLSharp#571]
به نام خدا
سلام و عرض ادب خدمت همه دوستان
فروش کتابخانه توسعه داده شده TLSharp 

کتابخانه لایه 57 هست 
1. خیلی مشکلاتش برطرف شده  💪
2. مشکل کانکت شدن برطرف شده 
3. متد جوین در گروه اضافه شده
4. متد گرفتن همه گروه ها اضافه شده 
* متد خود TLSharp تا 100 گروه رو میگیره و محدودیت میده 
5. تا لایه 66 TL ها برای Request فرستادن نوشته شده
6. متد فوروارد اضافه شده
7. متد ادد کردن کاربر و ربات به گروه ها اضافه شده
8. متد اضافه کردن شماره به مخاطبین اضافه شده
9. مشکل دانلود فایل ها برطرف شده
10. متد خوردن تیک دوم در pv ها نوشته شده کسی در pv پیام داد با این متد میتونه تیک دوم رو بزنه

برای خرید و اطلاعات بیشتر و سوال با شماره :

09214330845 حسینی

یا با آیدی :
@tladvamazing
@TlgramApi
تماس بگیرید

یک سولوشن Example هم از فوروارد و جوین و ادد و ... هستش 

که میتونید کار با متد ها رو ببینید 

گرفتن آپدیت ها هم در TL ها پیاده سازی شده

@TLgram_Api

میتونید متد ها رو کپی کنید و در لایه 66 هم ازش استفاده کنید بهتون میگم چجوری

**Comment by knocte** [comment]
Please create new issue, but in English please. (It's not my mother tongue, but I understand it. However I don't understand the language you used here :-( )
