### ISSUE TITLE
How to mark message as read?

### ISSUE THREAD

**Issue by mirror-neuron** [sochix/TLSharp#573]
Have TLSharp this functional?

**Comment by mirror-neuron** [comment]
As I understand it's posible to subscribe update events and get message through it with marking message as read. How to do this? Or maybe i need to change some bool flag?

**Comment by mirror-neuron** [comment]
Guess something like this, but i get error.
```
var ipeer = new TLInputPeerChannel() { channel_id = target.channel_id, access_hash = target.access_hash};
var res = new TLAffectedHistory() { offset = 0, pts = 1, pts_count = 1 };
var markAsRead = new TLRequestReadHistory() { peer = ipeer, MessageId = m.id, max_id = int.MaxValue, Dirty = true, ConfirmReceived = false, Sequence = 100};
//var error = await telegram.SendRequestAsync<TLAffectedHistory>(markAsRead);
```

**Comment by JaMandh** [comment]
hey buddy , can you share this source code?(i can't understand whats the "target" in this code)

**Comment by NickolayKabash** [comment]
for me it returns always 'false':

var readed = await telegram.SendRequestAsync<bool>(markAsRead);

and then I get again this message from TLRequestGetDifference

**Comment by Wade227** [comment]
@NickolayKabash Did you ever find a solution to this problem? Im getting the same thing?
