### ISSUE TITLE
getContact

### ISSUE THREAD

**Issue by siml173** [sochix/TLSharp#58]
i wrote getContactRequest , if any body wants that just say it :-)

**Comment by dinhducit** [comment]
yes, can u share it, and can  u send media file?

**Comment by sochix** [comment]
Make a pull-request please
13 янв. 2016 г. 17:20 пользователь "Nguyen Dinh Duc" <
notifications@github.com> написал:

**Comment by siml173** [comment]
i also wrote following request that i tested :
AddChatUserRequest
CreateChatRequest
DeleteChatUserRequest
GetContactRequest
ImportContactRequest (updated so it can get list of numbers to import now)
but i couldn't make a pull request, can u tell me how can i do that, it seems i don't have access.

**Comment by sochix** [comment]
Just clone tlsharp repo on github, make your changes and then click pull
request
16 янв. 2016 г. 9:14 пользователь "siml173" <notifications@github.com>
написал:

**Comment by siml173** [comment]
i did. :-)

**Comment by sochix** [comment]
Thank you! I'll review and merge asap

суббота, 16 января 2016 г. пользователь mohammad ahmady написал:

> i did. :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sochix/TLSharp/issues/58#issuecomment-172173832>.
>


-- 
Best regards, Ilya (http://sochix.ru)
С уважением, Илья (http://sochix.ru)

**Comment by siml173** [comment]
Ok. you'r welcome
