### ISSUE TITLE
How to listen new message / use handle update?

### ISSUE THREAD

**Issue by mirror-neuron** [sochix/TLSharp#580]
According to #361 #43 right way to get new messages is TLRequestGetDifference or HandleUpdate usage. Also we can find official manual about processing updates: https://core.telegram.org/api/updates 
Here we need an source code example. Same questions:  #564 #239 #436 #457 #524 #538 #547 #570

**Comment by mirror-neuron** [comment]
If you need to catch message from real user you can check status in simple loop
```
while (true) {
   var state = await telegram.SendRequestAsync<TLState>(new TLRequestGetState());
   if (state.unread_count > 0) { ... }
}
```
All new message from users after authorising are saved in this field. But this not working with channels.

**Comment by mirror-neuron** [comment]
In general you need to create test channel, test group and second user and check whats happends with this code pattern or try to use PUSH notification https://core.telegram.org/api/push-updates.
```
while (true)
{
    var state = await telegram.SendRequestAsync<TLState>(new TLRequestGetState());
    var req = new TLRequestGetDifference() { date = state.date, pts = state.pts, qts = state.qts };
    var adiff = await telegram.SendRequestAsync<TLAbsDifference>(req);
    if (!(adiff is TLDifferenceEmpty))
    {
        if (adiff is TLDifference)
        {
            var diff = adiff as TLDifference;
            Console.WriteLine("chats:" + diff.chats.lists.Count);
            Console.WriteLine("encrypted:" + diff.new_encrypted_messages.lists.Count);
            Console.WriteLine("new:" + diff.new_messages.lists.Count);
            Console.WriteLine("user:" + diff.users.lists.Count);
            Console.WriteLine("other:" + diff.other_updates.lists.Count);
        }
        else if (adiff is TLDifferenceTooLong)
            Console.WriteLine("too long");
        else if (adiff is TLDifferenceSlice)
            Console.WriteLine("slice");
    }
    await Task.Delay(500);
}
```

**Comment by mirror-neuron** [comment]
For reading my channels and mark message as read i use this code:
```
while (true)
{
    var state = await telegram.SendRequestAsync<TLState>(new TLRequestGetState());
    var req = new TLRequestGetDifference() { date = state.date, pts = state.pts, qts = state.qts };
    var diff = await telegram.SendRequestAsync<TLAbsDifference>(req) as TLDifference;
    if (diff != null)
    {
        foreach (var upd in diff.other_updates.lists.OfType<TLUpdateNewChannelMessage>())
            Console.WriteLine((upd.message as TLMessage).message);

        foreach(var ch in diff.chats.lists.OfType<TLChannel>())
        {
            var ich = new TLInputChannel() { channel_id = ch.id, access_hash = (long)ch.access_hash };
            var markAsRead = new TeleSharp.TL.Channels.TLRequestReadHistory() { channel = ich, max_id = -1 };
            await telegram.SendRequestAsync<bool>(markAsRead);
        }
    }
    await Task.Delay(500);
}
```

**Comment by armanjojo** [comment]
while (true)
            {
                var state = await client.SendRequestAsync<TLState>(new TLRequestGetState());
                var req = new TLRequestGetDifference() { date = state.date, pts = state.pts, qts = state.qts };
                var diff = await client.SendRequestAsync<TLAbsDifference>(req) as TLDifference;

                if (diff != null) {
                    foreach (var x in diff.new_messages.lists.OfType<TLUpdateNewMessage>())
                    {
                        listBox1.Items.Add((x.message as TLMessage).message);
                    }
                }
                await Task.Delay(500);
            }

why my code doesn't work ?

**Comment by Cjay93** [comment]
so "upd.message as TLMessage).message"  get you the message but how would u get a photo in the message or know what channel the message came from?
Please help a brother out.

**Comment by Cjay93** [comment]
munrocket thats nothing to do with the question i asked sir.

**Comment by Cjay93** [comment]
while (true)
{
    var state = await telegram.SendRequestAsync<TLState>(new TLRequestGetState());
    var req = new TLRequestGetDifference() { date = state.date, pts = state.pts, qts = state.qts };
    var diff = await telegram.SendRequestAsync<TLAbsDifference>(req) as TLDifference;
    if (diff != null)
    {
        foreach (var upd in diff.other_updates.lists.OfType<TLUpdateNewChannelMessage>())
            Console.WriteLine((upd.message as TLMessage).message);

        foreach(var ch in diff.chats.lists.OfType<TLChannel>().Where(x => !x.left))
        {
            var ich = new TLInputChannel() { channel_id = ch.id, access_hash = (long)ch.access_hash };
            var readed = new TeleSharp.TL.Channels.TLRequestReadHistory() { channel = ich, max_id = -1 };
            await telegram.SendRequestAsync<bool>(readed);
        }
    }
    await Task.Delay(500);
}
This code is ideal but i would like to accept photos and get the name of the channel of the incoming message.

thanks

**Comment by GodSpeedXI** [comment]
Someone Please give me an example how to use TLRequestRegisterDevice.
I want to get notify when messages are coming from every chat.

Thanks.

**Comment by pisitch** [comment]
Hello I have tried this code so many times.

`var state = await telegram.SendRequestAsync<TLState>(new TLRequestGetState());
    var req = new TLRequestGetDifference() { date = state.date, pts = state.pts, qts = state.qts };
    var adiff = await telegram.SendRequestAsync<TLAbsDifference>(req);
`

And I found that adiff will be returned "TLDifferenceEmpty"

**Comment by projektai** [comment]
Does anyone know why why compiler cant find "lists"?

**Comment by amirvenus** [comment]
@projektai 

try to use .ToList() instead

**Comment by Maverick1983** [comment]
@pisitch I have same problem. Anyone resolve it?

**Comment by J1herm** [comment]
Ok I'm getting a few grey hairs now.. 

I am wanting to forward messages between groups. User sets up which group forwards to whom. 

so select from group from drop down, and select to group. then config that from that point going forward all new messages are automatically forwarded from the one group to the other.. 

I am able to get the user to select To and From group and forward the last message sent to the from group gets forwarded to the To group with this code 

       var tlAbsMessages = await client.GetHistoryAsync(new TLInputPeerChat { ChatId = chat1.Id }, 0, -1,  50 );
                        var tlChatMessage = (TLMessages)tlAbsMessages;
                        var tlAbsMessage = tlChatMessage.Messages.ToList()[0];
                        var message = (TLMessage)tlAbsMessage;
                        messageID = message.Id;


       //Request for Forward: 
                        TLRequestForwardMessages rq = new TLRequestForwardMessages();
                        rq.FromPeer = new TLInputPeerChat() { ChatId = chat2.Id };
                        rq.ToPeer = new TLInputPeerChat() { ChatId = chat1.Id };


                        TLVector<long> rn = new TLVector<long>();
                        TLVector<int> idd = new TLVector<int>();

                        rn.Add(rnd.Next(1000, 5000));
                        // messageID is the last post ID of the channel or group the last messages posted's ID
                        idd.Add(messageID); 
                        rq.RandomId = rn;
                        rq.MessageId = messageID; 
                        rq.Id = idd;
                        rq.Silent = true;
                        rq.WithMyScore = true;

                        TLUpdates rr = await client.SendRequestAsync<TLUpdates>(rq);

But now I am at the point where I want to forward any new messages received on the from group to that To group as well. 

     var state = await client.SendRequestAsync<TLState>(new TLRequestGetState());
                    var req = new TLRequestGetDifference() { Date = state.Date, Pts = state.Pts, Qts = state.Qts };
                    var adiff = await client.SendRequestAsync<TLAbsDifference>(req) as TLDifference;

not sure how to hook this up to listen for new messages on a particular group to forward. 
maybe I am on the wrong track
any help /direction will be much be appreciated...

**Comment by munrocket** [comment]
> But now I am at the point where I want to forward any new messages received on the from group to that To group as well.
As i know sending message much easier than listen updates. Try with sipmle message and another user at first.

**Comment by aroaddy** [comment]
> If you need to catch new message from user or group after authorizing, you can check status in simple loop without getting FLOOD_EXCEPTION. But this not working with channels.
> 
> ```
> while (true) {
>    var state = await telegram.SendRequestAsync<TLState>(new TLRequestGetState());
>    if (state.unread_count > 0) { ... }
>    await Task.Delay(500);
> }
> ```
Hello please i would like to know where to paste this code, how do I implement in a way that it always listens for a new message.

**Comment by Trinitron** [comment]
@munrocket I want just simply track incoming messages from certain user. Why using this peace of come in while loop i miss approximately 5/6 of incoming messages? where are the rest?
`await telegram.SendRequestAsync<TLState>(new TLRequestGetState());`
Do i need subract 500ms from Date property of TLRequestGetDifference or how?

**Comment by munrocket** [comment]
@trinitron just use telethon and relax, TLSharp has an annoying verbouse api.

**Comment by Trinitron** [comment]
If someone still uses this library and struggling between unobvious exceptions here is my small example how to listen incomming telegram messages:
`                while (true)
                {
                    var state = await _client.SendRequestAsync<TLState>(new TLRequestGetState());
                    TrackingState = state.Pts.ToString();
                    var req = new TLRequestGetDifference() { Date = state.Date, Pts = state.Pts-10, Qts = state.Qts };
                    var diff = await _client.SendRequestAsync<TLAbsDifference>(req);
                    var msgs = diff as TLDifference;
                    if (msgs!=null && msgs.NewMessages.Count>0)
                    {
                        var mss = msgs.NewMessages.Where(x => x.GetType() == typeof(TLMessage))
                            .Cast<TLMessage>().ToList().Where(x => x.Date > _lastMessageStamp && x.Out == false)
                            .OrderBy(dt => dt.Date);
                        foreach (TLMessage upd in mss)
                        {
                            Console.WriteLine("New message ({0}): {1}", upd.Date, upd.Message);
                        }
                        _lastMessageStamp = mss.Any() ? mss.Max(x => x.Date) : _lastMessageStamp;
                    }
                    await Task.Delay(2500);
                }`

**Comment by asensionacher** [comment]
> `_lastMessageStamp = (Int32)(DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1))).TotalSeconds;`
> 
> >

I always receive TLDifferenceEmpty, do you know why?

**Comment by RomanSoloweow** [comment]
```
while (true)
            {
                var state = await _Client.SendRequestAsync<TLState>(new TLRequestGetState());
                if(state.UnreadCount>0)
                {
                    var req = new TLRequestGetDifference() { Date = state.Date, Pts = state.Pts-state.UnreadCount, Qts = state.Qts, Sequence = state.Seq};
                    var diff = await _Client.SendRequestAsync<TLAbsDifference>(req) as TLDifference;
                }
                
                await Task.Delay(500);
            }
```

state.Pts-state.UnreadCount - it's solve

**Comment by Invectys** [comment]
ModernTLSharp solve this problem

**Comment by knocte** [comment]
> ... solves this problem

Also this PR: https://github.com/sochix/TLSharp/pull/940 can anyone test it please?
