### ISSUE TITLE
MakeAuthAsync System.NullReferenceException

### ISSUE THREAD

**Issue by monbland** [sochix/TLSharp#583]
i trying to make auth in asp.net using same code that in my project on gtk# (where it works properly) and when i try:
`public async void login_Click(object sender, EventArgs args)
		{
            try
            {
                var user = await client.MakeAuthAsync(number.Text, hash, code.Text);
                if (client.IsUserAuthorized())
                    infolbl.Text = "vhod vypolnen";
            }
			catch (Exception eexc)
			{
				System.Console.Write(eexc.ToString());
			}
		}`
it sends me System.NullReferenceException
upd. hash is not null

**Comment by mirror-neuron** [comment]
a kto budet manual chitat?

**Comment by knocte** [comment]
Can you paste full exception stack trace please?

**Comment by knocte** [comment]
@monbland we have committed some changes in master branch that maybe solve this problem, can you git pull and try again with latest git master? If you still find this exception please reopen this issue. Thanks!
