### ISSUE TITLE
invalid constructor code

### ISSUE THREAD

**Issue by DaveOff** [sochix/TLSharp#59]
hi ,

i get some error :

Exception	Exception thrown: 'System.Exception' in mscorlib.dll ("invalid constructor code 3162085175")	System.Exception

Bad CRC32 in GZIP trailer. (actual(2F9F8956)!=expected(097283F2))")	Ionic.Zlib.ZlibException

**Comment by sochix** [comment]
Strange. Paste your codesnippet and stacktrace

**Comment by DrEhsan** [comment]
@sochix well i had that problem too actually. in fact GZipStream doesnt do any checks when you close streaming before the end. so it says Bad CRC code...

to solve the problem we have to options : 

1. pull all the sources of Ionic.ZLib into project and change it is structure to our usage to skip the CRC checks

2. change the GZipStream  to System.IO.Compression.GZipStream here : 

https://github.com/sochix/TLSharp/blob/master/TLSharp.Core/Network/MtProtoSender.cs#L299

in fact i have chosen the second one and it works for me.. maybe there is better solution
