### ISSUE TITLE
Join To Group by Link or Hash (100% work)

### ISSUE THREAD

**Issue by wecanco** [sochix/TLSharp#591]
سلام. 
با این کد میتونید از طریق لینک یا هش کد در گروه عضو بشید:

            string grhash = GHash.Text.Trim().Replace("https://t.me/joinchat/", "").Replace("/","");
            TLRequestImportChatInvite RCHI = new TLRequestImportChatInvite();
            RCHI.hash = grhash;
            TLUpdates chat = await Client.SendRequestAsync<TLUpdates>(RCHI);

جهت شادی روح امام و شهدا و سلامتی رهبر انقلاب صلوات

**Comment by hosseinGanjyar** [comment]
آقا دم شما گرم....
صلوات

**Comment by knocte** [comment]
Please use English. I'm not a native-English speaker myself (so not trying to impose my own language), but if you don't speak English not all can participate as a community.

**Comment by wecanco** [comment]
@knocte You Can Learn Farsi :) or use Google Translate!!

**Comment by knocte** [comment]
Or you can learn Spanish ;) Yes please, from now on, everything should be in Spanish and you have to use GoogleTranslator before posting, ok?

**Comment by wecanco** [comment]
@knocte I also learn Spanish if necessary

**Comment by knocte** [comment]
lol, no need, let's just use English and it's less effort for everyone

**Comment by wecanco** [comment]
@knocte Dear, 
My audience is Iranians. other body if want understand what i,m say, should use translator or learn farsi.

**Comment by Hamidnwo** [comment]
Dear @knocte,
Don't worry, the Persian message is not related to the problem.

Dear Mr. صلوات
There would be an exception if the user already joined the channel. 
برو اول یاد بگیر کد نوشتنو بعد بیا صلوات بفرس
اینقدرم از دستاوردای کفار استفاده نکن نونش حرومه

**Comment by knocte** [comment]
@Hamidnwo then please open a new issue, using only English, describing your issue. This one we leave it closed to not confuse other community members. Thanks

**Comment by hpdownload** [comment]
what is GHash in 
string grhash = GHash.Text.Trim().Replace("https://t.me/joinchat/", "").Replace("/","");

**Comment by wecanco** [comment]
hash code in group link.
**for example:**
https://t.me/joinchat/B_wdJUQUMWrjD3Khfbcl6A
====> 
Ghash = B_wdJUQUMWrjD3Khfbcl6A

**Comment by hpdownload** [comment]
is there any way to add members to channel or group?

**Comment by hanigamini** [comment]
Hi,
How can i check that link is group or channel.
I want join only group not channel , with this code all link joined.

string grhash = GHash.Text.Trim().Replace("https://t.me/joinchat/", "").Replace("/","");
        TLRequestImportChatInvite RCHI = new TLRequestImportChatInvite();
        RCHI.hash = grhash;
        TLUpdates chat = await Client.SendRequestAsync<TLUpdates>(RCHI);

**Comment by atrezonator** [comment]
> Hi,
> How can i check that link is group or channel.
> I want join only group not channel , with this code all link joined.
> 
> string grhash = GHash.Text.Trim().Replace("https://t.me/joinchat/", "").Replace("/","");
> TLRequestImportChatInvite RCHI = new TLRequestImportChatInvite();
> RCHI.hash = grhash;
> TLUpdates chat = await Client.SendRequestAsync(RCHI);

            var url = "https://t.me/joinchat/SaspY5xrHXlpViOE";
            var channelhash = url.Split("t.me/joinchat/")[1];

            var channelInfohash = client.SendRequestAsync<TLChatInvite>(new TLRequestCheckChatInvite { Hash = channelhash }).ConfigureAwait(false).GetAwaiter();
            while (!channelInfohash.IsCompleted)
            {
                Thread.Sleep(1000);
            }
            var channelhashres = channelInfohash.GetResult();
