### ISSUE TITLE
how to reply a message

### ISSUE THREAD

**Issue by Rman77** [sochix/TLSharp#598]
there is a code to reply a message ? i have message id ... but i don't know how to reply and answer it

**Comment by Ravenglass** [comment]
@Rman77 Were you able to figure out how to reply?

**Comment by speekflayder** [comment]
`string name_of_channel = "channel"; //Name of the channel
        string MSG = "abcdefg"; //Your Message
        int reply_id = 12345; //Id of replying message

        var dialogs = (TLDialogs)await client.GetUserDialogsAsync(); //Get dialogs
        var chat = dialogs.Chats
            .OfType<TLChannel>()
            .FirstOrDefault(c => c.Title == name_of_channel); //Get chat id

        var send = new TLRequestSendMessage //Make a request
        {
            Peer = new TLInputPeerChannel() { ChannelId = chat.Id, AccessHash = chat.AccessHash.Value },
            Message = MSG,
            ReplyToMsgId = reply_id
        };

        var res = await client.SendRequestAsync<TLRequestSendMessage>(send); //Send a request`
