### ISSUE TITLE
how to run test testconnection()

### ISSUE THREAD

**Issue by starbug1** [sochix/TLSharp#6]
Hi. and thank you for this project. In step 4 of https://github.com/sochix/TLSharp#quick-configuration you sayed Run test testConnection(). How can i do this? and another question that i have is that is this a project to import in visual studio or it is a library for adding to another project? Thank you.

**Comment by sochix** [comment]
>  In step 4 of https://github.com/sochix/TLSharp#quick-configuration you sayed Run test testConnection(). How can i do this?

Just open VS test runner and run test

> and another question that i have is that is this a project to import in visual studio or it is a library for adding to another project?

It's a library. The best way to understand how to use it in your own project - inspect unit tests.
