### ISSUE TITLE
Corrupted session on file DC migration

### ISSUE THREAD

**Issue by andreysolovyov** [sochix/TLSharp#602]
trying to download file:

`var file = await client.GetFile(new TLInputFileLocation
                        {
                            local_id = fileInfo.local_id,
                            secret = fileInfo.secret,
                            volume_id = fileInfo.volume_id
                        }, 512 * 1024, bytesDownloaded);`

File downloading successfully several times. After that I'm getting InvalidOperationException something like "Couldn't read the packet length" or "invalid nonce in encrypted answer". After exception every request ends with "Can't decode packet" exception.

It seems, that the issue is somewhere in file migration hadling:

`catch (FileMigrationException ex)

            {

                var exportedAuth = await SendRequestAsync<TLExportedAuthorization>(new TLRequestExportAuthorization() { dc_id = ex.DC });

                var authKey = _session.AuthKey;
                var timeOffset = _session.TimeOffset;
                var serverAddress = _session.ServerAddress;
                var serverPort = _session.Port;

                await ReconnectToDcAsync(ex.DC);
                var auth = await SendRequestAsync<TLAuthorization>(new TLRequestImportAuthorization
                {
                    bytes = exportedAuth.bytes,
                    id = exportedAuth.id
                });
                result = await GetFile(location, filePartSize, offset);

                _session.AuthKey = authKey;
                _session.TimeOffset = timeOffset;
                _transport = new TcpTransport(serverAddress, serverPort);
                _session.ServerAddress = serverAddress;
                _session.Port = serverPort;
                await ConnectAsync();

            }`

I see recursive call of GetFile after change DC and restoring auth key after downloading, but if inside of recursive call some exception of type not equal to FileMigrationException thown It will stay at last connected DC.

How to restore connection without delete session file?

**Comment by samuelg78** [comment]
Hi, i am getting the same System.InvalidOperationException' in TLSharp.Core.dll. Any help?

**Comment by andreysolovyov** [comment]
@samuelg78 at this moment I am still facing this problem. Do you have any ideas?

**Comment by samuelg78** [comment]
@andreysolovyov It had been like this since the major breakdown in asia. I dun have a solution.

**Comment by Grepsy** [comment]
Should be solved by 1877c9061c0e8e8033cb68f9257bc75fa3fb18c4 I believe.

**Comment by knocte** [comment]
Yes thanks.

@andreysolovyov if you see this again with latest master branch, reopen this please.

**Comment by eordukaya** [comment]
I have similar problem like #851
