### ISSUE TITLE
I got FILE_PART_Х_MISSING error

### ISSUE THREAD

**Issue by dinhducit** [sochix/TLSharp#61]
When I try create sendMedia function, I got error FILE_PART_Х_MISSING
https://cloud.githubusercontent.com/assets/13290578/12302400/891ac8cc-ba57-11e5-81d6-55a4a5a94701.png
Here my code:
        long random_id = Helpers.GenerateRandomLong();
string md5_checksum = MD5.GetMd5String(filename);
FileInfo f = new FileInfo(filename);
var parts = (int)f.Length / 524288;
if ((int)f.Length % 524288 > 0)
parts += 1;
InputFile file = new InputFileConstructor(random_id, parts, filename, md5_checksum);
InputMedia media = new InputMediaUploadedPhotoConstructor(file);
var request = new SendMediaRequest(new InputPeerContactConstructor(id), media);
await _sender.Send(request);
await _sender.Recieve(request);

So how I can create exactly InputFile type?
And how I can get md5_checksum of contents of file?

**Comment by sochix** [comment]
Check telegram API reference

FILE_PART_Х_MISSING: Part X (where X is a number) of the file is missing from storage. Try repeating the method call to resave the part.

https://core.telegram.org/api/files

**Comment by dinhducit** [comment]
Can you explain to me? I had read this title but I do not understand why I got this error :(

**Comment by DaveOff** [comment]
hi,
@dinhducit if u find ur problem please insert here

**Comment by sochix** [comment]
Check this example https://github.com/sochix/TLSharp#send-media-to-contact
