### ISSUE TITLE
problem limit 100 groups or channel shows to method client.GetUserDialogsAsync

### ISSUE THREAD

**Issue by ptwebco** [sochix/TLSharp#613]
hi dear develops
important problem,
My line has 160 groups whith this method getuserdialogasync limit 100 shows.
But I want to show everyone!!!

Help me please!

**Comment by elmagekmosaad** [comment]
give me your code for get group members

**Comment by ptwebco** [comment]
limit show group or channel of 100 to more 160
cann't write code
please help me!!!!

**Comment by knocte** [comment]
> can't write code

you cannot write code? why?

**Comment by ptwebco** [comment]
count supergroup more 160 but limit 100 show dialog supergroup only
problem "GetUserDialogsAsync" only limit show 100 groups

**Comment by knocte** [comment]
You already wrote that.

**Comment by ptwebco** [comment]
What is the solution to this problem?

**Comment by knocte** [comment]
Ah, I see, so you're reporting a problem, not a bug. I'm afraid that we use Github Issues for reporting bugs, this is not a forum. Please go to our gitter channel if you want to discuss.
