### ISSUE TITLE
Getting PEER_FLOOD in SendMessageAsync, what should be the limits?

### ISSUE THREAD

**Issue by elmagekmosaad** [sochix/TLSharp#621]
Hi all. I'm trying to send some messages to my channel users but after a while (30+ messages) I get an exception with PEER_FLOOD message. So, I have two questions:

How often is it allowed to send messages in Telegram? Should I use some kinds of delays or maybe change message text a bit?
If I get PEER_FLOOD, will my account be able to send messages again after some time, or it is restricted forever?

**Comment by knocte** [comment]
The purpose of github issues is to report bugs or requests for enhancements, this is not a forum. Please go to the gitter channel if you want to ask questions.

**Comment by hosseinGanjyar** [comment]
Hi every body...You can ask your questions in this group:
https://t.me/joinchat/JRwh2w0A-7YlrMT_V4KhFQ
