### ISSUE TITLE
Getting error PEER_FLOOD in SendMessageAsync, what should be do to fix or skipt this proplem??

### ISSUE THREAD

**Issue by elmagekmosaad** [sochix/TLSharp#623]
Getting error PEER_FLOOD in SendMessageAsync, what should be do to fix or skipt this proplem??

**Comment by knocte** [comment]
The purpose of github issues is to report bugs or requests for enhancements, this is not a forum. Please go to the gitter channel if you want to ask questions.

Also, if you keep posting duplicated posts, we will ban you from this repository.

**Comment by elmagekmosaad** [comment]
i can't understand where is this forum ?

can u give me url for him?

**Comment by knocte** [comment]
I didn't say there is a forum, I said that github issues are not a forum.

We have a gitter channel, please use that.

**Comment by elmagekmosaad** [comment]
thanks

**Comment by hosseinGanjyar** [comment]
I solved this issue. please send your question in my group:
https://t.me/joinchat/HhLHow3Ed97A0gRZo7Ggog

**Comment by mkliu** [comment]
@hosseinGanjyar  your link doesn't work

**Comment by hosseinGanjyar** [comment]
Hi every body...You can ask your questions in this group:
https://t.me/joinchat/JRwh2w0A-7YlrMT_V4KhFQ
