### ISSUE TITLE
AUTH_KEY_UNREGISTERED thrown after some period (requires new token), if using GetFile

### ISSUE THREAD

**Issue by Grepsy** [sochix/TLSharp#624]
I've been trying to run TLSharp continuously but seem to periodically (almost every day) run into the `AUTH_KEY_UNREGISTERED` error message. Unfortunately I can't just reconnect, because the same error keeps happening instantly.

I've found the only way to fix it is to delete the `session.dat` and re-request the authorization code, which requires manual intervention.

Does anyone else experience this?

**Comment by knocte** [comment]
Would be great if you could leave a sniffer session recording the communication, so that you could compare the packets being sent at the last moment when it throws AUTH_KEY_UNREGISTERED, and the previous one where it didn't throw it. Maybe something gets corrupted at the client side? Other people discussed this also in https://github.com/sochix/TLSharp/issues/192 (in which someone suggests to not use true as param for ConnectAsync).

**Comment by Grepsy** [comment]
When using `true` for `ConnectAsync` is happens instantly I noticed. I'll fiddle around with a sniffer and see if I can get more information. Thanks for the suggestion.

**Comment by aarani** [comment]
that's normally happen while reconnecing to other DCs, I fixed it in one my project. will look if i still have that

**Comment by knocte** [comment]
@Grepsy hey, @aarani has proposed a PR to fix this, can you check if it works for you?: https://github.com/sochix/TLSharp/pull/629

**Comment by aarani** [comment]
@knocte It's not just for that. I actually used it to fix Downloading Private files from different DCs.

**Comment by Grepsy** [comment]
Thanks, I will. And this could be the case since I am using the `GetFile` functionality. As a matter of fact I've switched off that functionality of and haven't had the error since, which adds some evidence that it's actually the culprit of this issue.

**Comment by mhdbzr** [comment]
I am getting AUTH_KEY_UNREGISTERED in a while loop for getting new updates, right after sending request for getting new state.
```
     try
            {
                TLState state; // = await client.SendRequestAsync<TLState>(new TLRequestGetState());
                while (true)
                {
                    WORKING_STATE = "Getting STATE ...";
                    **state = await client.SendRequestAsync<TLState>(new TLRequestGetState());**
                    await Task.Delay(1000);
                    //if (state.UnreadCount == 0) { await Task.Delay(1000); }
                    //--
                    WORKING_STATE = "Getting Difference ...";
                    var req = new TLRequestGetDifference() { Date = state.Date, Pts = state.Pts, Qts = state.Qts };
                    var diff = await client.SendRequestAsync<TLAbsDifference>(req) as TLDifference;
                    //--
                    if (diff != null)
                    {
// ........
```

**Comment by VDVuser** [comment]
Hi! This works for me!
string fullPathToDat = Directory.GetCurrentDirectory() + "\session";
var store = new FileSessionStore();
client = new TelegramClient(apiId, apiHash, store, fullPathToDat);
await client.ConnectAsync(false);
