### ISSUE TITLE
md5_checksum / Uploading file

### ISSUE THREAD

**Issue by DaveOff** [sochix/TLSharp#63]
hi i have on question

Telegram :

an MD5 hash of the file contents can also be computed to be used later as the md5_checksum parameter in the inputFile constructor.

how we can create md5 hash of the file contents?

**Comment by ra0o0f** [comment]
```c#
// your file
byte[] data;
 string md5_checksum;
                          using (var md5 = MD5.Create())
                          {
                              var hash = md5.ComputeHash(data);
                              var hashResult = new StringBuilder(hash.Length * 2);

                              for (int i = 0; i < hash.Length; i++)
                                  hashResult.Append(hash[i].ToString("x2"));

                              md5_checksum = hashResult.ToString();
                          }
```

**Comment by DaveOff** [comment]
thankss raoof..

this is my split upload file, u see any problem ?

            ////md5
            var yu = File.ReadAllBytes("1.png");
            byte[] data = yu;
            string md5_checksum;
            using (var md5 = System.Security.Cryptography.MD5.Create())
            {
                var hash = md5.ComputeHash(data);
                var hashResult = new System.Text.StringBuilder(hash.Length * 2);

                for (int i = 0; i < hash.Length; i++)
                    hashResult.Append(hash[i].ToString("x2"));

                md5_checksum = hashResult.ToString();
            }


            //Upload
            long ti = numBytes / 1024;
            long read = 1024;

            for (int i = 0; i < ti; i++) {


                buff = br.ReadBytes((int)read);
                read = numBytes - read;

                if (buff != null)
                {
                    var request = new UploadPhoto(random_id, i, buff);
                    await _sender.Send(request);
                    await _sender.Recieve(request);
                }
           
            }

**Comment by ra0o0f** [comment]
you should know better, from what i read from https://core.telegram.org/api/files

`i` file part is correct(start from zero)
`random_id` you can use `DateTime.Now.Ticks` for it
`1024` is a valid part size

**Comment by DaveOff** [comment]
thanks,

if have big problem.

i uploading all part successfully but in 

var crtmedia = new InputMediaUploadedPhotoConstructor(new InputFileConstructor(random_id, ii, "1", md5_checksum));

i get Invalid checksum but i create md5 of file content....

**Comment by ra0o0f** [comment]
i finished the upload method, i will send the PR. i used same checksum method that i sent you. worked for me.

and one thing, i think file name should have extention => "1.jpg"

**Comment by DaveOff** [comment]
i try extention..

awsome i waiting for ur pr.

**Comment by dinhducit** [comment]
@ra0o0f can you send upload method to me, I really need it, thank so much :)

**Comment by ra0o0f** [comment]
@DaveOff @dinhducit PR is attached

usage
```c#
            var data = File.ReadAllBytes("file-path");
            var inputFile = await client.UploadFile("file-name-with-extention", data);
            
            var inputMedia = new InputMediaUploadedPhotoConstructor(inputFile);

            int? id = await client.ImportContact("phone-number");
            var inputPeer = new InputPeerContactConstructor(id.Value);

            var statedMessage = await client.SendMediaMessage(inputPeer, inputMedia);
```

**Comment by dinhducit** [comment]
@ra0o0f many thank :)

**Comment by dinhducit** [comment]
@ra0o0f I got error when testing your method: try to parse TLSharp.Core.MTProto.messages_StatedMessage, but incompatible type TLSharp.Core.MTProto.MessageConstructor

and I have a question, how I can send video by your method, I see inputMediaUploadedVideo contructor have: 

duration	int	Video duration in seconds
mime_type	string	MIME-type of the video file
Parameter added in Layer 13.
w	int	Width in pixels
h	int	Height in pixels

so where I can have duration, mime_type, w, h?

**Comment by ra0o0f** [comment]
check the tl types in telegram website and compare it to tl.cs file, it should be easy. If you changed the layer know that some types could be changed too.

**Comment by dinhducit** [comment]
@ra0o0f can u explain error: try to parse TLSharp.Core.MTProto.messages_StatedMessage, but incompatible type TLSharp.Core.MTProto.MessageConstructor

I debug and see datacode == code of MessageConstructor in TL file

**Comment by ra0o0f** [comment]
@dinhducit according to https://core.telegram.org/method/messages.sendMedia `messages.sendMedia` method could return's two types

1-messages.statedMessage#d07ae726
2-messages.statedMessageLink#a9af2881

these were added to tl.cs file and i used them without problem, maybe you changed the layer and types are changed.

**Comment by dinhducit** [comment]
@ra0o0f  yes in my TL.cs messages.statedMessage =  d07ae726
![1](https://cloud.githubusercontent.com/assets/13290578/12395064/136becda-be32-11e5-9aae-29c1edaed67e.png)
but I see I got different code from Telegram
![2](https://cloud.githubusercontent.com/assets/13290578/12395075/322f6174-be32-11e5-8b49-13026fe26256.png)

this code is MessageConstructor (not statedMessage)
![3](https://cloud.githubusercontent.com/assets/13290578/12395099/5128a176-be32-11e5-8b7b-916107d9d328.png)

so have any idea? and where I can check layer I used?

**Comment by ra0o0f** [comment]
try to print it to hex by `dataCode.ToString("X")`
`585853626` is `0x22eb6aba` which is `MessagConstructor`

you've seen the return type is `statedMessage` now it returns `message`, maybe this is not the response of the requested message. i have no any other idea

**Comment by hussein-shakiba** [comment]
hi i have on question
i want send caption for image but seen telgam api not supports this method:(

**Comment by ra0o0f** [comment]
@hussein-shakiba salam, added methods accept base classes for tl types, you should look for input media types which has `caption` attribute. take a look at tl.cs file

**Comment by hussein-shakiba** [comment]
mamnon ra0o0f:)) but not find method in tl with caption.

**Comment by sochix** [comment]
Basic usage added to Readme.md. See https://github.com/sochix/TLSharp#send-media-to-contact
