### ISSUE TITLE
Flood prevention Exception for SendCodeRequestAsync function

### ISSUE THREAD

**Issue by ParisaHatami** [sochix/TLSharp#635]
Hi guys!
I try to use my application but suddenly For using SendCodeRequestAsync function I get This Exception : 
"Flood prevention. Telegram now requires your program to do requests again only after 84894 seconds have passed (TimeToWait property). If you think the culprit of this problem may lie in TLSharp's implementation, open a Github issue "

after waiting for 84894 sec, It show me again this message.
(I wait and try several times but no different message :( )
what should I do?

**Comment by knocte** [comment]
Telegram API has some limitations. If Telegram's server reply to you with a FLOOD error, TLSharp library translates this error into a FloodException, that's all. This is not a bug in TLSharp (if you have proof that it is, please show us evidence).

Github issues is not a web forum, it's a place to report bugs. Thanks

**Comment by hosseinGanjyar** [comment]
I solved this issue. please send your question in my group:
https://t.me/joinchat/HhLHow3Ed97A0gRZo7Ggog

**Comment by amastaneh** [comment]
The problem solved and I hope this helps.
- Change phone number to international format started with `+` like `+989123456789`
- Change `SessionUserId` as session name  from `session` to a separated session for each user like `session_9123456789`
- Remove custom TcpClientConnectionHandler with custom IP and call `TelegramClient` with a null as handler (actually call it with just 4 parameters `apiId`, `apiHash`, `store` and `sessionUserId` without `handler`)

In my experience final sequence is 
```
1- Create an instance of TelegramClient
2- Call ConnectAsync
3- Call IsUserAuthorized
4- Call SendCodeRequestAsync (if step 3 is false)
...
```

**Comment by hosseinGanjyar** [comment]
Hi every body...You can ask your questions in this group:
https://t.me/joinchat/JRwh2w0A-7YlrMT_V4KhFQ
