### ISSUE TITLE
 AuthSendCodeRequest: Unable to read beyond the end of stream.

### ISSUE THREAD

**Issue by siml173** [sochix/TLSharp#64]
in following method : OnResponse in class : AuthSendCodeRequest
in following lines :

var sendCodeTimeout = reader.ReadInt32();
var isPassword = reader.ReadUInt32() == boolTrue;

it return an exception with following content : 
unable to read beyond the end of stream.

i think you should delete that two lines, because the do anything and are not used in any other place of class, just they are throwing error. ;-)

**Comment by sochix** [comment]
Provide stack trace and your code snippet.
