### ISSUE TITLE
is it possible to send multiple request in same time?

### ISSUE THREAD

**Issue by amin8811** [sochix/TLSharp#644]
All i want is to get updates and send message in same time, but i get error while calling update and send method together,
Also i tried using api in 2 different machine ,1 for send and 1 for receive, it seems we can't use token on more then 1 machine, getting AUTH_KEY_UNREGISTERED on another machine.

can anyone help me to find solution for these problems?

**Comment by knocte** [comment]
We don't use github issues as a forum, but as a way to report bugs in TLSharp library. For discussion, please join our gitter channel. Thanks
