### ISSUE TITLE
Remove UploadFile Method

### ISSUE THREAD

**Issue by Rasul-Jaber** [sochix/TLSharp#650]
Hi
I am trying to upload file with UploadFile method in new version(0.1.0.315) but this method is removed.
please help me to upload file with request.

**Comment by knocte** [comment]
The method is still there, look:

https://github.com/sochix/TLSharp/blob/master/TLSharp.Core/Utils/UploadHelper.cs#L79

So I'm closing this. Feel free to reopen if I had missed or overlooked anything.
