### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by karimzzzm** [sochix/TLSharp#658]
Hello everyone and do not be tired for everyone
Thanks for the one who answers me
How do I get out of my account?
Without clearing the cession file

**Comment by karimzzzm** [comment]
TelegramClient client = new TelegramClient(ApiId, ApiHash);
            await client.ConnectAsync();
            TLRequestLogOut g = new TLRequestLogOut();
            TLRequestSaveAppLog dd = new TLRequestSaveAppLog();
           var x = await client.SendRequestAsync <bool>(g);
           
            MessageBox.Show(x.ToString());




I wrote the code above but did not run
If you can get a code sample

**Comment by knocte** [comment]
What do you mean with "it did not run"???

**Comment by karimzzzm** [comment]
I mean
I want to be out of my account
But it is printed in the box of fals

**Comment by knocte** [comment]
What the fuck is a box of fals?

**Comment by karimzzzm** [comment]
MessageBox.Show(x.ToString());


This piece of Fals code is printed

**Comment by karimzzzm** [comment]
Dear friend, my goal is to leave the account
The method of getting out is not important
If you have code samples for this
give me please

**Comment by knocte** [comment]
> MessageBox.Show(x.ToString());
> This piece of Fals code is printed

What are you talking about? This doesn't make any sense.
If you're getting any exception report it here, pasting its whole stacktrace.

Reopen the bug when you have things more clear.
