### ISSUE TITLE
Formatted message

### ISSUE THREAD

**Issue by akartynnik** [sochix/TLSharp#660]
Hi all!
Guys, is it possible to send formatted message (html or murkdown) with TLSharp? 
In telegram API is written that we need just change **parse_mode** param in request.  Can I do it in TLSharp?
https://core.telegram.org/bots/api#html-style

UPD: I so several entities like `TLMessageEntityBold` in TLSharp code, but how I can use them for formatting me message?

**Comment by akartynnik** [comment]
UP

**Comment by knocte** [comment]
hi @akartynnik , sorry we don't use Github issues as a forum, it's only for reporting bugs. If you want to ask questions, use gitter.
