### ISSUE TITLE
RPC_MCGET_FAIL

### ISSUE THREAD

**Issue by icoreex** [sochix/TLSharp#662]
what is this error? RPC_MCGET_FAIL

**Comment by knocte** [comment]
Give more context please, we're not mind-readers. Do you get this inside an exception? If so, paste the whole stacktrace.

**Comment by moslem7026** [comment]
this error was because of Telegram own Server and solved .

**Comment by knocte** [comment]
What do you mean with "and solved"?

**Comment by icoreex** [comment]
it was telegram related issues
