### ISSUE TITLE
(Bug)infinit loop on TLSharp.Core.Network.UserMigrationException

### ISSUE THREAD

**Issue by moslem7026** [sochix/TLSharp#663]
after doing some work with api , a handled exception occured , `TLSharp.Core.Network.UserMigrationException` in description : "{"User located on a different DC: 4. See: https://github.com/sochix/TLSharp#i-get-a-xxxmigrationexception-or-a-migrate_x-error"}"  but this line of code run infinit loop and exception not ended unless via deleting session file and relogin in session . as run program again also not solving problem .
'https://github.com/sochix/TLSharp/blob/687eca968a64c8d3f489b1ad077e6c90cb59fa55/TLSharp.Core/TelegramClient.cs#L125'

**Comment by knocte** [comment]
I fail to see where's the infinite loop sorry. If you're so sure that there's an infinite loop there, can you please provide a PullRequest with the fix?

**Comment by giraffe81** [comment]
I have the same issue but cannot work out why it gets stuck in a loop. I can only assume it doesn't migrate DC successfully so keeps throwing the migration exception.

It appears to happen after you have migrated to a different DC to download an image. Then it never seems to migrate back to your phone DC.

**Comment by Mohfath** [comment]
I faced this problem too and searched the issues list to reach here.

As the giraffe81 says, I hit this problem when my soft was fetching profile pictures of all my users, after that it never gets past the DC migration error. unless I delete the session.dat file it never gets out of the DCMigration loop error.

Any Ideas so far??

**Comment by knocte** [comment]
No ideas, otherwise we would have already fixed it. Please debug it and provide a PullRequest.

**Comment by knocte** [comment]
The culprit seems to have been narrowed down in this other bug report: https://github.com/sochix/TLSharp/issues/719. So I'm closing this one as duplicate.

**Comment by pesar368** [comment]
i have this problem too.
My User located on DC : 4
With TLRequestGetNearestDc I found That My NearestDc is 2
Then ExportAuthorization To DC:2 Successfully
when use TLRequestGetNearestDc agein . say that My NearestDc is 2
means My Current Dc:2 and My NearestDc : 2
And This Make Loop.
