### ISSUE TITLE
How can i change C# code to VB for Tlsharp Dll

### ISSUE THREAD

**Issue by aliaus** [sochix/TLSharp#669]
Hi.
I want to start using Tlsharp in **vb.net** but I can't find any code for how using TL class in VB.
I changed this part with an online converter but that one not correct.
who can change this part for example?
who has more sample in vb.net?
Thank you.

```
//find recipient in contacts
        var user = result.users.lists
            .Where(x => x.GetType() == typeof(TLUser))
            .Cast<TLUser>()
            .Where(x => x.first_name == "ZRX");
        if (user.ToList().Count != 0)
        {
            foreach (var u in user)
            {
                if (u.phone.Contains("3965604"))
                {
                    //send message
                    await client.SendMessageAsync(new TLInputPeerUser() { user_id = u.id }, textBox3.Text);
                }
            }
```

**Comment by knocte** [comment]
@aliaus thanks for using TLSharp. However, we use Github Issues for reporting library bugs, not as a forum. If you want to discuss about TLSharp, join our gitter channel. Thanks!
