### ISSUE TITLE
InvalidOperationException Receieve()

### ISSUE THREAD

**Issue by DaveOff** [sochix/TLSharp#67]
hi in Task<TcpMessage> Receieve()

           if (await stream.ReadAsync(packetLengthBytes, 0, 4) != 4)
              throw new InvalidOperationException("Couldn't read the packet length");

how i can if Couldn't read the packet length, return and start again ? becuse by  InvalidOperationException all of program stop working

and what is reason of Couldn't read the packet length ?

on 3 try to connect i get 2 Couldn't read the packet length

**Comment by ra0o0f** [comment]
occurred for me too, if i'm not wrong when `ReadAsync` method returns zero then probably the remote server closes the tcp socket, and new `TcpClient` should be initialize again. @sochix may have an opinion

**Comment by DaveOff** [comment]
thats so many class and part of part and i confused and can't figure that but maybe that work :


            if (await stream.ReadAsync(packetLengthBytes, 0, 4) != 4)
                await stream.ReadAsync(packetLengthBytes, 0, 4);


:D

**Comment by ra0o0f** [comment]
wouldn't work i think, the socket is closed already

**Comment by afraz92** [comment]
Is there any idea about this?

**Comment by headria** [comment]
i got it too , every have an idea please help

**Comment by sochix** [comment]
You can try to call client.Connect(true). Which will perform reconnection.
