### ISSUE TITLE
Program freeze when cast type

### ISSUE THREAD

**Issue by TheTrigger** [sochix/TLSharp#676]
```
foreach (var dialog in dialogs.Dialogs.Where(x => x.Peer is TLPeerChat)) {
    TLPeerChat peer = (TLPeerChat)dialog.Peer;
```
As in this example, the cast blocks the execution, without generate errors.

**Comment by ppanhoto78** [comment]
Had the same problem when I to `GetFullChat` on a Channel. Since Level 72, there is a new message `ChannelFull`.

**Comment by knocte** [comment]
Can you post the whole (ex.ToString()) text? Thanks

**Comment by TheTrigger** [comment]
There are no exceptions, if you mean that

**Comment by knocte** [comment]
You claiming that the execution of code stops when casting? with no exception whatsoever? This must be a bug in your program, doesn't look a problem in TLSharp.

**Comment by TheTrigger** [comment]
It's like an infinite loop
`var peer = dialog.Peer;` works.
`TLPeerChat peer = (TLPeerChat)dialog.Peer;` doesn't work.
`TLPeerChat peer = dialog.Peer as TLPeerChat` instead, gives NULL and goes on

![image](https://user-images.githubusercontent.com/6072718/37338840-e9587da4-26b8-11e8-9991-7b508740bf6b.png)
![image](https://user-images.githubusercontent.com/6072718/37338702-85820eb2-26b8-11e8-8d33-56ab8826368d.png)
Then if i continue the execution, it's like freezed. No cpu usage, no errors. 

am i doing something wrong?

**Comment by knocte** [comment]
Show the full code.

**Comment by TheTrigger** [comment]
```
public int ApiId { get; private set; } = ...;
public string ApiHash { get; private set; } = "....";
public string PhoneNumber { get; private set; } = "+....";
public int UserId { get; private set; } = ...;

public TelegramClient Client { get; private set; }

private TLUser User { get; set; }
```


```
public async Task<bool> Start()
{
	try
	{
		var sessionstore = new SessionStore();

		Client = new TelegramClient(ApiId, ApiHash, sessionstore, $"{UserId}");
		await Client.ConnectAsync();

		if (!Client.IsConnected)
			throw new Exception("Unable to connect");

		if (!Client.IsUserAuthorized())
		{
			User = await Auth();
		}
		else
		{
			Console.WriteLine("Authorized");
		}
	}
	catch (Exception)
	{
		throw;
	}

	return true;
}
```

```
public async Task<TLUser> Auth()
{
	var hash = await Client.SendCodeRequestAsync(PhoneNumber);
	var code = "55693"; // you can change code in debugger

	return await Client.MakeAuthAsync(PhoneNumber, hash, code);
}
```

Called after Start();
```
public async Task LineCmd()
{
	while (true)
	{
		var cmd = Console.ReadLine();

		switch (cmd)
		{
			case "self":
				await Client.SendMessageAsync(new TLInputPeerUser() { UserId = UserId }, "Message from tlsharp");
				break;

			case "show contacts":
				var result = Client.GetContactsAsync().Result;

				foreach (var u in result.Users.Cast<TLUser>())
				{
					Console.WriteLine($"{u.FirstName}	{u.Id}	{u.Phone}	{u.Status}	{u.Verified}");
				}

				break;

			case "dialogs":
				TLDialogsSlice dialogs = (TLDialogsSlice)await Client.GetUserDialogsAsync();

				if (dialogs != null)
				{
					Console.WriteLine($"Chat con utenti: {dialogs.Chats.Count}");
					Console.WriteLine($"Dialogs: {dialogs.Dialogs.Count}");
					
					foreach (var dialog in dialogs.Dialogs)
					{
						//TLPeerChat peer = dialog.Peer as TLPeerChat;
						TLPeerChat peer = (TLPeerChat)dialog.Peer;

						TLChat chat = null;

						foreach (TLChat c in dialogs.Chats)
						{
							if (c.Id == peer.ChatId)
							{
								Console.Write("!");
								chat = c;
							}
							else
							{
								Console.Write(".");
							}
						}

						Console.WriteLine($"{chat.Title} => {chat.Id}");
					}
				}
			}
		}
	}
```


SessionStore.cs
```
public class SessionStore : ISessionStore
{
	public string FilePath = Directory.GetCurrentDirectory() + @"\{0}.dat";

	public void Save(Session session)
	{
		using (var fileStream = new FileStream(string.Format(FilePath, session.SessionUserId), FileMode.OpenOrCreate))
		{
			byte[] bytes = session.ToBytes();
			fileStream.Write(bytes, 0, bytes.Length);
		}
	}

	public Session Load(string sessionUserId)
	{
		string path = string.Format(FilePath, sessionUserId);
		if (!File.Exists(path))
			return null;

		var buffer = File.ReadAllBytes(path);
		return Session.FromBytes(buffer, this, sessionUserId);
	}
}
```

**Comment by ppanhoto78** [comment]
I stumbled over a similar problem that could be regarded as an infinite loop with a TLDialogsSlice. Problem is the API GetUserDialogsAsync fixes the offset to 0 and limits to 100 results. A second call to GetUserDialogsAsync would yield the same results as the first and so on. In my repo, I've modified this call to accept an optional offset parameter so that further calls can iterate correctly.

**Comment by knocte** [comment]
@ppanhoto78 can you separate that change into a PR please? (only this change)

**Comment by knocte** [comment]
Hey @TheTrigger , since you reported this bug, there have been 2 commits which might possibly help around this issue: f2a394ea15d14a5482cd815c4b5c2b9c672abf0e (which is related to what @ppanhoto78 mentioned) and 60a3c6235792163e9c74e9c24b1ca7800a220ce2 (which could have been causing the problem that you described with the word "freeze" but might as well just an infinite loop).

Do you mind updating to use latest master (not sure when the new version will hit nuget.org though, use sources for now)? If after that you keep having this issue please reopen this bug.
