### ISSUE TITLE
How to get all messages in channel?

### ISSUE THREAD

**Issue by prog9016** [sochix/TLSharp#680]
How to read all messages in channel into textbox ?
Help Me 
please put this code
Thank You

**Comment by prog9016** [comment]
Help Me

**Comment by prog9016** [comment]
1

**Comment by messire** [comment]
use GetHistoryAsync method

public Task<TLAbsMessages> GetHistoryAsync(**TLAbsInputPeer** peer, **int** offset, **int** max_id, **int** limit);

offset - is offset from last message
limit - max messeges from one requiest (100 max)

something that for example:
var peer = new TLInputPeerUser() { UserId = UserId, AccessHash = AccessHash };
var client = new TelegramClient(Api_Id, Api_Hash);

int max_id = GetLastId();
int msgCount = 100;

for (int offset = 0;offset < lastMessage + 1; offset += 100)
{
    var messages = await client.GetHistoryAsync(peer, offset, max_id, msgCount)
    ...
    Thread.Sleep(1200);
}

**Comment by tokp** [comment]
I not found GetLastId() in any part of TLSharp code. How can I access to last channel id?

**Comment by knocte** [comment]
We don't use github issues as a forum, but as a way to report bugs in TLSharp library. For discussion, please join our gitter channel. Thanks
