### ISSUE TITLE
Username message

### ISSUE THREAD

**Issue by TooLazyy** [sochix/TLSharp#683]
Can i send message to user by its username?
In telegram desktop or web or mobile i can just search for user by username and send message.
Is it private api?

**Comment by MahdiHosseiniOfficial** [comment]
hi yes you must search user with SearchUserAsync method then send message or forward message or Everything else

**Comment by TooLazyy** [comment]
Thanks

**Comment by MahdiHosseiniOfficial** [comment]
Your Welcome

**Comment by knocte** [comment]
We use github issues as a platform for reporting bugs, not as a forum. To join the debate, use our gitter channel. Thanks!
