### ISSUE TITLE
Bot Start Button

### ISSUE THREAD

**Issue by byHappyCV** [sochix/TLSharp#684]
Hi!
I have a problem.
I have a bot and I want to start interacting with it, but I can not figure out how to press the start button, which is responsible for activating the bot.
I tried to look for it in updates, but there was nothing. The only thing I found is the TLRequestStartBot(not in updates). But I have no idea how to use it. I am familiar with the data of Peer and Bot.
I read some informanion about Deep linking, but I have not figured out how to solve my problem(

TLRequestStartBot start = new TLRequestStartBot();

var req = await client.SendRequestAsync?????

![default](https://user-images.githubusercontent.com/35576408/35116279-8ebb4376-fc93-11e7-9589-058a03216f0c.PNG)

Can you help me to solve my problem?

**Comment by knocte** [comment]
We use github issues as a platform for reporting bugs, not as a forum. To join the debate, use our gitter channel. Thanks!
