### ISSUE TITLE
Add member to channel

### ISSUE THREAD

**Issue by hanigamini** [sochix/TLSharp#688]
Hello, is there anyone to know, how I can add contact to telegram channel via c#?
Thanks.

**Comment by amirvenus** [comment]
One simple method (perhaps a hack) would be to send them the invite link to the channel.

**Comment by hanigamini** [comment]
Hi,
@amirvenus thanks,
how I can add contact by phone numbers? i want do not display my phone to them

**Comment by knocte** [comment]
We use github issues as a platform for reporting bugs, not as a forum. To join the debate, use our gitter channel. Thanks!
