### ISSUE TITLE
Problem while using assemblies TLABDialogs & using TLSharp.Core;

### ISSUE THREAD

**Issue by amirvenus** [sochix/TLSharp#689]
Hi,
I am developing a very simple C# Console Based client and I am just following the sample codes provided in Github. 

I have included the following assemblies: 

```
using TLSharp;
using TeleSharp.TL;
using TLSharp.Core;
```

But when I want to use the following code to get the channel lists:

```
     //get user dialogs
            var dialogs = await tclient.GetUserDialogsAsync();

  var chat = dialogs.chats.lists
    .Where(c => c.GetType() == typeof(TLChannel))
    .Cast<TLChannel>()
    .FirstOrDefault();
```

I receive an error:

 Error CS1061: 'TLAbsDialogs' does not contain a definition for 'chats' and no extension method 'chats' accepting a first argument of type 'TLAbsDialogs' could be found (are you missing a using directive or an assembly reference?)

**Comment by knocte** [comment]
Try `Chats` instead? Our docs may be outdated.

**Comment by amirvenus** [comment]
The problem is that dialogs does not appear to contain anything such as Chats, chats, etc

But when I remove using TLSharp.Core, I can access .chats property of it but then I won’t be able to create the client as it complains assembly not found.

**Comment by amirvenus** [comment]
Solved: I needed a cast
