### ISSUE TITLE
Geochat

### ISSUE THREAD

**Issue by ram-sh** [sochix/TLSharp#690]
Hello Ilya P,

Your project is more than awesome!! many thanks for your time and effort and for all those who contribute to it!

I am looking to develop a Geochat room, any thoughts on that subject? I couldn't find any implementation of it  anywhere ...

Wish you nothing but the best!
Ram

**Comment by knocte** [comment]
Github issues is for reporting bugs. This is not a forum. Check our gitter room if you want to discuss the project.
