### ISSUE TITLE
how to select the user?????

### ISSUE THREAD

**Issue by Axe-Usa** [sochix/TLSharp#699]
i do this for searching contacts
```
 foreach (object list in (await Program.client.SendRequestAsync<TLImportedContacts>((TLMethod) requestImportContacts)).users.lists)
          {
          	
            
          }
```

Now how can i select the user to send the message?

**Comment by knocte** [comment]
We don't use github issues as a forum, but as a way to report bugs in TLSharp library. For discussion, please join our gitter channel. Thanks
