### ISSUE TITLE
Channel API

### ISSUE THREAD

**Issue by DaveOff** [sochix/TLSharp#70]
hi, can we work on channel by telegram api ?

**Comment by keyvanarasteh** [comment]
i could'nt find any Methods about Telegram Channel Methods in telegram.org :-1:

**Comment by keyvanarasteh** [comment]
#80 Here i found something help to implement in TLSharp :-( Thanks

**Comment by arfprogrammer** [comment]
the list of last schema of telegram is [here](https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/mtproto/scheme.tl)
with this you can do every thing with telegram

**Comment by aghamohammadi** [comment]
@sochix which schema is for send message to channel?
i dont found!

**Comment by aghamohammadi** [comment]
error to create channel :
"try to parse TLSharp.Core.MTProto.Updates, but incompatible type TLSharp.Core.MTProto.Messages_channelMessagesConstructor"

**Comment by keyvanarasteh** [comment]
@aghamohammadi : You cant parse because there is no implementation for Updates in @sochix 's TL.cs.

you have to code layer 45 or another layer TL.cs for your usage.

yekam sakhte, movafag bashi <3

**Comment by aghamohammadi** [comment]
@keyvanarasteh 
can you impliment's?

**Comment by DrEhsan** [comment]
@aghamohammadi kare sakhti nis dost aziz awal az hame baiad moge bargarari session laye 45 ro befresti va badesh kole Construction haye dakhel TL.cs ro tebg handle haye mojod dar laye 45 baz nevisi koni. 

be tor messal UserSelfConstructor dar har laye field ha va header motefavet dare ke baiad ona ro dubare benevisi chizi ke alan SharpTL dare bara laye 23 has va dar laye 23 shoma nemituni ro channel ha dasrasi dashte bashi.

pas baiad tamam field haye packet UserSelfConstructor  ro dubare motenaseb ba packet laye 45 benevisi ta parser betune onu durus parse kone. degat kon ke agar yek field invar onvar beshe kole packet kharab mishe va barname ya crash khahad dad ya inke kolan etelaat galat migiri.

sakht nis ama hajme karesh ziade va degat ziadi ham mikhad.

kole field haye mojod ro mituni az source zir peida koni : 

https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/mtproto/scheme.tl

dar zemn pishnahad mikonam ta kami ham ba packeting ashena beshin onvag 2 sute halesh mikoni 

movafag bashi.

**Comment by aghamohammadi** [comment]
mamnun az pasokhet
shoma mostanadi az laye 45 dari?
ru sitesh peyda nakardam!

**Comment by DrEhsan** [comment]
mostanadesh hamin link has ke to comment gabli dadam behet.
source telegram desktop az laye 45 estefade mikone ke shamel super group ha va channel ha mishe.
tamami function ha neveshte shodan to un link. va jeloshun ham shomare hexadecimal packet hast.

va field haye mored niaz ham baraye sakht packet ham jelosh hast.

agar az pushe Requests chand ta ro mored barasi garar bedi va ba API haye mojud dar khode telegram.org check koni be C# mosalat bashi va inke kami az packeting beduni rahat mifahmi chi be chie.

badesh ke protocol ro fahmidi mituni onu be laye 45 ba estefade az link ke dadam behet ertegash bedi.

**Comment by naa3er** [comment]
ba salam khedmat asatid
mishe dar morede flags bishtar tozih bedid
har ja ro gashatam be natije naresidam
ba tashakor

**Comment by hadi77ir** [comment]
@naa3er If you want to know more about `flags` property, you should take a look at Telegram for Android: [DrKLO/Telegram](https;//github.com/DrKLO/Telegram).
