### ISSUE TITLE
Using this library blocks the API for my number(s) for 24H

### ISSUE THREAD

**Issue by grasmanek94** [sochix/TLSharp#703]
So I tried telegram-cli and that works fine for doing stuff, but when using this library to do *anything*, the number is blocked for 24H from issuing authentication api requests.. so I can not login for 24H wherever. telegram-cli works fine again after 24H (relogin by clearing session) and can login as many times as I want with telegram-cli. This library does something that Telegram doesn't like and blocks everyone using it...

    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading;
    using System.Threading.Tasks;
    using TeleSharp.TL;
    using TLSharp.Core;

    namespace TelegramMonitor
    {
        class Program
        {
            public static object TimeSpam { get; private set; }

            static void Main(string[] args)
            {
                MainAsync().Wait();
            }

            static async Task MainAsync()
            {
                Int64 unixTimestamp = (Int64)(DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1))).TotalMilliseconds;
                Random rnd = new Random((int)unixTimestamp);
                var client = new TelegramClient(********, "********");
                await client.ConnectAsync();
                Thread.Sleep(100 + rnd.Next(100, 500));

                var hash = await client.SendCodeRequestAsync("+**********");
                Thread.Sleep(100 + rnd.Next(100, 500));

                Console.WriteLine("Code: ");
                var code = Console.ReadLine().Trim(new char[3] { ' ', '\n', '\r' }); // you can change code in debugger

                var logged_in_user = await client.MakeAuthAsync("+**********", hash, code);
                Thread.Sleep(100 + rnd.Next(100, 500));

                //get available contacts
                var result = await client.GetContactsAsync();
                Thread.Sleep(100 + rnd.Next(100, 500));

                //find recipient in contacts
                var user = result.Users
                    .Where(x => x.GetType() == typeof(TLUser))
                    .Cast<TLUser>()
                    .FirstOrDefault(x => x.Phone == "+**********");
                Thread.Sleep(100 + rnd.Next(100, 500));

                //send message
                await client.SendMessageAsync(new TLInputPeerUser() { UserId = user.Id }, "Test");
                Thread.Sleep(100 + rnd.Next(100, 500));
            }
        }
    }

**Comment by Axe-Usa** [comment]
the project is a little forgotten need updates .

**Comment by hosseinGanjyar** [comment]
Hi...send question in my group
https://t.me/joinchat/HhLHow3Ed97A0gRZo7Ggog
I solved this last month

**Comment by bumpdone** [comment]
You do not need to receive and enter the code every time, once you have authenticated one time you get an auth_key_id which i believe is stored in the session.dat file. You can then use IsUserAuthorized() to check if you have already been authorized and then you will not need to keep entering the code. This solved the problem for me. Something like this:

```c#
        private async Task AuthenticateUser(TelegramClient client)
        {
            if (!client.IsUserAuthorized())
            {
                var hash = await client.SendCodeRequestAsync("xxxxxxxxxxxx");
                var code = "xxxxx";
                await client.MakeAuthAsync("xxxxxxxxxxxx", hash, code);
            }
        }
```

**Comment by grasmanek94** [comment]
Oh that explains it, thanks for the help everyone :)
