### ISSUE TITLE
working with TLAbsReplyMarkup to reply ReplyMarkup of telegram bot

### ISSUE THREAD

**Issue by khang0001** [sochix/TLSharp#707]
I want to click button markup of bot as this photo
![untitled](https://user-images.githubusercontent.com/20863676/36323488-a78579a6-1383-11e8-8194-82e6e2434f8e.png)
I found method TLRequestSendMessage can support TLAbsReplyMarkup. This is my code

// read history message to get ReplyMarkup
var target = new TLInputPeerUser() { UserId = 1111111, AccessHash = 111111111 };
var hist = await client.GetHistoryAsync(target, 0, 0, 10);

// get ReplyMarkup
var tlChannelMessages = (TLMessagesSlice)hist;
var TmpVar1 = tlChannelMessages.Messages[2];
var TmpVar2 = (TLMessage)TmpVar1;
var ReplyMarkup = TmpVar2.ReplyMarkup;

// send request

 var req = new TLRequestSendMessage()
            {
                Peer = target,
                Message = "test",
                RandomId = TLSharp.Core.Utils.Helpers.GenerateRandomLong(),
                ReplyMarkup = ReplyMarkup 
        };
            await client.SendRequestAsync<TLAbsUpdates>(req);

But i don't work. Always send text is test. And not click button markup. How can I fix it?

**Comment by khang0001** [comment]
No update because I need some one help me

**Comment by pingudiavel** [comment]
PM at pingudiavel@gmail.com

**Comment by tuananh14391** [comment]
> I want to click button markup of bot as this photo
> ![untitled](https://user-images.githubusercontent.com/20863676/36323488-a78579a6-1383-11e8-8194-82e6e2434f8e.png)
> I found method TLRequestSendMessage can support TLAbsReplyMarkup. This is my code
> 
> // read history message to get ReplyMarkup
> var target = new TLInputPeerUser() { UserId = 1111111, AccessHash = 111111111 };
> var hist = await client.GetHistoryAsync(target, 0, 0, 10);
> 
> // get ReplyMarkup
> var tlChannelMessages = (TLMessagesSlice)hist;
> var TmpVar1 = tlChannelMessages.Messages[2];
> var TmpVar2 = (TLMessage)TmpVar1;
> var ReplyMarkup = TmpVar2.ReplyMarkup;
> 
> // send request
> 
> var req = new TLRequestSendMessage()
> {
> Peer = target,
> Message = "test",
> RandomId = TLSharp.Core.Utils.Helpers.GenerateRandomLong(),
> ReplyMarkup = ReplyMarkup
> };
> await client.SendRequestAsync(req);
> 
> But i don't work. Always send text is test. And not click button markup. How can I fix it?

Any updates ? Can you share code?

**Comment by pingudiavel** [comment]
https://github.com/pingudiavel/TLCSharp

**Comment by pingudiavel** [comment]
@tuananh14391 

https://github.com/pingudiavel/TLCSharp

**Comment by tuananh14391** [comment]
> @tuananh14391
> 
> https://github.com/pingudiavel/TLCSharp

The line:  TLReplyInlineMarkup List_InlineButtons = message.ReplyMarkup as TLReplyInlineMarkup;
is always null because message.ReplyMarkup can't convert to TLReplyInlineMarkup
