### ISSUE TITLE
trying to make auth for two number

### ISSUE THREAD

**Issue by DaveOff** [sochix/TLSharp#71]
i created two num1.dat num2.dat but when connect in loop :+1: 

            var client = new TelegramClient(store, num1.dat (next time num2.dat));
            await client.Connect();

i get msg_seqno error
where is my problem and whats is soloution ?

tnk

**Comment by sochix** [comment]
you need to properly close TelegramClient. try to wrap it with using.

```
using(var client = new TelegramClient(store, num1.dat)) 
{
       await client.Connect();
}

using(var client = new TelegramClient(store, num2.dat)) 
{
       await client.Connect();
}
 ```
