### ISSUE TITLE
Can Send Vector

### ISSUE THREAD

**Issue by hamedmaleki1366** [sochix/TLSharp#72]
Hi , in this Codes. we only get vector on OnResponse , but there is'nt code to send Vector or other lists to telegram api.

can you explain me one message sending with vector like sendmessageBroadcast?

**Comment by dinhducit** [comment]
Here is my code:

public class SendBroadcastRequest : MTProtoRequest
    {
        private readonly List<InputUser> _id;
        private readonly string _message;
        private readonly InputMedia _media;
        public messages_StatedMessages StatedMessages { get; set; }
        public SendBroadcastRequest(List<InputUser> id, string message = "", InputMedia media = null)
        {
            _id = id;
            _message = message;
            _media = media;
        }

        public override void OnSend(BinaryWriter writer)
        {
            writer.Write(0x41bb0972);
            writer.Write(0x1cb5c415); // vector#1cb5c415
            writer.Write(_id.Count); // vector length
            foreach (var id in _id)
                id.Write(writer);

            if (!string.IsNullOrWhiteSpace(_message))
                Serializers.String.write(writer, _message);
            _media?.Write(writer);
        }

        public override void OnResponse(BinaryReader reader)
        {
            var code = reader.ReadUInt32();
            if (code != 0x969478bb && code != 0x3e74f5c6)
                throw new InvalidOperationException($"Expected Tl messages_StatedMessages type");

            StatedMessages = TL.Parse<messages_StatedMessages>(reader);
        }

        public override void OnException(Exception exception)
        {
            throw new NotImplementedException();
        }

        public override bool Confirmed => true;
        public override bool Responded { get; }
    }

But I got error: Broadcast is disable :)

**Comment by bemaxima** [comment]
I get the same error.
I tied to bring up this issue with telegram support team. but they hasn't respond yet.

**Comment by hamedmaleki1366** [comment]
thank you, dinhducit.

what is type of List _id; if this is List<InputUser> , i have only user_id of contacts , how can convert  user_id (int) to InputUser?

**Comment by dinhducit** [comment]
sample code:

//var data = System.IO.File.ReadAllBytes(@"E:\1.jpg");
            //var inputFile = await client.UploadFile("1.jpg", data);

            //var inputMedia = new InputMediaUploadedPhotoConstructor(inputFile);

            //var user1 = await client.ImportContact("+841689945117");
            //var user2 = await client.ImportContact("+84973986702");
            ////var inputPeer = new InputPeerContactConstructor(res.Value);

            //var message = @"Test send broadcast";
            //var users = new List<InputUser>
            //{
            //    new InputUserContactConstructor(user1.Value),
            //    new InputUserContactConstructor(user2.Value)
            //};

            //var statedMessages = await client.SendBroadcast(users, message, inputMedia);

**Comment by eaba** [comment]
Is the broadcast feature still alive?
