### ISSUE TITLE
Channel participants limit

### ISSUE THREAD

**Issue by programmermeus** [sochix/TLSharp#720]
Is there any limit to request get all chat members? Why can I take just 10 000 members? A few months ago Durov sad that group size was increased from 10 000 to 75 000 members. Was it implemented in TLSharp?

**Comment by knocte** [comment]
Welcome to TLSharp. We don't use Github issues as a forum, but as a way to report bugs. To engage in conversations about TLSharp please use our gitter or telegram channels.
