### ISSUE TITLE
Отправка сообщений без авторизации

### ISSUE THREAD

**Issue by Kingmidas74** [sochix/TLSharp#721]
Здравствуйте.
Во всех примерах по отправке сообщений присутствует чудо-строка c переменной code, которую нужно либо каждый раз считывать у пользователя, либо править через отладчик. Получается, что сделать сервис, который бы отсылал сообщения конкретному пользователю не получится?
Скажем висит себе одинокий обработчик SendTLMessage.ashx, который гет параметром принимает номер и текст сообщения. Но вот код-то приходит на телефон мне. Как быть?

**Comment by knocte** [comment]
English please.
