### ISSUE TITLE
two step verification (2FA)

### ISSUE THREAD

**Issue by pishgaman-org** [sochix/TLSharp#725]
hi
when I try login to an account, SESSION_PASSWORD_NEEDED exception occurs.
by Telegram Desktop, it show me a button "Remove cloud password" and after clicking, it removes account password and makes a fresh account.
how could I do this by tlsharp?

**Comment by knocte** [comment]
> SESSION_PASSWORD_NEEDED exception occurs

Please paste the whole `ex.ToString()`

**Comment by pishgaman-org** [comment]
why? it is completely clear. there is nothing wrong in program code. the account is protected with two step verification. I want to remove its password by Tlsharp. I can do this by Telegram Desktop simply.

**Comment by knocte** [comment]
We want whole stacktraces when people report exceptions in bugs.

**Comment by pishgaman-org** [comment]
I have not stack trace log at this time. exception is not important.
just help me how to remove cloud password of account when try signing in by Tlsharp.

**Comment by knocte** [comment]
This is not a forum, you're filing a github issue, which means you're filing a bug. If you want to discuss the usage of TLSharp, use our gitter or telegram channels.

**Comment by pishgaman-org** [comment]
this is not issue?! I tried login to an account by Tlsharp that is password protected and I have not its password so it show me "SESSION_PASSWORD_NEEDED" then you ask me for stack trace!
Just say I don't know.

**Comment by knocte** [comment]
You mentioned an exception. If you're filing a bug where there's an exception involved, you need to provide all the details about the exception. If you're not willing to provide this information, I will close this issue.

**Comment by pishgaman-org** [comment]
I close this myself. I thought wrongly you are here to help others.

**Comment by knocte** [comment]
As I said, you can ask for help in our telegram/gitter channels. We use github issues for reporting bugs in the library.
