### ISSUE TITLE
Notifications about new messages

### ISSUE THREAD

**Issue by siberianguy** [sochix/TLSharp#730]
Bot Api has a way to get notifications about new messages. Is there similar functionality for non-bot api implemented by TLSharp? All I see now is getHistory but if you need to be notified often (at least once a second), I'm afraid it will result in flood prevention error message.

**Comment by hosseinGanjyar** [comment]
Hi every body...You can ask your questions in this group:
https://t.me/joinchat/JRwh2w0A-7YlrMT_V4KhFQ
