### ISSUE TITLE
Don't log out on app close

### ISSUE THREAD

**Issue by Shifu462** [sochix/TLSharp#733]
How to make my app save anything like access token for further login without sending SMS to my phone?

I mean, at first I send code to my phone:
`var hash = await Client.SendCodeRequestAsync(phone);`

Then I make auth to my account with the code from SMS:
`var user = await Client.MakeAuthAsync(phone, hash, code);`

Ok, now I'm logged in. But if I restart my app, it will send SMS again, and I'll have to do the same, despite I've logged in just a minute ago, but inside of another instance of my app.
 
**How can I save some kind of access token so I don't need to log in through phone again?**

**Comment by knocte** [comment]
This is a recurrent question by new users of TLSharp. I believed you're already being helped on our telegram channel, but it would be great if you could contribute a PullRequest to change our README file to make this more clear (adding a code snippet).

**Comment by Shifu462** [comment]
@knocte 
I've created this issue before wrote the same message on the telegram channel.
 
Of course, would be glad contribute, after I finally figure out how to do that :)
