### ISSUE TITLE
Resolving username

### ISSUE THREAD

**Issue by m-rain** [sochix/TLSharp#74]
Hi

I tried to resolve the username but I failed and got some errors 

I could not find the resolve username documentation in telegrams official web site, It seems they deleted it.

Can someone help me on this??

**Comment by bemaxima** [comment]
https://core.telegram.org/method/account.checkUsername

**Comment by m-rain** [comment]
Thank you but checkUsername just checks if username is taken or not.

I need to get user or channel info by its username

The problem is on OnResponse method where I don't know how to get response

**Comment by bemaxima** [comment]
Based on which api method, you are trying to get and parse response !?

**Comment by sochix** [comment]
Import user by phoneNumber -> get a user Name. See Tests for Importing.

**Comment by sochix** [comment]
See ImportByUserNameAndSendMessage test. Just implemented this functionality.
