### ISSUE TITLE
Update Username works incorrectly

### ISSUE THREAD

**Issue by CheshireCaat** [sochix/TLSharp#740]
I try this code:

```
    var req = new TeleSharp.TL.Account.TLRequestUpdateUsername() { Username = oldNick };
    var oks =   client.SendRequestAsync<TLUpdateUserName>(req).IsCompleted;
    if (oks)
    {
        TS("yes");
    }
    else
    {
        TS("no");
    }
```

I get oks == false, but the nickname has been changed successfully
Is this a bug or am I doing something wrong?

**Comment by knocte** [comment]
IsCompleted is a property that is in Task&lt;T&gt: class, it's not part of TLSharp API. This property just tells you that the asynchronous task has been finished.
