### ISSUE TITLE
TLRequestImportContacts works randomly!?

### ISSUE THREAD

**Issue by CheshireCaat** [sochix/TLSharp#741]
Why does TLRequestImportContacts work randomly for different sessions?
There is a list of 100 phones.
For one account everything is added, for another account only ~ 20
What is the reason?

**Comment by CheshireCaat** [comment]
My code:
` for (int i = 0; i < 100; i++)
                {
                    var num = lines[i];

                    var phoneContact = new TLInputPhoneContact()
                    {
                        Phone = num,
                        FirstName = fname,
                        LastName = lname
                    };
                    contacts.Add(phoneContact);

                    if (i % 5 == 0 && i != 0)
                    {
                        var req = new TLRequestImportContacts() { Contacts = contacts };
                        req.Replace = true;

                        var cont = await client.SendRequestAsync<TLRequestImportContacts>(req);
                        var nUsers = cont.Contacts;
                        int cst = nUsers.Count;
                        

                        foreach (var nUser in nUsers)
                        {
                            
                            CheckRez.AppendText(nUser.Phone + Environment.NewLine);
                                  

                        }



                        contacts.Clear();
                        await TaskEx.Delay(10000);
                    }`

**Comment by jefferyleo** [comment]
Your code able to import contact? I got the same code as you, but what happen is my contact doesn't even save into my account, no idea why
