### ISSUE TITLE
change InvokeWithLayer

### ISSUE THREAD

**Issue by m-rain** [sochix/TLSharp#75]
Hi

Should I update Invoke with layer in source to da9b0d0d?

because it's in the official telegram website

**Comment by sochix** [comment]
What the reason?

**Comment by m-rain** [comment]
I need some new api features.

when i use invoke by 0xda9b0d0d and layer 45 app throws an error:

> An exception of type 'Ionic.Zlib.ZlibException' occurred in mscorlib.dll but was not handled in user > code
> Additional information: Bad CRC32 in GZIP trailer. (actual(DD2AD780)!=expected(4D201CB3))

**Comment by m-rain** [comment]
When i send 0xf93ccba3 , telegram sends 0x75cf7a8 which is for an old type of UserForeignContstractor instead of 0x5214c89d or 0x7f077ad9 (which contains users and chats together)

Am I doing something wrong?? Or its because i'm using old layer type??

**Comment by sochix** [comment]
Yep, try changing a layer

**Comment by m-rain** [comment]
The problem is when I use layer greater than 22

```
writer.Write(0xda9b0d0d); // invokeWithLayer10#39620c41, invokeWithLayer11#a6b88fdf
writer.Write(23);
```
 This error occurs:
An exception of type 'System.OutOfMemoryException' occurred in mscorlib.dll but was not handled in user code

```
writer.Write(0xda9b0d0d); // invokeWithLayer10#39620c41, invokeWithLayer11#a6b88fdf
writer.Write(45);
```
This error occurs:
An exception of type 'Ionic.Zlib.ZlibException' occurred in mscorlib.dll but was not handled in user code


Is there something else I should change?? or The library does not support layer greater than 22??

**Comment by sochix** [comment]
Layer changed to 23
