### ISSUE TITLE
Unable to import contacts

### ISSUE THREAD

**Issue by jefferyleo** [sochix/TLSharp#753]
```
var contacts = new TLVector<TLInputPhoneContact>();
            contacts.Add(new TLInputPhoneContact { FirstName = "Test", LastName = "Test", Phone = "60123456789" });
            //Create request 
            var req = new TLRequestImportContacts()
            {
                Contacts = contacts
            };
            var test = await client.SendRequestAsync<TLImportedContacts>(req);
```

I've write the import contact code which I refer from some of the solutions, however, I'm unable to create the contact still after I run the code.
The result telling me `Enumeration yielded no results`

Any others way to import contact by using TLSharp?

**Comment by jefferyleo** [comment]
I'm able to add the contact finally, I found out it's unable to add contact with invalid phone numbers, which it's checked by telegram side i guess.

**Comment by raso03031983** [comment]
if it were not for your information I would still be looking for the right information. Thanks for sharing
