### ISSUE TITLE
无法将数据写入传输连接: 远程主机强迫关闭了一个现有的连接。。

### ISSUE THREAD

**Issue by dahuomao** [sochix/TLSharp#754]
var client = new TelegramClient(221656, "********************f476224016", store, "session");

await client.ConnectAsync();

然后就报错了。ConnectAsync() 无法将数据写入传输连接: 远程主机强迫关闭了一个现有的连接。。

**Comment by knocte** [comment]
English please.

**Comment by dahuomao** [comment]
var client = new TelegramClient(221656, "********************f476224016", store, "session");

await client.ConnectAsync();

then error, "An existing connection was forcibly closed by the remote host"

this method:client.ConnectAsync();

**Comment by jm-jack** [comment]
我也遇到同样的问题...你也是"翻墙"出来的吗? 估计是因为VPN.. 大量相同IP访问...服务器主动拒绝....

**Comment by legend2k** [comment]
看了两天协议包结构无果，果然还是VPN的问题。

**Comment by yqrj** [comment]
Is the problem solved? Is it because VPN connections can't be connected too much?
