### ISSUE TITLE
Forbidden Chats and Dialogs

### ISSUE THREAD

**Issue by DrEhsan** [sochix/TLSharp#76]
when we use LoadChatsAndUsers method for both of Channels and Forbidden chats (which you have been removed from groups) it returns ChatForbiddenConstructor so we can not recognize if chat_id is for a channel or it is really inaccessible for our session.

is there any way to filter  inaccessible group chat_id s? i wana to skip those and chat get chat_ids which are channels or groups that i have access to them.

https://github.com/sochix/TLSharp/blob/master/TLSharp.Core/TelegramClient.cs#L176

thanks

**Comment by sochix** [comment]
LoadChatsAndUsers isn't implemented well. Sorry can't help with it.

**Comment by DrEhsan** [comment]
@sochix what should i do if i want to implement it complete and what is the way to separate inaccessible groups from channels?

**Comment by sochix** [comment]
start from tests on exsisiting func. I'm not sure that it work
