### ISSUE TITLE
Anyone here exporting Telegram data (Users/Channels) into MSSQL?

### ISSUE THREAD

**Issue by mkellerman** [sochix/TLSharp#776]
I'm trying to evaluate if I should use one of the commonly knows Python projects, or this one, as a base, to collect Telegram information and save it in MSSQL.

Anyone else has done this? Or any experience doing so?

**Comment by knocte** [comment]
We use github issues to report bugs. For discussion, use our telegram channel.

**Comment by mkellerman** [comment]
Can you please provide me the link to the channel. Wasn’t able to find it. Thanks!
