### ISSUE TITLE
Read Channel Post

### ISSUE THREAD

**Issue by arfprogrammer** [sochix/TLSharp#78]
@sochix, I want to read channel posts, how can i do this?

**Comment by arfprogrammer** [comment]
i had been do this,
---function---
channels.getDialogs#a9d3d249 offset:int limit:int = messages.Dialogs;
--- class ---
dialogChannel#5b8496b2 peer:Peer top_message:int top_important_message:int read_inbox_max_id:int unread_count:int unread_important_count:int notify_settings:PeerNotifySettings pts:int = Dialog;
peerChannel#bddde532 channel_id:int = Peer;

i will soon update channel work, in my forked project from TLSharp

**Comment by sochix** [comment]
Waiting for your pull-request

**Comment by sochix** [comment]
Thread merged to Channel API https://github.com/sochix/TLSharp/issues/70#issuecomment-176725343

**Comment by hosseinGanjyar** [comment]
https://github.com/sochix/TLSharp/issues/520
