### ISSUE TITLE
Convert tdata to tlsharp session

### ISSUE THREAD

**Issue by CheshireCaat** [sochix/TLSharp#781]
Is it possible  to convert tdata to tlsharp session in dat file?

**Comment by nimix3** [comment]
Yeah, but not easy! you will need to read bytes by bytes of map file in tdata and separate it to AuthKey, DC, Phone and etc then easily write it to .dat format using TLSharp SessionStore!

**Comment by knocte** [comment]
What's tdata?

**Comment by nimix3** [comment]
Mr @knocte they call "Official Telegram Desktop" session file as tdata, in fact this is a folder contains map file that is binary and Session exist on it.

**Comment by knocte** [comment]
Thanks for the info @nimix3

**Comment by Arei15** [comment]
@nimix3 you can get sessoin from tdata?

**Comment by victor-pashuk** [comment]
> Is it possible to convert tdata to tlsharp session in dat file?

Sorry ,can you share a code example if you have?
