### ISSUE TITLE
tlsharp register new user don't have username in session

### ISSUE THREAD

**Issue by cainiaokun** [sochix/TLSharp#783]
when i register new user, default username is null

so i sendrequest like this to modify username

`TLUser tluser= await telegramClient.SendRequestAsync<TLUser>(new TeleSharp.TL.Account.TLRequestUpdateUsername() { Username = "myUsername"});`

but tlsharp can't auto update user.dat file

i try to `telegramClient.OnUserAuthenticated(tluser)` but it's still not update user.dat

`public void OnUserAuthenticated(TLUser TLUser)
{
_session.TLUser = TLUser;
 _session.SessionExpires = int.MaxValue;
_session.Save();
}`

TLUser.username in user.dat is always null

**Comment by cainiaokun** [comment]
![tlsharp](https://user-images.githubusercontent.com/31569568/42338629-064dcdde-80bd-11e8-8ce7-dea3584f4ae8.jpg)

**Comment by cainiaokun** [comment]
ok ，I solved it

**Comment by knocte** [comment]
how?
