### ISSUE TITLE
TLRequestGetBotCallbackAnswer click button didn't return

### ISSUE THREAD

**Issue by cainiaokun** [sochix/TLSharp#786]
`client.SendRequestAsync<TLBotCallbackAnswer>(new TLRequestGetBotCallbackAnswer()
{
	Peer = new TLInputPeerUser()
	{
		AccessHash = (long)user.AccessHash,
		UserId = user.Id
	},
	Data = btnCallback.Data,
	MsgId = msgId
}).Wait();`
some times it works fine
but most of the time it didn't return
any one have tlsharp click button code ?
help me please

**Comment by cainiaokun** [comment]
five days ,there is still no answer

**Comment by cainiaokun** [comment]
if i don't wait for it, the next request while throw "invalid checksum!"

**Comment by cainiaokun** [comment]
9 days, i solve it
because my btn is TLAbsKeyboardButton not convert to TLKeyboardButtonCallback

**Comment by tuananh14391** [comment]
> 9 days, i solve it
> because my btn is TLAbsKeyboardButton not convert to TLKeyboardButtonCallback

Can you share code?

**Comment by DeWizzard** [comment]
Share the solution please

**Comment by rnyPlanet** [comment]
> 9 days, i solve it
> because my btn is TLAbsKeyboardButton not convert to TLKeyboardButtonCallback


and how did you solve the problem?

**Comment by cainiaokun** [comment]
private void clickButton(TelegramClient client,TLUser u,
TLAbsKeyboardButton btn, TLMessage message)
        {
            if (btn is TLKeyboardButtonCallback btnCallback)
            {
                var req = new TLRequestGetBotCallbackAnswer()
                {
                    Peer = new TLInputPeerUser()
                    {
                        AccessHash = (long)u.AccessHash,
                        UserId = u.Id
                    },
                    Data = btnCallback.Data,
                    MsgId = message.Id
                };
                Console.WriteLine("点击按钮:" + btnCallback.Text);
                try
                {
                    client.SendRequestAsync<object>(req).Wait();
                }
                catch (Exception) { }
                //client._session.Save();
                Console.WriteLine("点击结束");
            }
            else if (btn is TLKeyboardButtonUrl btnUrl)
            {
                if (btnUrl.Url.IndexOf("https://t.me/") >= 0)
                {
                    joinChannel(client, btnUrl.Url).Wait();
                }
            }
            else
            {
                Console.WriteLine("otherbtn");
                Console.WriteLine(btn);
                Console.WriteLine("otherbtn");
            }
        }

Stanislav <notifications@github.com> 于2020年7月15日周三 下午11:14写道：

**Comment by rnyPlanet** [comment]
maybe you know how to answer on button ReplyKeyboardMarkup?
like this
![image](https://user-images.githubusercontent.com/33624178/87633654-67b77000-c744-11ea-88d2-3395933fa079.png)
