### ISSUE TITLE
Program terminates when calling client.SendCodeRequestAsync(+770527...)

### ISSUE THREAD

**Issue by timo4ka** [sochix/TLSharp#787]
public virtual async Task AuthUser()
        {
            TelegramClient client = new TelegramClient(352042, "b616900е5ed615d5e52985f7c87b5923");
            await client.ConnectAsync();
            string ph = "0";
            var hash = await client.SendCodeRequestAsync("+77052750709");
            var code = "384058"; // you can change code in debugger too
            TLUser user = null;
            Random rnd = new Random();
            for (int i = 0; i != 300; i++)
            {

            }
}
What am I doing wrong?

**Comment by derodevil** [comment]
Try to remove plus sign (+) in your phone number. It must be started with country code without plus

**Comment by knocte** [comment]
@timo4ka what do you mean with "Program terminates"? Please, if you receive an exception, reopen this issue and post the whole `ex.ToString()`. Thanks!
