### ISSUE TITLE
Authentication Workaround,working servers list, and other problems

### ISSUE THREAD

**Issue by delphiassistant** [sochix/TLSharp#8]
Hi
1- Every time I run make project I have to run AuthUser test and get a code from telegram, otherwise none of methods work and they wait for unlimited time.
Is there any workaround for this?

2- I tested these servers:

    Server 1: 149.154.175.50:443
    Server 2: 149.154.167.51:443
    Server 3: 149.154.175.100:443
    Server 4: 149.154.167.91:443
    Server 5: 91.108.56.165:443
and only server with address 149.154.167.91 works, other servers return exceptions when calling their methods. 
The exception is:
*Test method TLSharp.Tests.NotificatioClientTests.AuthUser threw exception: 
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.*

More strange part is that they send code to me using sms, and then return above exception.

Is there any reason for this?

3- When i send someone a message, his contact name changes to "My Test Name" for me. What to do with this?

**Comment by sochix** [comment]
1. When you run an AuthUser you create a telegram session, that stored in `session.dat` file. After this file created you can run any other tests or call api funcitons, but the file `session.dat` should always be near executable, otherwise will be created new empty one. See `Session.cs` for details.

2. Read about different DC here https://core.telegram.org/api/datacenter

3. Check the method send messsage. "My test name" is default name, you can change it to what you want.

**Comment by delphiassistant** [comment]
1- That's Correct. But when I open project while "session.dat" exists (it's size is 368 bytes) and run methods like CheckPhone without first running AuthUser test, it's execution never ends, when looking into debugger i see this message in debug logs:
* Exception	Exception thrown: 'System.OutOfMemoryException' in mscorlib.dll ("")*

**Comment by sochix** [comment]
It could be a bug, but do you specify numbers in App.config?

**Comment by delphiassistant** [comment]
*It could be a bug, but do you specify numbers in App.config?*
Sure, I did.

**Comment by starbug1** [comment]
Excuse me. what numbers we must specify in app.config? because i have just one simcard.

**Comment by sochix** [comment]
@starbug1 number of your contacts.

**Comment by sochix** [comment]
@delphiassistant don't know what happens with your session ;(
