### ISSUE TITLE
There is no CreateChannel Method in Telegram API

### ISSUE THREAD

**Issue by keyvanarasteh** [sochix/TLSharp#80]
i cant find CreateChannel Method in TelegramAPI...

anybody have a link or ... ???

i want to implement CreateChannel Method to TLSharp.. 

it's Emergency need, help plzzzzzzzz, tnXXX

**Comment by keyvanarasteh** [comment]
i'm researching about that and posting all found articles here :+1: 

trying to find solution from tdesktop source ;-) :100: 
```
mtpc_channels_getDialogs = 0xa9d3d249,
	mtpc_channels_getImportantHistory = 0xddb929cb,
	mtpc_channels_readHistory = 0xcc104937,
	mtpc_channels_deleteMessages = 0x84c1fd4e,
	mtpc_channels_deleteUserHistory = 0xd10dd71b,
	mtpc_channels_reportSpam = 0xfe087810,
	mtpc_channels_getMessages = 0x93d7b347,
	mtpc_channels_getParticipants = 0x24d98f92,
	mtpc_channels_getParticipant = 0x546dd7a6,
	mtpc_channels_getChannels = 0xa7f6bbb,
	mtpc_channels_getFullChannel = 0x8736a09,
	mtpc_channels_createChannel = 0xf4893d7f,
	mtpc_channels_editAbout = 0x13e27f1e,
	mtpc_channels_editAdmin = 0xeb7611d0,
	mtpc_channels_editTitle = 0x566decd0,
	mtpc_channels_editPhoto = 0xf12e57c9,
	mtpc_channels_toggleComments = 0xaaa29e88,
	mtpc_channels_checkUsername = 0x10e6bd2c,
	mtpc_channels_updateUsername = 0x3514b3de,
	mtpc_channels_joinChannel = 0x24b524c5,
	mtpc_channels_leaveChannel = 0xf836aa95,
	mtpc_channels_inviteToChannel = 0x199f3a6c,
	mtpc_channels_kickFromChannel = 0xa672de14,
	mtpc_channels_exportInvite = 0xc7560885,
	mtpc_channels_deleteChannel = 0xc0111fe3
```

**Comment by keyvanarasteh** [comment]
it's Create Channel Method : 

`channels.createChannel#f4893d7f flags:# broadcast:flags.0?true megagroup:flags.1?true title:string about:string = Updates;`

**Comment by DaveOff** [comment]
hi , what is flag ? can you create channel by this?

**Comment by keyvanarasteh** [comment]
@DaveOff : i'm working on it, i have to do that in next 24 hours.
it's emergency to me to do this :-1: 
i'll post all progress here for users ;-)

**Comment by sochix** [comment]
Let's merge this thread to https://github.com/sochix/TLSharp/issues/70#issuecomment-176725343
