### ISSUE TITLE
no response from client.ConnectAsync and GetContactsAsync

### ISSUE THREAD

**Issue by ackid32** [sochix/TLSharp#803]
Hi
for the past one week, the telegram client not working properly. As i check there is no response from 
await client.ConnectAsync 
await client.GetContactsAsync

I'm using the latest dlls 

I was not change any code that send messages without any problem, why it stopped now?

any help?

**Comment by knocte** [comment]
What does "problem" mean exactly? What do you mean with "stopped"? What does "not working" properly mean? Come on man, we're all programmers here, can you not act as a user? :)

**Comment by ackid32** [comment]
> 
> 
> What does "problem" mean exactly? What do you mean with "stopped"? What does "not working properly" mean? Come on man, we're all programmers here, can you not act as a user? :)

Sorry!
actually the 
await client.ConnectAsync not responding. I debug that and find that while on executing the line
await _sender.Receive(invokewithLayer); - is not responding (means await for infinite time!)
the same with await client.GetContactsAsync

What is the problem with - await _sender.Receive(invokewithLayer); which is worked properly till 10 days ago?

**Comment by ackid32** [comment]
No reply? Why no reply??

**Comment by knocte** [comment]
> means await for infinite time!

Infinite time may have meant that there was an infinite loop, an issue that I've tried to fix in a commit I have pushed today to master branch: https://github.com/sochix/TLSharp/commit/60a3c6235792163e9c74e9c24b1ca7800a220ce2.

Do you mind updating to use latest master (not sure when the new version will hit nuget.org though, use sources for now)? If after that you keep having this issue please reopen this bug.

> No reply? Why no reply??

This is an opensource project, run by volunteers. If people don't know an answer to your question, then nobody replies. Today I might have come up with a solution for your issue, as explained above, but am not 100% sure. Thanks for your understanding, hope it helps!
