### ISSUE TITLE
Sending to a username instead of PhoneNumber

### ISSUE THREAD

**Issue by mtbitcoin** [sochix/TLSharp#81]
Does the library support sending to a telegram username instead of using a phone number?

thanks

**Comment by sochix** [comment]
Now not, bit it very easy to develop.

**Comment by mtbitcoin** [comment]
where do we send the tips to ? :+1:

**Comment by sochix** [comment]
Done. Check ImportByUserNameAndSendMessage test.

**Comment by mtbitcoin** [comment]
thank you
