### ISSUE TITLE
I can't use TLSharp please help me

### ISSUE THREAD

**Issue by bahman309** [sochix/TLSharp#82]
hi dear

i can't run TLSharp...
when i run TLSharp.Test .... Error: a project with an OutPut Type of class library can not be started directly.

how to use TLSharp?
may explain with detail?

tanks alot

**Comment by sochix** [comment]
Try to run tests. It's a library, so you need to write some code to make it
work.
2 февр. 2016 г. 12:22 пользователь "bahman309" <notifications@github.com>
написал:

**Comment by bahman309** [comment]
why you closed this issues?

**Comment by sochix** [comment]
It's silly question, sorry

**Comment by bahman309** [comment]
your welcome
say hello to your mother
