### ISSUE TITLE
Not connected?

### ISSUE THREAD

**Issue by Sixerito** [sochix/TLSharp#823]
I try my code, and I cant authorize my client.

client = new TelegramClient(apiId, hash);
client.ConnectAsync(true);
var hash = await client.SendCodeRequestAsync(userNumber); // here throw error -- Not Connected!

What can i do?

Thanks you in advance!

**Comment by shahab47** [comment]
and me too :(((((((((((

**Comment by sjblom** [comment]
Were any of you able to past this?

**Comment by sjblom** [comment]
I've managed to get this working:

I basically enclosed "await client.ConnectAsync(true);" within a Task.Run();

`static void Main(string[] args)
        {
            using (var client = new TLSharp.Core.TelegramClient(apiId, apiHash))
            {
                Task.Run(async () =>
                {
                    await client.ConnectAsync(true);
                }).Wait();

                if (client.IsConnected)
                {
                    Console.WriteLine("Connected to Telegram service...");
                    
                    Console.WriteLine($"Code: {client.SendCodeRequestAsync(telNumber).Result}");
                }
            }
            Console.ReadLine();
        }`

**Comment by knocte** [comment]
@Sixerito : when you say `here throw error -- Not Connected!` what do you exactly mean? Do you mean that it throws an exception?

If this is the case, please reopen this bug and attach the whole `ex.ToString()`, thanks!
