### ISSUE TITLE
TLRequestGetStickerSet is not working properly

### ISSUE THREAD

**Issue by Topinambur223606** [sochix/TLSharp#826]
It says that TeleSharp.TL.TLStickerSet cannot be casted to TeleSharp.TL.Messages.TLStickerSet.

I downloaded source code and found that the problem is in class TeleSharp.TL.Messages.TLStickerSet:
there is property named Set which has wrong type:
`public TLStickerSet Set { get; set; }`
instead of
`public TL.TLStickerSet Set { get; set; }`
So property type now is class that it contains, lol.

I changed property type and it works now.
I'm sorry that it is not pull request, but I am not very familiar with git.

**Comment by raznahan** [comment]
Thanks, it worked! I was struggling with this for almost two days.

**Comment by knocte** [comment]
@CheshireCaat hey do you mind converting this suggestion into a PR? thanks!

**Comment by raznahan** [comment]
> @CheshireCaat hey do you mind converting this suggestion into a PR? thanks!

Sure. I will do this asap.

**Comment by CheshireCaat** [comment]
@knocte Let's give @raznahan opportunity to prove himself :D

**Comment by raznahan** [comment]
It's done now.

**Comment by aarani** [comment]
These changes will be reverted after every layer update you should never change anything in those folders or you should update generator as well.
