### ISSUE TITLE
Layer 82 or newer

### ISSUE THREAD

**Issue by nimix3** [sochix/TLSharp#827]
Hello,

Anyone has any opinion to update to newer (than 66) API layer?!
TLGenerator with newer layer schema cannot create correct class files or entire core need to update.

Good Luck.

**Comment by nimix3** [comment]
Ok, let's do it guys,

I try on Layer 74 but unsuccessful, everything compiled successfully but in send and receive of packets cannot cast correctly, I think some part of the core need to regenerate.

is there anyone try to update layers?

**Comment by nimix3** [comment]
[TeleSharp.TL.zip](https://github.com/sochix/TLSharp/files/2685320/TeleSharp.TL.zip)

The file of TL part attached...

**Comment by nimix3** [comment]
> > TLGenerator with newer layer schema cannot create correct class files
> 
> Why not?

You can check it by your self, newer layers has some missing class / method after conversion by TLGenerator!

I attach the file above just compile it together with TLSharp core and try to register a phone number.

**Comment by knocte** [comment]
> You can check it by your self, newer layers has some missing class / method after conversion by TLGenerator!

How can I check it by myself? Please be more specific, tell us what you did and the error you get.

**Comment by nimix3** [comment]
> > You can check it by your self, newer layers has some missing class / method after conversion by TLGenerator!
> 
> How can I check it by myself? Please be more specific, tell us what you did and the error you get.

Ok, First of All, download the [tl-schema.json](https://github.com/sochix/TLSharp/files/2690454/tl-schema.zip) file then copy in TLGenerator debug folder  "...\TeleSharp.Generator\bin\Debug" then run the TeleSharp.Generator.exe file and wait, after some seconds a new folder created with the name "TL" that there are many *.cs file inside of this folder!

Copy the TL folder and paste in "TeleSharp.TL" main folder then open the solution and compile the project, in the end, you have two files "TeleSharp.TL.dll" and "TLSharp.Core.dll" in "...\TLSharp.Core\bin\Debug" folder now you can use them inside your own projects.

when you want to use them you will get an error when trying to Register a new number, exactly in Connect part, the serialized body received by telegram cannot be deserialized and cause errors!

Please advise if you compile a newer API layer that 66 that is embedded in this repository! if not please be active and just do it, I bet you it takes few minutes not more!

**Comment by knocte** [comment]
> I bet you it takes few minutes not more!

I've never done this myself, so not sure what you're talking about. I just helped here and there, but never tinkered with the Generator.

> the serialized body received by telegram cannot be deserialized and cause errors!

Please paste the exact error.

**Comment by ilyalatt** [comment]
I have updated my fork of the library to work with 82 layer, https://github.com/ilyalatt/TLSharp.Fork, but it is entirely redesigned library

**Comment by nimix3** [comment]
Hi,

sorry for my late I was sick some days @knocte , your fork is nice @ilyalatt but if you provide some description for migration.

Good job.

**Comment by knocte** [comment]
Even if @ilyalatt's fork is good, its changes cannot be easily landed in TLSharp because they are not separated properly.

@nimix3 please answer to my latest comment where I ask you to paste the error
