### ISSUE TITLE
Identify Group and Channel

### ISSUE THREAD

**Issue by hosseinGanjyar** [sochix/TLSharp#829]
Hello every one,
I've getting dialogs and I want to identify group and channel. 
Before I did this by select dialogs with "**Username**" property (just channel dialogs had this property), but recently I have see this using in the groups. 
How to identify from another one? I just want get groups of dialogs.

**Comment by mkellerman** [comment]
Look at the Peer property. It will have a TLUser, TLChat or TLChannel object.

**Comment by hosseinGanjyar** [comment]
Where is this? In **Dialogs > item > Peer**? That has just 2 item **TLPeerChannel** , **TLPeerUser** !
Can I get Id+Access_hash through this?

**Comment by hosseinGanjyar** [comment]
Hi every body...You can ask your questions in this group:
https://t.me/joinchat/JRwh2w0A-7YlrMT_V4KhFQ

**Comment by hosseinGanjyar** [comment]
@mkellerman I have seen this, but I  had **TLChannel** in **Peer** for a group (I checked it with it's id)

**Comment by MasihAkbari** [comment]
it's simple, as Readme pointed out this area:
```
//get user dialogs
  var dialogs = (TLDialogsSlice) await client.GetUserDialogsAsync();

  //find channel by title
  var chat = dialogs.Chats
    .Where(c => c.GetType() == typeof(TLChannel))
    .Cast<TLChannel>()
    .FirstOrDefault(c => c.Title == "<channel_title>");
```

you can query out channels like this

**Comment by hosseinGanjyar** [comment]
@MasihAkbari That's right, but not for my issue. Please read my last comment carefully. I got a **_TLChannel in Peer for a group_** !!! 
Is it TRUE?!
As soon I send a capture of this.
Thanks

**Comment by MasihAkbari** [comment]
Please post code snippets that you are having trouble with and show us exactly what is the problem in here. AFAIK this is the way you can filter channels in a dialog, unless this is some sort of special case

**Comment by hosseinGanjyar** [comment]
@MasihAkbari ,After spend many hours I got this:
A _normal_ group is: **TeleSharp.TL.TLPeerChat**
A _super_ group is: **TeleSharp.TL.TLPeerChannel**
So now channel and supergroup are same in type. How do I identify group in dialogs?
Thanks

**Comment by MasihAkbari** [comment]
No it's not true, this is how you can identify them:

A _normal_ group is: **TeleSharp.TL.TLChat**
A _super_ group is: **TeleSharp.TL.TLChannel** with addition of property **Megagroup = true**
A _channel_ is: **TeleSharp.TL.TLChannel** with addition of property **Megagroup = false**

this is a bit wired but this is how it is

**Comment by hosseinGanjyar** [comment]
@MasihAkbari Ok, but **TLChat** haven't got **Access_hash**. I'll update this answer tomorrow...
.
.
.

**Comment by TaherianuBeac** [comment]
@hosseinGanjyar Could you get any new result? I did the same and I tried to send message to group but it is not possible, because it says `CHANNEL_INVALID` but it found the group.

**Comment by TaherianuBeac** [comment]
I fixed the issue in this way:
```
 await client.ConnectAsync();
            var dialogs = (await client.GetUserDialogsAsync()) as TLDialogsSlice;

            var chat = dialogs.Chats
                // TLChat means Group
                // TLChannel with addition of property Megagroup = true means Super Group
                // TLChannel with addition of property Megagroup = false means Channel
                .OfType<TLChat>()
                .FirstOrDefault(c => c.Title == "Test");                

            await client.SendMessageAsync(new TLInputPeerChat() { ChatId = chat.Id/*, AccessHash = chat.AccessHash.Value*/ }, "TEST MSG");
```

**Comment by hosseinGanjyar** [comment]
@TaherianuBeac  Hi, sorry I was busy.
My solution is like your answer.
Can I have your email?  Thanks

**Comment by SMPSLLC** [comment]
hey i think there is a problem with the variable types in the dll some variable must be long but it's int32 so we can't fetch all group list from our telegram account :/

i have this code for fetch group list but the response returns only 14 groups but i have more that 14 you know what i'm says ? that's the problem... here is my code :

```
var dialogs = await client.GetUserDialogsAsync() as TLDialogsSlice;
var chats = dialogs.Chats
                    .OfType<TLChat>()
                     .ToList();
Console.WriteLine("Count : " + chats.Count()); //output : 14; i have more that 14 why i can't fetch all them ?
```

**Comment by SMPSLLC** [comment]
> I fixed the issue in this way:
> 
> ```
>  await client.ConnectAsync();
>             var dialogs = (await client.GetUserDialogsAsync()) as TLDialogsSlice;
> 
>             var chat = dialogs.Chats
>                 // TLChat means Group
>                 // TLChannel with addition of property Megagroup = true means Super Group
>                 // TLChannel with addition of property Megagroup = false means Channel
>                 .OfType<TLChat>()
>                 .FirstOrDefault(c => c.Title == "Test");                
> 
>             await client.SendMessageAsync(new TLInputPeerChat() { ChatId = chat.Id/*, AccessHash = chat.AccessHash.Value*/ }, "TEST MSG");
> ```

you can fetch all group list using this code ?
i think no your code will only returns some left groups + some new ones but not all group you join on telegram.
