### ISSUE TITLE
Unable to read beyond the end of the stream

### ISSUE THREAD

**Issue by wasimjee** [sochix/TLSharp#83]
My Code

    String NumberToAuthenticate = "";
     FileSessionStore store;
     TelegramClient client;
     String hash = "";
     String code = "";
    NumberToAuthenticate = "Mobile Number With Country Code"; // using Mobile number with country code without + or leading Zero
    store = new FileSessionStore();
    client = new TelegramClient(store, "session");

    await client.Connect();

    hash = await client.SendCodeRequest(NumberToAuthenticate);

I am getting the Code in SMS, but error in hash

Please guide where am i wrong.

Even after deleting the Session.Dat, having same error

**Comment by wasimjee** [comment]
I Checked the codes and i found, i am getting error in this code

Page : AuthSendCodeRequest.cs

    public override void OnResponse(BinaryReader reader)
		{
			var boolTrue = 0x997275b5;
			var dataCode = reader.ReadUInt32(); // 0x2215bcbd
			_phoneRegistered = reader.ReadUInt32() == boolTrue;
			_phoneCodeHash = Serializers.String.read(reader);
			var sendCodeTimeout = reader.ReadInt32(); // This is the Line Getting Error in Reading
			var isPassword = reader.ReadUInt32() == boolTrue;
		}

Error is on This Line

    var sendCodeTimeout = reader.ReadInt32();

**Comment by sochix** [comment]
Seems like you to often send code to your phone, and that's why Telegram banned your number for some time.

**Comment by wasimjee** [comment]
Even with the new numbers having the same issue.

**Comment by sochix** [comment]
Do you use the same ip address?

**Comment by wasimjee** [comment]
Dis you mean for My IP of PC, or Telegram Server IP,

Yes i was connected to same IP ( My Server IP) and tried with different Telegram IP

**Comment by sochix** [comment]
I asking about your pc ip address. If it the same all the time than possibly problem in it.
