### ISSUE TITLE
System.OverflowException

### ISSUE THREAD

**Issue by afraz92** [sochix/TLSharp#84]
Hi,
sometimes I get this error when send text message(why? and solution?):
Exception	Exception thrown: 'System.OverflowException' in mscorlib.dll ("Arithmetic operation resulted in an overflow.")
Thanks.

**Comment by sochix** [comment]
Need a full stack trace and your codesnippet
5 февр. 2016 г. 1:28 пользователь "afraz92" <notifications@github.com>
написал:

**Comment by afraz92** [comment]
solved, Very thanks.

**Comment by sochix** [comment]
PLease, describe a problem a bit.

**Comment by Hamidnwo** [comment]
Hi, I found the source of this error:
The problem is that we are sending the same request in a short period of time.
The worked around is that we should avoid re-sending similar requests consecutively by sending a dummy requests in between.

**Comment by n3nikita** [comment]
> Hi, I found the source of this error:
> The problem is that we are sending the same request in a short period of time.
> The worked around is that we should avoid re-sending similar requests consecutively by sending a dummy requests in between.

Hello. I'm facing same error. Can you provide an example please?

**Comment by Hamidnwo** [comment]
Hi.
Happy to help.
The exception rises when the sending requests are too close and they are send together in the same packet over the network.
In theses cases the received packets are larger than expected for each of the request.
Just add a time delay between sending the requests:

await Task.Delay(getRandomWaitingTime(250, 650));

var _random = new Random();

public static int getRandomWaitingTime(int start, int end)
{
		return _random.Next(start, end);
}

The numbers of 250 and 650 milliseconds used to work fine the time I was working with Telegram Api.

You may need to increase them if you face any error.

Good luck

**Comment by n3nikita** [comment]
> Hi.
> Happy to help.
> The exception rises when the sending requests are too close and they are send together in the same packet over the network.
> In theses cases the received packets are larger than expected for each of the request.
> Just add a time delay between sending the requests:
> 
> await Task.Delay(getRandomWaitingTime(250, 650));
> 
> Random _random = new Random();
> 
> public int getRandomWaitingTime(int start, int end)
> {
> return _random.Next(start, end);
> }
> 
> The numbers of 250 and 650 milliseconds used to work fine the time I was working with Telegram Api.
> 
> You may need to increase them if you face any error.
> 
> Good luck

Thank you so much for the code example but I tried to add Task.Delay before sending file and at the start of the method but I got error `Invalid checksum` every time. I think it doesn't work for me because I'm sending big files (200mb - 500mb). Any advises?

**Comment by Hamidnwo** [comment]
Sorry, I haven't sent large files to check the behavior of the api, but I think you should prevent the interference of the requests using some kind of a queue. Invalid checksum error means the sending requests are transmitted together then the receiving responses have wrong checksum. 
Send a request, wait until finished, send another one.

**Comment by knocte** [comment]
> Send a request, wait until finished

How to know when it's finished?

**Comment by n3nikita** [comment]
> prevent the interference of the requests using some kind of a queue

How can I implement request queue?
