### ISSUE TITLE
Infinity loop - exception User located on a different DC: 4

### ISSUE THREAD

**Issue by lazyjohny500** [sochix/TLSharp#840]
Got loops.
Got `"USER_MIGRATE_4" `
`throw new UserMigrationException`
In `RequestWithDcMigration`

```
while(!completed){
await _sender.Receive(request);
}
```
catch and again `ReconnectToDcAsync`

So I can't understand what happening

Because `_session.DataCenter.DataCenterId.HasValue` is False
So it's not enter to your scope

```
                    if (_session.DataCenter.DataCenterId.HasValue &&
                        _session.DataCenter.DataCenterId.Value == e.DC)
                    {
                        throw new Exception($"Telegram server replied requesting a migration to DataCenter {e.DC} when this connection was already using this DataCenter", e);
                    }
```

#839

**Comment by knocte** [comment]
> Because `_session.DataCenter.DataCenterId.HasValue` is False

How can that be false? If a reconnect happens, the DataCenterId is filled with a new value, so it shouldn't be false. We need to understand how this happens.

**Comment by knocte** [comment]
@lazyjohny500 I wish I could reproduce your issue! If I could, I would likely be able to fix it.

But as I cannot, it has to be you who tries to find a fix, or you could try helping me to help you. For example, could you try this patch that I came up with?:

```
diff --git a/TLSharp.Core/TelegramClient.cs b/TLSharp.Core/TelegramClient.cs
index d9f0454..14544f7 100644
--- a/TLSharp.Core/TelegramClient.cs
+++ b/TLSharp.Core/TelegramClient.cs
@@ -25,7 +25,7 @@ namespace TLSharp.Core
         private TcpTransport _transport;
         private string _apiHash = "";
         private int _apiId = 0;
-        private Session _session;
+        private readonly Session _session;
         private List<TLDcOption> dcOptions;
         private TcpClientConnectionHandler _handler;

@@ -82,26 +82,25 @@ namespace TLSharp.Core
             if (dcOptions == null || !dcOptions.Any())
                 throw new InvalidOperationException($"Can't reconnect. Establish initial connection first.");

-            TLExportedAuthorization exported = null;
-            if (_session.TLUser != null)
-            {
-                TLRequestExportAuthorization exportAuthorization = new TLRequestExportAuthorization() { DcId = dcId };
-                exported = await SendRequestAsync<TLExportedAuthorization>(exportAuthorization);
-            }
-
-            var dc = dcOptions.First(d => d.Id == dcId);
+            var dc = dcOptions.First (d => d.Id == dcId);
             var dataCenter = new DataCenter (dcId, dc.IpAddress, dc.Port);

-            _transport = new TcpTransport(dc.IpAddress, dc.Port, _handler);
+            _transport = new TcpTransport (dc.IpAddress, dc.Port, _handler);
             _session.DataCenter = dataCenter;

-            await ConnectAsync(true);
+            await ConnectAsync (true);

+            TLExportedAuthorization exported = null;
             if (_session.TLUser != null)
             {
-                TLRequestImportAuthorization importAuthorization = new TLRequestImportAuthorization() { Id = exported.Id, Bytes = exported.Bytes };
-                var imported = await SendRequestAsync<TLAuthorization>(importAuthorization);
-                OnUserAuthenticated(((TLUser)imported.User));
+                TLRequestExportAuthorization exportAuthorization = new TLRequestExportAuthorization() { DcId = dcId };
+                exported = await SendRequestAsync<TLExportedAuthorization>(exportAuthorization);
+
+                await ConnectAsync (true);
+
+                TLRequestImportAuthorization importAuthorization = new TLRequestImportAuthorization () { Id = exported.Id, Bytes = exported.Bytes };
+                var imported = await SendRequestAsync<TLAuthorization> (importAuthorization);
+                OnUserAuthenticated ((TLUser)imported.User);
             }
         }
```

Thanks

**Comment by lazyjohny500** [comment]
I'l try and update...

**Comment by knocte** [comment]
What do you mean with "still not working"? Give more info.

**Comment by lazyjohny500** [comment]
It's mean that the infinity loops stop. 
But now I got System.InvalidOperationException: 'AUTH_KEY_UNREGISTERED'

**Comment by lazyjohny500** [comment]
It's looks like the first time is working correctly, and second time not working anymore. and got 'AUTH_KEY_UNREGISTERED'

**Comment by knocte** [comment]
Ok, can you try this instead:

```
diff --git a/TLSharp.Core/TelegramClient.cs b/TLSharp.Core/TelegramClient.cs
index d9f0454..e01d216 100644
--- a/TLSharp.Core/TelegramClient.cs
+++ b/TLSharp.Core/TelegramClient.cs
@@ -25,7 +25,7 @@ namespace TLSharp.Core
         private TcpTransport _transport;
         private string _apiHash = "";
         private int _apiId = 0;
-        private Session _session;
+        private readonly Session _session;
         private List<TLDcOption> dcOptions;
         private TcpClientConnectionHandler _handler;
 
@@ -82,13 +82,6 @@ namespace TLSharp.Core
             if (dcOptions == null || !dcOptions.Any())
                 throw new InvalidOperationException($"Can't reconnect. Establish initial connection first.");
 
-            TLExportedAuthorization exported = null;
-            if (_session.TLUser != null)
-            {
-                TLRequestExportAuthorization exportAuthorization = new TLRequestExportAuthorization() { DcId = dcId };
-                exported = await SendRequestAsync<TLExportedAuthorization>(exportAuthorization);
-            }
-
             var dc = dcOptions.First(d => d.Id == dcId);
             var dataCenter = new DataCenter (dcId, dc.IpAddress, dc.Port);
 
@@ -99,9 +92,14 @@ namespace TLSharp.Core
 
             if (_session.TLUser != null)
             {
-                TLRequestImportAuthorization importAuthorization = new TLRequestImportAuthorization() { Id = exported.Id, Bytes = exported.Bytes };
-                var imported = await SendRequestAsync<TLAuthorization>(importAuthorization);
-                OnUserAuthenticated(((TLUser)imported.User));
+                TLRequestExportAuthorization exportAuthorization = new TLRequestExportAuthorization() { DcId = dcId };
+                var exported = await SendRequestAsync<TLExportedAuthorization>(exportAuthorization);
+
+                TLRequestImportAuthorization importAuthorization = new TLRequestImportAuthorization () { Id = exported.Id, Bytes = exported.Bytes };
+                var imported = await SendRequestAsync<TLAuthorization> (importAuthorization);
+                OnUserAuthenticated ((TLUser)imported.User);
             }
         }
```

**Comment by lazyjohny500** [comment]
The same problem. Should I try to create a session/account again?

**Comment by knocte** [comment]
Not sure, maybe?

**Comment by lazyjohny500** [comment]
Again, worked twice. (create, load, load)
then 'AUTH_KEY_UNREGISTERED'

**Comment by knocte** [comment]
I'm out of ideas then :(

**Comment by lazyjohny500** [comment]
I saw a lot of issues that are open with the problem 'AUTH_KEY_UNREGISTERED'.
Maybe all is the same problem?

Can you write an example of load a session file and finish the usage (with dispose)?
Maybe I don't use that correctly?

**Comment by ArmeF97** [comment]
Same issue

**Comment by lazyjohny500** [comment]
Not good...and all other forks have the same issue?

**Comment by ArmeF97** [comment]
who knows?

**Comment by lazyjohny500** [comment]
@ArmeF97 I afraid Im using the load/close session file incorrectly.
Can you post an example? thats look ok?

```
                var sessionStore = new FileSessionStore();
                Client = new TelegramClient(ID, secret, sessionStore, _sessionFileName);
                if (!Client.ConnectAsync().Wait(TimeoutMilliseconds))
	{
		blabla....
	}

	SaveSessionFile()
                Client.Dispose();
                Client = null;
```

**Comment by ArmeF97** [comment]
you can find my code here https://github.com/ArmeF97/ArmeGram/blob/master/ArmeGram_3/MainActivity.cs and here https://github.com/ArmeF97/ArmeGram/blob/master/ArmeGram_3/ChatList.cs

**Comment by lazyjohny500** [comment]
@knocte It's just @ArmeF97 and mine? 
Have not encountered this problem too?

**Comment by lazyjohny500** [comment]
This code is working for the issue title.
> +                TLRequestExportAuthorization exportAuthorization = new TLRequestExportAuthorization() { DcId = dcId };
> +                var exported = await SendRequestAsync<TLExportedAuthorization>(exportAuthorization);
> +
> +                TLRequestImportAuthorization importAuthorization = new TLRequestImportAuthorization () { Id = exported.Id, Bytes = exported.Bytes };
> +                var imported = await SendRequestAsync<TLAuthorization> (importAuthorization);
> +                OnUserAuthenticated ((TLUser)imported.User);

**Comment by lazyjohny500** [comment]
> Ok, can you try this instead:
> 
> ```
> diff --git a/TLSharp.Core/TelegramClient.cs b/TLSharp.Core/TelegramClient.cs
> index d9f0454..e01d216 100644
> --- a/TLSharp.Core/TelegramClient.cs
> +++ b/TLSharp.Core/TelegramClient.cs
> @@ -25,7 +25,7 @@ namespace TLSharp.Core
>          private TcpTransport _transport;
>          private string _apiHash = "";
>          private int _apiId = 0;
> -        private Session _session;
> +        private readonly Session _session;
>          private List<TLDcOption> dcOptions;
>          private TcpClientConnectionHandler _handler;
>  
> @@ -82,13 +82,6 @@ namespace TLSharp.Core
>              if (dcOptions == null || !dcOptions.Any())
>                  throw new InvalidOperationException($"Can't reconnect. Establish initial connection first.");
>  
> -            TLExportedAuthorization exported = null;
> -            if (_session.TLUser != null)
> -            {
> -                TLRequestExportAuthorization exportAuthorization = new TLRequestExportAuthorization() { DcId = dcId };
> -                exported = await SendRequestAsync<TLExportedAuthorization>(exportAuthorization);
> -            }
> -
>              var dc = dcOptions.First(d => d.Id == dcId);
>              var dataCenter = new DataCenter (dcId, dc.IpAddress, dc.Port);
>  
> @@ -99,9 +92,14 @@ namespace TLSharp.Core
>  
>              if (_session.TLUser != null)
>              {
> -                TLRequestImportAuthorization importAuthorization = new TLRequestImportAuthorization() { Id = exported.Id, Bytes = exported.Bytes };
> -                var imported = await SendRequestAsync<TLAuthorization>(importAuthorization);
> -                OnUserAuthenticated(((TLUser)imported.User));
> +                TLRequestExportAuthorization exportAuthorization = new TLRequestExportAuthorization() { DcId = dcId };
> +                var exported = await SendRequestAsync<TLExportedAuthorization>(exportAuthorization);
> +
> +                TLRequestImportAuthorization importAuthorization = new TLRequestImportAuthorization () { Id = exported.Id, Bytes = exported.Bytes };
> +                var imported = await SendRequestAsync<TLAuthorization> (importAuthorization);
> +                OnUserAuthenticated ((TLUser)imported.User);
>              }
>          }
> ```




This code is working for the issue title.

**Comment by ArmeF97** [comment]
@lazyjohny500  can you link me directly a valid telegram client file a not a diff one? thanks 👍

**Comment by WhiteLionATX** [comment]
> @lazyjohny500 can you link me directly a valid telegram client file and not a diff one? thanks 👍

here is one, made by me: https://pastebin.com/FfAPax04
I would test bt since these bug leads to a loop and that loop is spam from the sight of telegram I get account locked for 24h and cant test like I would. So the with other words: I just made the changed lazyjohny500 posted without testing.

**Comment by knocte** [comment]
@WhiteLionATX can you test the latest diff I posted?

**Comment by WhiteLionATX** [comment]
> 
> 
> @WhiteLionATX can you test the latest diff I posted?

OK, I did tested. Here is my report:
 - My test was made with your changes ( latest diff: https://pastebin.com/FfAPax04 ) and the repo was up to date.
- My code for testing is this ( https://pastebin.com/XJScahRf ) 
- What I tested was to grab a file type of document.

Results:
NOW:
I noticed that the infnity loop is (kind of) solved , but the problem "AUTH_KEY_UNREGISTERED" still exist (loops a some time but not infinitly).
AND the file (document) I downloaded will not be downloaded. 

Additional details:
https://puu.sh/CVVbe/3e56f383a3.png
https://puu.sh/CVVjR/55eb3dc7c6.png

BEFORE:
Before your changes there was one successfull download and then the intinity loop starts:
"Exception thrown: 'TLSharp.Core.Network.UserMigrationException'
The loop send so many requests within a short time that Telegram locked my account for 24h.

**Comment by benjaminhpang** [comment]
@knocte I tested your latest diff and got the same result as @WhiteLionATX 

Any idea how we can fix this issue? Thanks~

**Comment by camanchaca** [comment]
I have the same bug. So I decided to filter dcOptions to ipv4 addresses only - it didn't help.
On screenshot after next step program will get next looping UserMigrationException. As you see, request says that I want to migrate from 4 to 2. But response says with next exception, that I must migrate to 2. And so on...
May be the reasons is dcOptions contains two addresses ipv4 for dc=4?
![Screenshot_2](https://user-images.githubusercontent.com/37511641/62503766-4a70e680-b7fe-11e9-90ef-6a1cd24d4a32.jpg)

**Comment by knocte** [comment]
@camanchaca I believe there's a bug somewhere in the DC retry-code yes, but I cannot reproduce it myself, so please keep digging until you find the problem.

**Comment by camanchaca** [comment]
@knocte 
[Code of telegram desktop](https://github.com/telegramdesktop/tdesktop/blob/c0f8ab8da0f58b7b167a68a37e5d044c237d9e4d/Telegram/SourceFiles/mtproto/mtp_instance.cpp#L1237) doesn't do migration, as I can undestand. These lines are commented.
They create a new session for new DC and send current request (failed with migrate exception) to this session.

ExportAuthorization executing only for errorCode=400, 401 and some other conditions.

**Comment by knocte** [comment]
> They create a new session for new DC and send current request (failed with migrate exception) to this session.

Ok, maybe we should do the same.

> ExportAuthorization executing only for errorCode=400, 401 and some other conditions.

Not sure I understand this.

**Comment by camanchaca** [comment]
ExportAuthorization is only in [this](https://github.com/telegramdesktop/tdesktop/blob/c0f8ab8da0f58b7b167a68a37e5d044c237d9e4d/Telegram/SourceFiles/mtproto/mtp_instance.cpp#L1317) condition. I don't know the reason to get errorCode=400 etc.

**Comment by knocte** [comment]
Ah I see. I don't know, then try removing it from the Reconnect function and see if it fixes your problem?

**Comment by camanchaca** [comment]
I saw in documentation, that every file must have DC. So getFile request must have parameter DC.
If absent (or wrong), FILE_MIGRATE_X will be generated always. In this case new MtProtoSender must be created (with new session or not?) for this DC and request resend with it. Something like this.
```
private async Task RequestWithDcMigration(TLMethod request, int? dc = null)
        {
            var sender = CreateSenderOrDefault(dc);
            if (sender == null)
                throw new InvalidOperationException("Not connected!");

            var completed = false;
            while(!completed)
            {
                try
                {
                    await sender.Send(request);
                    await sender.Receive(request);
                    completed = true;
                }
                catch (FileMigrationException ef)
                {
                    await RequestWithDcMigration(request, ef.DC);
                }
                catch(DataCenterMigrationException e)
                {
                    if (_session.DataCenter.DataCenterId.HasValue &&
                        _session.DataCenter.DataCenterId.Value == e.DC)
                    {
                        throw new Exception($"Telegram server replied requesting a migration to DataCenter {e.DC} when this connection was already using this DataCenter", e);
                    }

                    await ReconnectToDcAsync(e.DC);
                    // prepare the request for another try
                    request.ConfirmReceived = false;
                }
            }
        }
```

**Comment by knocte** [comment]
@camanchaca can you present your proposal in diff format please, it's much easier to read this way
