### ISSUE TITLE
Uploading audio bigger than 10MB causes 'Unknown File' without duration

### ISSUE THREAD

**Issue by koxap** [sochix/TLSharp#843]
Hello.
Trying to send .mp3 files to chat

there is 2 types:
<10 mb size:
` var fileResult = (TLInputFile)await client.UploadFile($"{name}.mp3", new StreamReader(file));`

10+ mb size:
`var fileResult = (TLInputFileBig)await client.UploadFile($"{name}.mp3", new StreamReader(file));`

and uploading:

```
                               await client.SendUploadedDocument(
                                   new TLInputPeerChat() { ChatId = sendto.id },
                                   fileResult,
                                   "", //caption
                                   "audio/mpeg", 
                                   new TLVector<TLAbsDocumentAttribute>() );
```

<10mb file loads successfully, and recognizes as audio file that you can play via telegram.
but **10+mb** files recognizes as "**Unknown file**" and there is no possibility to play it or see duration.

i tried to change mime-type for "audio/mp3", but it is not work.
_**help please!**_

**Comment by koxap** [comment]
Can somebody help, please?
I can pay for your time.

**Comment by koxap** [comment]
Big thanks for all for help.
i found solution.


                
                    var attr = new TLVector<TLAbsDocumentAttribute>();
                    var audio_attr = new TLDocumentAttributeAudio();
                   
                   
                        audio_attr.Performer = "Performer";
                        audio_attr.Title = "My song";
                    
                    attr.Add(audio_attr);

                    if (FileMBSize < 10) 
                    {
                        var fileResult = (TLInputFile)await client.UploadFile($"{name}.mp3", new StreamReader(file));


                            await client.SendUploadedDocument(
                                    new TLInputPeerUser() { UserId = sendto.id },
                                    fileResult,
                                    $"", //caption
                                    "audio/mpeg", 
                                    attr);

                        
                        
                    }
                    else
                    {
                        var fileResult = (TLInputFileBig)await client.UploadFile($"{name}.mp3", new StreamReader(file));


                            await client.SendUploadedDocument(
                                    new TLInputPeerUser() { UserId = sendto.id },
                                    fileResult,
                                    $"", //caption
                                    "audio/mpeg", 
                                    attr);
                            
                    }`

**Comment by knocte** [comment]
Would you want to improve the documentation around this please?
