### ISSUE TITLE
Checking whether the contact phone number is valid/exist ?

### ISSUE THREAD

**Issue by mtbitcoin** [sochix/TLSharp#85]
Is it possible to check whether the contact phone number is valid? Is this what the "IsPhoneRegistered" for?  And also for checking whether the username exists.

Is this currently possible with the existing library ?

**Comment by sochix** [comment]
To check if phone number is valid you need to use some separate validation code. 

To check if user is registered in Telegram -> you can use IsPhoneRegistered or ImportContact by phone number. It will return null, if user doesn't exsist. For checking username, use ImportByUserName in the same way.

**Comment by mtbitcoin** [comment]
Right now for the phone number checking I am doing the following: 

TLSharp.Tests.NotificatioClientTests t = new TLSharp.Tests.NotificatioClientTests();
t.CheckPhones("+60125519540").Wait();

However, its throwing the following error  :

System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: NETWORK_MIGRATE_5
   at TLSharp.Core.Network.MtProtoSender.HandleRpcResult(UInt64 messageId, Int32 sequence, BinaryReader messageReader, MTProtoRequest request) in C:\TLSharp\TLSharp.Core\Network\MtProtoSender.cs:line 288
   at TLSharp.Core.Network.MtProtoSender.processMessage(UInt64 messageId, Int32 sequence, BinaryReader messageReader, MTProtoRequest request) in C:\TLSharp\TLSharp.Core\Network\MtProtoSender.cs:line 193
   at TLSharp.Core.Network.MtProtoSender.<Recieve>d__9.MoveNext() in C:\TLSharp\TLSharp.Core\Network\MtProtoSender.cs:line 144

**Comment by mtbitcoin** [comment]
And when I enter certain other valid numbers it throwing the following instead 

System.InvalidOperationException: Your phone number registered to 5 dc. Please update settings. See https://github.com/sochix/TLSharp#i-get-an-error-migrate_x for details.
   at TLSharp.Core.Network.MtProtoSender.HandleRpcResult(UInt64 messageId, Int32 sequence,
 BinaryReader messageReader, MTProtoRequest request) in C:\TLSharp\TLSharp.Core\Network\Mt
ProtoSender.cs:line 284
   at TLSharp.Core.Network.MtProtoSender.processMessage(UInt64 messageId, Int32 sequence,
BinaryReader messageReader, MTProtoRequest request) in C:\TLSharp\TLSharp.Core\Network\MtP
rotoSender.cs:line 193
   at TLSharp.Core.Network.MtProtoSender.<Recieve>d__9.MoveNext() in C:\TLSharp\TLSharp.Co

**Comment by sochix** [comment]
Do you use latest version of library? The problem in ip address of dc, it's fixed in latest release.

**Comment by mtbitcoin** [comment]
Yes, I just cloned it a few hours earlier and am using the latest library

**Comment by sochix** [comment]
Paste your code-snippet here

**Comment by mtbitcoin** [comment]
Hi

This is the code snippet

var store = new FileSessionStore();
var client = new TelegramClient(store, "session");
await client.Connect();

var Someresult2 = await client.IsPhoneRegistered("+60121234567");
Console.WriteLine("Finished checking phonenumber +60121234567");
Assert.IsTrue(Someresult2);

**Comment by sochix** [comment]
Two things I noticed:
* provid phone without + (e.g. "60121234567")
* remove session.dat

**Comment by mtbitcoin** [comment]
@sochix do you have a Bitcoin address for tips?

**Comment by sochix** [comment]
Bitcoin wallet: **3K1ocweFgaHnAibJ3n6hX7RNZWFTFcJjUe**

**Comment by mtbitcoin** [comment]
@sochix sent a small tip. Thank you for your contribution to the .NET community :+1:

**Comment by sochix** [comment]
Thank you!

**Comment by sochix** [comment]
Added you to list of donators. https://github.com/sochix/TLSharp/blob/master/README.md#donations
