### ISSUE TITLE
How do I get users of a chat?

### ISSUE THREAD

**Issue by borseno** [sochix/TLSharp#854]
How do I get users of a chat? Not of a CHANNEL, but of a group chat.

that's how i get a chat I need.
            //find chat by title
            var chat = dialogs.Chats
              .Where(c => c.GetType() == typeof(TLChat))
              .Cast<TLChat>()
              .FirstOrDefault(c => c.Title == ChatTitle);

Now I want to get the list of users of that chat.
How do I get there? TLChat does not contain a property that returns the list of users in that group chat

**Comment by borseno** [comment]
I found how to do it with a group chat, I'll send the code later

**Comment by AndreyWh** [comment]
> I found how to do it with a group chat, I'll send the code later

Can u pls send it? I'll be grateful

**Comment by AndreyWh** [comment]
```C#
var dialogs = (TLDialogs)await client.GetUserDialogsAsync();
            var main = dialogs.Chats.ToList().Where(c => c.GetType() == typeof(TLChat))
                        .Cast<TLChat>()
                        .FirstOrDefault(c => c.Title == ("GROUP_NAME"));
            var req = new TLRequestGetFullChat
            {
                ChatId = main.Id
            };
            var res = await client.SendRequestAsync<TeleSharp.TL.Messages.TLChatFull>(req);
            var chatUsers = res.Users.ToList();
            foreach(var chatUser in chatUsers)
            {
                var user = chatUser as TLUser; // to get user id
                await client.SendMessageAsync(new TLInputPeerUser() { UserId = user.Id }, "<MESSAGE>");
            }
```
Maybe it could be useful for someone
