### ISSUE TITLE
How often do I need to call MakeAuth?

### ISSUE THREAD

**Issue by mikachi** [sochix/TLSharp#88]
Hello, 

Thank you for the perfect job with Telegram API!
I plan to use your client on a web server to send notifications to clients via Telegram.
I have to implement some kind of a tool that will allow me to update session file (AuthUser test analogue).
So I have some questions to you:
How long does the session live?
Will it extend it lifetime for any command i.e. browser session do? 

Maybe it is somehow possible to use client without entering telegram code each time?
I actually failed to ran any of your tests without calling AuthUser, but maybe I am missing something?

Thanks in advance and thanks once more for the great code.
Best regards,
Mike.

**Comment by sochix** [comment]
You need once create a session with MakeAuth -> than you can use this session for a long time. (can't now answer exact time span). You can just copy session.dat to your server. Or you can create your own ISessionStore and store all data in DB.

**Comment by mikachi** [comment]
Thanks for the reply.
And will it be prolonged with each call, so I could use some timer job to renew for example?

**Comment by sochix** [comment]
Yep, i think so. I advice you to read about session in Telegram API reference. https://core.telegram.org/
