### ISSUE TITLE
Get new message

### ISSUE THREAD

**Issue by rd1975** [sochix/TLSharp#89]
Hi sochix , How we can get all new message? 
in the GetMessagesHistoryForContact method we can get message history but we want to get person  that send new message then specified person message history
if it doesn't implement yet, how we can implement?
Thanks
Best regard

**Comment by sochix** [comment]
You need to implement updates handling. Check Telegram official API.

**Comment by AugerSoft** [comment]
Я добавил обработку сообщений, но в метод HandleUpdate он падает только при подключении. Как сделать: проверять по таймауту каждые n секунд или есть более кошерный способ?

**Comment by Frank213** [comment]
client.SendMessage(userId, "Hello Habr!");
Что тут userId?
если так ar userId =  client.ImportContactByPhoneNumber("79184981723"); то возникает 
Ошибка	CS1503	Аргумент 1: не удается преобразовать из "System.Threading.Tasks.Task<int?>" в "int". Как мне отправить сообщение по номеру телефона?
API_ID и API_HASH поменял на свои

**Comment by ibgithub** [comment]
first of all thank you for your TLSharp, it's awsome

I have same problem, how can I subscribing to updates? https://core.telegram.org/api/updates it is not clear how to subscribes? 
I already create class for methods updates.getState or updates.getDifference, after I call updates.getState I got values for pts, qts, date, seq, unread_count. And then I call updates.getDifference using pts, qts, date value, I always got  updates.differenceEmpty.

Please somebody help me to implement handling updates to get new messages?

**Comment by beppe9000** [comment]
Has this issue been closed because it is solved?

**Comment by gmix** [comment]
Здравствуйте! Огромное спасибо за библиотеку. Она просто отличная!
Возникала следующая проблема. Был написан проект на ASP.NET, на локальной машине все отлично работает,а после того как залили проект на Azure - нет соединения с серверами Telegram

**Comment by sochix** [comment]
Hey @gmix! It could be possible that Azure servers are blocked from Telegram servers. I need full logs to investigate further

**Comment by am2222** [comment]
@ibgithub could you find any way to fix this issue?

**Comment by leila-net** [comment]
hi all,
could you find any way to fix this issue?
I need to read new messages without calling and checking all channels in GetUserDialogsAsync result.

**Comment by mHCio** [comment]
Hi,
has anybody found a solution for that ?

**Comment by vailukhin** [comment]
Не могу установить соединение с сервером телеграм 149.154.175.100
Использовал разные прокси
Соединение не устанавливается ни через библиотеку ни через телнет соединение в кмд

**Comment by knocte** [comment]
@vailukhin English please, I don't understand Russian.

**Comment by a13ks3y** [comment]
> `client.SendMessage(userId, "Hello Habr!");` Что тут userId? если так `var userId = client.ImportContactByPhoneNumber("79184981723");` то возникает Ошибка CS1503 Аргумент 1: не удается преобразовать из "System.Threading.Tasks.Task<int?>" в "int". Как мне отправить сообщение по номеру телефона? API_ID и API_HASH поменял на свои


Probably should be async call?
`var userId = async client.ImportContactByPhoneNumber("79184981723");`
