### ISSUE TITLE
problem when running unit test

### ISSUE THREAD

**Issue by starbug1** [sochix/TLSharp#9]
after many struggling i am in this section now.
http://s3.picofile.com/file/8214980850/1.PNG
and Authuser test is running for more than 5 minute. what i must do. or what is wrong with my action?
Thanks.

**Comment by sochix** [comment]
You should check App.config in test, your api_id and hash_id. Just follow tutorial https://github.com/sochix/TLSharp#starter-guide.

**Comment by starbug1** [comment]
this is my app.config file
http://s6.picofile.com/file/8214998692/2.PNG
and this is TelegramClient.cs file
http://s6.picofile.com/file/8214998942/3.PNG
after this configurations i click on Run All. What i must do next or what i am doing wrong? Thanks.

**Comment by sochix** [comment]
Ohh, you should run conenction config test first. Than auth. One-by-one. Please read documentation.

**Comment by sochix** [comment]
Also in config file you should use three *DIFFERENT* numbers

**Comment by starbug1** [comment]
i have just one simcard.

**Comment by moradifx** [comment]
hi very very very very tank you sochix. :)


my app is connect and send message but error in hash code, please help

![image](https://cloud.githubusercontent.com/assets/13655263/10262961/78f2811e-69ea-11e5-9dbe-009963726749.png)

**Comment by delphiassistant** [comment]
I already explained in other posts, set server ip to 149.154.167.90 or 149.154.167.91 .
Other servers return error you posted above.

**Comment by delphiassistant** [comment]
**i have just one simcard.**
Other numbers than NumberToAuthenticate are number of message recipients.
