### ISSUE TITLE
How we can get active sessions? (As we can see them in Telegram application).

### ISSUE THREAD

**Issue by mianchoa** [sochix/TLSharp#907]
Hi guys,
How we get get all active sessions via TLSharp?
As we can see them in telegram application:

![ActiveSessions](https://user-images.githubusercontent.com/61012646/74535431-0c8e1100-4f4b-11ea-8f74-6db88b7e0cdf.PNG)

**Comment by CheshireCaat** [comment]
Official docs: https://core.telegram.org/method/account.getAuthorizations
TLSharp class: https://github.com/sochix/TLSharp/blob/master/TeleSharp.TL/TL/Account/TLRequestGetAuthorizations.cs

In readme there is an example of sending a custom request.

**Comment by CheshireCaat** [comment]
```csharp
var request = new TLRequestGetAuthorizations();

var response = await client.SendRequestAsync<TLAuthorizations>(req);
```

**Comment by mianchoa** [comment]
thank you very muh
