### ISSUE TITLE
Update Settings in order to prevent phone number registration error

### ISSUE THREAD

**Issue by saman-ghm** [sochix/TLSharp#92]
This is the code snippet which I have to check a phone number:
        ```
    var store = new FileSessionStore();
            var client = new TelegramClient(store, "session");
            await client.Connect();
            var result = await client.IsPhoneRegistered("989373738867");
            MessageBox.Show(result.ToString());

```
And this is the exception I'll get when I execute the code:

> Your phone number registered to 4 dc. Please update settings. See https://github.com/sochix/TLSharp#i-get-an-error-migrate_x for details.

**Comment by mtbitcoin** [comment]
this looks related to https://github.com/sochix/TLSharp/issues/85

**Comment by sochix** [comment]
Yep,the same problem
