### ISSUE TITLE
checkphone

### ISSUE THREAD

**Issue by nezam1** [sochix/TLSharp#94]
hello
I download latest Tlsharp and run Test Methods but checkphone()  have exception:

Test Name:	CheckPhones
Test FullName:	TLSharp.TLSharpTests.CheckPhones
Test Source:	C:\Androi\Downloads\TLSharp-master\TLSharp-master\TLSharp\TLSharpTests.cs : line 59
Test Outcome:	Failed
Test Duration:	0:00:08.147187

Result Message:	
Test method TLSharp.Tests.TLSharpTests.CheckPhones threw exception: 
System.InvalidOperationException: Your phone number registered to 4 dc. Please update settings. See https://github.com/sochix/TLSharp#i-get-an-error-migrate_x for details.

**Comment by sochix** [comment]
See this https://github.com/sochix/TLSharp/issues/85

**Comment by nezam1** [comment]
Thanks. I read them but I use telegram desktop and TLSharp together with same IP in session list device.
