### ISSUE TITLE
Dialogs Return Null

### ISSUE THREAD

**Issue by NimaZare** [sochix/TLSharp#947]
Hello
When I use this code, it returns an null value:
`TLDialogs dialogs = MyBot.GetUserDialogsAsync().Result as TLDialogs;`
It works well with my mobile number, but it returns an null value with my friend's number!
please help me.
thanks

**Comment by knocte** [comment]
You seem to not understand what the `as` keyword does in C#. Please learn about it first. Then reopen this issue if you keep having problems.

**Comment by NimaZare** [comment]
Hi dear friend
It has nothing to do with the keyword as!
I've used different methods but failed!
I've said before that, it works well with my mobile number, but it returns an empty value with my friend's mobile number!
I also used this code without the word as, it is still empty!

private async void CheckNewUsers()
{
    DataMachine db = new DataMachine();
    var dialogs = await MyBot.GetUserDialogsAsync();
    if (dialogs != null)
    {
        // To-Do
    }
    else
    {
        MessageBox.Show("Not Dialogs Available!", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
    }
}

please check it !
