### ISSUE TITLE
doesn't connect to server

### ISSUE THREAD

**Issue by MohammadHadi2031** [sochix/TLSharp#95]
I downloaded the TLSharp and added to my project and try to connect to telegram servers with my api_id and my api_hash with this code :

`var store = new FileSessionStore();
var client = new TelegramClient(store, "session");
await client.Connect();`

but TLSharp waiting on this line (await _tcpClient...) in TcpTransport.cs

`public async Task Send(byte[] packet)
{
    if (!_tcpClient.Connected)
        throw new InvalidOperationException("Client not connected to server.");

    var tcpMessage = new TcpMessage(sendCounter, packet);
    await _tcpClient.GetStream().WriteAsync(tcpMessage.Encode(), 0, tcpMessage.Encode()); 
    sendCounter++;
}`

**Comment by sochix** [comment]
Really strange problem. Can u use telegram web version? Is it blocked or not?

**Comment by MohammadHadi2031** [comment]
Yes I can

**Comment by sochix** [comment]
Try to remove ```session.dat```

**Comment by MohammadHadi2031** [comment]
there isn't any session.dat file

**Comment by sochix** [comment]
Maybe you have a firewall locally? Antivirus?

**Comment by MohammadHadi2031** [comment]
even after disabling firewall filtering VS2015 is waiting on this line
`await _tcpClient.GetStream().WriteAsync(tcpMessage.Encode(), 0, tcpMessage.Encode()); `

**Comment by MohammadHadi2031** [comment]
The problem solved 
that was cause of writing a line wrongly that I didn't know

**Comment by leila-net** [comment]
@MohammadHadi2031  and the same problem that I have!!!

what was that line of code ? or what is the solution?

**Comment by MohammadHadi2031** [comment]
Actually I didn't remember completely but I think it was related to working with Async function and I didn't use them carefully.
