### ISSUE TITLE
I can't kick a contact from the channel #TLRequestKickFromChannel()

### ISSUE THREAD

**Issue by bliznec-89** [sochix/TLSharp#953]
It doesn't show any errors, but the contact isn't deleted, what am I doing wrong?:

                var result = await client.GetContactsAsync();
                var uim = result.Users.ToList().Where(x => x.GetType() == typeof(TLUser)).Cast<TLUser>().FirstOrDefault(x => x.Phone == number);
                var dialogs = await client.GetUserDialogsAsync() as TLDialogsSlice;
                var chat = dialogs.Chats.ToList().Where(c => c.GetType() == typeof(TLChannel)).Cast<TLChannel>().LastOrDefault(c => c.Title == channelname);
                var inputuser = new TLInputUser() { AccessHash = uim.AccessHash.Value, UserId = uim.Id };
                var req2 = new TeleSharp.TL.Channels.TLRequestKickFromChannel() { Channel = new TLInputChannel() { AccessHash = chat.AccessHash.Value, ChannelId = chat.Id }, UserId = inputuser };
                var ups = await client.SendRequestAsync<TLUpdates>(req2);

**Comment by bliznec-89** [comment]
Fixed.

**Comment by knocte** [comment]
And you're gonna share how did you fix it?
