### ISSUE TITLE
How to get user object if not re-authenticated?

### ISSUE THREAD

**Issue by BitBargain** [sochix/TLSharp#956]
I apologize in advance if I am asking something basic, but after much googling, reading the FAQ etc I couldn't find an answer.

If I authenticate, I get a user object back which contains the ID, the username and some other useful info. However, if I need to launch the program again without having to authenticate this time (relying on the session store) then there is no user object.

Do I really need to extract this info from the session storage, or is there a better way, for example does the TelegramClient object hold it, or can I send some sort of "whoami" to the server to get the same type of info again? Thanks in advance.

**Comment by KoalaBear84** [comment]
You can use this:

```csharp
TUserFull userSelf = await TelegramClient.UsersService.GetUserFullAsync(new TInputUserSelf());
```

**Comment by BitBargain** [comment]
Fantastic, thanks for the speedy reply. In the meantime I've also found the answer to my question: basically yes, use the session's .Load() method, the TLUser object is right in there. But this .UsersService.GetUserFullAsync thing will come handy too.

Thanks again!

**Comment by KoalaBear84** [comment]
Ahh, sorry, I removed my answer almost immediately because I was replying because I thought it another library (OpenTL), but probably will also work in here indeed :)

Good you have succeeded.
