### ISSUE TITLE
dcoptions just have 3 dc

### ISSUE THREAD

**Issue by MohammadHadi2031** [sochix/TLSharp#96]
Hi
in dcOption list there are three dcs but my phone number is registered in 4 dc

**Comment by sochix** [comment]
TLSharp grabs dc configuration automatically from Telegram server.

**Comment by mikachi** [comment]
Hello, I've faced the same issue with "4 dc" how can I solve it?
Error says: Update settings.

**Comment by sochix** [comment]
remove session.dat and try again

**Comment by mikachi** [comment]
I've tried that with no help.
It happens for the one (known) specific number. I've found in TL documentation (https://core.telegram.org/api/datacenter) hint to export authorization using new dc_id. 
And I've found some pieces of code in your solution, but I don't see the exact migration mechanism.
Do I have to implement it by myself or am I missing something?

Thanks in advance.

**Comment by sochix** [comment]
I think export won't help.Try to debug initial request, which returns all available dc's.

**Comment by mikachi** [comment]
So, if I want to check if phone is registered, my sender should be connected to the same DC as the receiver phone I'm trying to check, is that true?

**Comment by jd1378** [comment]
so what should i do to fix this ? deleting session.dat didn't help

**Comment by jd1378** [comment]
interesting , i skipped checking phone number and sent the code without checking it , and it worked ,
but if two-steps authentication is enabled , it fails .
any ideas ?

**Comment by oldnavy1989** [comment]
I've got the same issue:
System.InvalidOperationException: Your phone number registered to 2 dc. Please update settings. See https://github.com/sochix/TLSharp#i-get-an-error-migrate_x for details.

I don't get what sould I do. Which settings sould I update?

**Comment by MohammadHadi2031** [comment]
Hello
Try this way:
Get telegram desktop and run it. 
Try to found the Ip to which telegram connected.
Write the ip and port and input them into session.cs 
`private const string defaultConnectionAddress = "91.108.56.165";
        private const int defaultConnectionPort = 443;`

**Comment by Veterinarr** [comment]
**Download telegram for desktop and run it. 
Try to find the Ip to which telegram connected.
Write the ip and port and input them into session.cs** 
Tryed this option, doesent help, still same error, phone registered in 2 dc.
