### ISSUE TITLE
How to login with Cloud Password (2-step Verification)

### ISSUE THREAD

**Issue by CeSiumUA** [sochix/TLSharp#961]
Hi! I'm using this library with some of Telegram accounts. However, I can't use it with account, protected with cloud password.
I've found a method MakeAuthWithPasswordAsync(), but I really don't know how to use it, because it requires TLPassword, so I'm stucking with it :(

**Comment by vuminhit** [comment]
```
TLUser user = await client.MakeAuthAsync(sPhone, phoneCodeHash, sCode);
var passwordSettings = await client.GetPasswordSetting();
user = await client.MakeAuthWithPasswordAsync(passwordSettings, cloud_pass);
```

**Comment by CeSiumUA** [comment]
> ```
> TLUser user = await client.MakeAuthAsync(sPhone, phoneCodeHash, sCode);
> var passwordSettings = await client.GetPasswordSetting();
> user = await client.MakeAuthWithPasswordAsync(passwordSettings, cloud_pass);
> ```

Thank you very much!)
It worked!
