### ISSUE TITLE
HELP ME

### ISSUE THREAD

**Issue by JapanMarten** [sochix/TLSharp#966]
[!] Getting Flood Error from telegram. 
[!] Script is stopping now. 
[!] Please try again after some time.

**Comment by hosseinGanjyar** [comment]
Please contact me:
Hossein.ganjyar@gmail.com

**Comment by hosseinGanjyar** [comment]
https://github.com/sochix/TLSharp/issues/973#issue-671873804

**Comment by knocte** [comment]
Please read https://github.com/sochix/TLSharp#why-do-i-get-a-floodexceptionflood_wait-error first.
