### ISSUE TITLE
Freeze app

### ISSUE THREAD

**Issue by haghft** [sochix/TLSharp#97]
sometimes when i send a message the my app freezed and dont throw exception and only freezed!
help me plz

**Comment by sochix** [comment]
Read this https://github.com/sochix/TLSharp#nothing-helps

**Comment by unn4m3d** [comment]
Had the same issue

**Comment by knocte** [comment]
@unn4m3d are you sure you're using the last master?

**Comment by unn4m3d** [comment]
@knocte I used package from [here](https://ci.appveyor.com/project/sochix/tlsharp/build/1.0.178)

P.S. Freezes are still happening with last build (1.0.180)

**Comment by knocte** [comment]
@sochix does that version include the FloodException-inclusion change?
