### ISSUE TITLE
offset = 0 return real count | offset <> 0 return count = 10002 ?!!!

### ISSUE THREAD

**Issue by elmagekmosaad** [sochix/TLSharp#970]
i have error with offest
whene use this code
{
    var request = new TLRequestGetParticipants() { offset = offset, limit = 200, Dirty = true, channel = new TLInputChannel() { access_hash = x.access_hash.Value, channel_id = x.id }, filter = new TLChannelParticipantsRecent() };
}

 TLChannelParticipants members = Await client.SendRequestAsync<TLChannelParticipants>(request);

if offset value = 0 it's return users count = 14500
if  offset value = any integer else 0 it's  return users count = 10002

offset = 0 return real count
offset <> 0 return count = 10002
please any help hot to fix ?

**Comment by elmagekmosaad** [comment]
Anybody here ?

**Comment by elmagekmosaad** [comment]
Anybody here ?

**Comment by Vxer-Lee** [comment]
I have the same problem！
