### ISSUE TITLE
How to authinticate user with password?

### ISSUE THREAD

**Issue by Muaath5** [sochix/TLSharp#978]
## I want to authinticate using `MakeAuthWithPasswordAsync`
**and I don't have `TLPassword` to pass it as parameter!**
I have this code:
```c#
public async void Authinticate()
{
    await Client.ConnectAsync();

    Console.WriteLine("Enter your password:");
    string password = Console.ReadLine();

    // Here is the problem: 
    await Client.MakeAuthWithPassword(/*???*/, password);
}
```

How to offer `TLPassword` object to `MakeAuthWithPasswordAsync `method??

**Comment by Laiteux** [comment]
`await Client.GetPasswordSetting();`

**Comment by Hedgehog734** [comment]
`TLPassword settings = await client.GetPasswordSetting();`

**Comment by knocte** [comment]
@aarani is this related to SRP?

**Comment by Muaath5** [comment]
> 
> 
> `TLPassword settings = await client.GetPasswordSetting();`

Not working :( 
Because exception `CloudPasswordNeededException`
What sould i do.
I start with code auth then password.
In the code auth error

**Comment by Hedgehog734** [comment]
1. `await client.SendCodeRequestAsync(phoneNumber);`

2. `await client.MakeAuthAsync(phoneNumber, hash, code);` <-- `CloudPasswordNeededException` thrown if two-factor enabled

3. `var passwordSettings = await client.GetPasswordSetting();`
   `await client.MakeAuthWithPasswordAsync(passwordSettings, password);` <-- `InvalidCastException` thrown if two-factor disabled

So for user with two-factor enabled: 1-2-3
For user with two-factor disabled: 1-2

**Comment by Muaath5** [comment]
> 1. `await client.SendCodeRequestAsync(phoneNumber);`
> 2. `await client.MakeAuthAsync(phoneNumber, hash, code);` <-- `CloudPasswordNeededException` thrown if two-factor enabled
> 3. `var passwordSettings = await client.GetPasswordSetting();` <-- `InvalidCastException` thrown if two-factor disabled
>    `await client.MakeAuthWithPasswordAsync(passwordSettings, password);`
> 
> So for user with two-factor enabled: 1-2-3
> For user with two-factor disabled: 1-2

How can I do **step 2** and step two will throw `CloudPasswordNeededException`, @Hedgehog734 ?!

**Comment by Muaath5** [comment]
I understand after some time, This code is login method for console apps:
Thank you, @Hedgehog734 
```c#
TelegramClient.ConnectAsync();

Console.Write("Enter your phone number: ");
string phone = Console.ReadLine();

string codeHash = await TelegramClient.SendCodeRequestAsync(phone);

Console.Write("Enter your Telegram code: ");
string code = Console.ReadLine();

TLUser user;
try
{
    user = await TelegramClient.MakeAuthAsync(phone, code, codeHash);
}
catch (CloudPasswordNeededException)
{
    TLPassword passwordSetting = await TelegramClient.GetPasswordSetting();
    Console.WriteLine("This account needs cloud password.");

TryAgain:
    Console.Write("Enter your password: ");
    string password = Console.ReadLine();

    try
    {
        user = await TelegramClient.MakeAuthWithPasswordAsync(password, passwordSetting);
    }
    catch // If wrong password
    {
        Console.WriteLine("Hint: " + passwordSetting.Hint);

        if (passwordSetting.HasRecovery)
        {
            Console.WriteLine("Do you want to reset your password? [Y|N]");
            string answer = Console.ReadLine();
            if (answer == "Y")
            {
                Console.WriteLine("Recovery email: " + passwordSetting.EmailUnconfirmedPattern);

                // Recover password
                Console.Write("Enter email recovery code: ");
                string recoveryCode = Console.ReadLine();
                TelegramClient.SendRequestAsync<TLRequestRecoverPassword>(new TLRequestRecoverPassword() { Code = recoveryCode });
            }
        }
        else
        {
            Console.WriteLine("This account doesn't have recovery!");
        }

        goto TryAgain;
    }
}
```
