### ISSUE TITLE
invalid constructor code 990D1493

### ISSUE THREAD

**Issue by rmmahryar** [sochix/TLSharp#99]
hi i use ImportContactByPhoneNumber and SendMessage for send message for my friend .
ImportContactByPhoneNumber("my friend phone") return this error  "invalid constructor code 990D1493"

**Comment by haghft** [comment]
i have same problem and freezed my app!
![freezed](https://cloud.githubusercontent.com/assets/5370842/13202403/96fe05ce-d8ae-11e5-9ff9-ae230886f6a3.jpg)

**Comment by haghft** [comment]
sometimes when run my program in debug window program output: Should wait 84600 sec and freezed my UI!

**Comment by sochix** [comment]
@haghft check this https://github.com/sochix/TLSharp#why-i-get-flood_wait-error

**Comment by hosseinGanjyar** [comment]
I solved this issue. please send your question in my group:
https://t.me/joinchat/HhLHow3Ed97A0gRZo7Ggog
